In [3]:
import pandas as pd
import os

files = [f for f in os.listdir() if f.endswith(('.csv', '.xlsx' , '.xls'))]

print(files)

['admission.csv', 'Bed management.csv.xlsx', 'bed.csv', 'billing.csv', 'billing_detail.csv', 'department.csv', 'diagnostic_test.csv', 'disease.csv', 'doctor.csv', 'drug.csv', 'drug_inventory.csv', 'drug_manufacturer.csv', 'employee.csv', 'HMIS_Cleaned_Data.xlsx', 'insurance_provider.csv', 'patient.csv', 'patient_diagnostic.csv', 'patient_insurance.csv', 'prescription.csv', 'readmission_cleaned.csv.xls', 'staff_assignment.csv', 'ward.csv']

In [2]:
import pandas as pd
import os

hmis_files = [
    f for f in os.listdir()
    if f.endswith('.csv') and f.lower() != 'bed management.csv.xlsx'
]

profile = []

for file in hmis_files:
    df = pd.read_csv(file)

    profile.append({
        'File': file,
        'Rows': df.shape[0],
        'Columns': df.shape[1],
        'Missing Values': df.isnull().sum().sum(),
        'Duplicate Rows': df.duplicated().sum()
    })

profile_df = pd.DataFrame(profile)

profile_df

                      File    Rows  Columns  Missing Values  Duplicate Rows
0            admission.csv   45000       10               0               0
1                  bed.csv     415        4               0               0
2              billing.csv   45000        8               0               0
3       billing_detail.csv  112402        5           67402               0
4           department.csv      11        5               0               0
5      diagnostic_test.csv       9        5               0               0
6              disease.csv      20        3               0               0
7               doctor.csv      98        5               0               0
8                 drug.csv     250        6               0               0
9       drug_inventory.csv     250        6               0               0
10   drug_manufacturer.csv     300        5               0               0
11            employee.csv     500        7               0               0
12  insurance_provider.csv      50        5               0               0
13             patient.csv   30000        6               0               0
14  patient_diagnostic.csv   63269        6               0               0
15   patient_insurance.csv   21617        7               0               0
16        prescription.csv   73109        6               0               0
17    staff_assignment.csv     207        4               0               0
18                ward.csv      27        5               0               0

In [4]:
import os

files = os.listdir()

for f in files:
    print(f)

.ipynb_checkpoints
01_data_understanding.ipynb
admission.csv
Bed management.csv.xlsx
bed.csv
billing.csv
billing_detail.csv
department.csv
diagnostic_test.csv
disease.csv
doctor.csv
drug.csv
drug_inventory.csv
drug_manufacturer.csv
employee.csv
HMIS_Cleaned_Data.xlsx
insurance_provider.csv
patient.csv
patient_diagnostic.csv
patient_insurance.csv
prescription.csv
readmission_cleaned.csv.xls
staff_assignment.csv
ward.csv

In [8]:
import pandas as pd
import os

files = os.listdir()

profile = []

for file in files:

    try:
        
        if file.lower().endswith(".csv"):
            df = pd.read_csv(file)

        
        elif file.lower().endswith(".xlsx"):
            df = pd.read_excel(file, engine="openpyxl")

        elif file.lower().endswith(".xls"):
            df = pd.read_excel(file, engine="xlrd")

        else:
            continue

        profile.append({
            "File": file,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
            "Missing Values": df.isnull().sum().sum(),
            "Duplicate Rows": df.duplicated().sum()
        })

    except Exception as e:
        print("ERROR:", file)
        print(e)

profile_df = pd.DataFrame(profile)

profile_df

                        File    Rows  Columns  Missing Values  Duplicate Rows
0              admission.csv   45000       10               0               0
1    Bed management.csv.xlsx    1000       21               0               0
2                    bed.csv     415        4               0               0
3                billing.csv   45000        8               0               0
4         billing_detail.csv  112402        5           67402               0
5             department.csv      11        5               0               0
6        diagnostic_test.csv       9        5               0               0
7                disease.csv      20        3               0               0
8                 doctor.csv      98        5               0               0
9                   drug.csv     250        6               0               0
10        drug_inventory.csv     250        6               0               0
11     drug_manufacturer.csv     300        5               0               0
12              employee.csv     500        7               0               0
13    HMIS_Cleaned_Data.xlsx   30000        6               0               0
14    insurance_provider.csv      50        5               0               0
15               patient.csv   30000        6               0               0
16    patient_diagnostic.csv   63269        6               0               0
17     patient_insurance.csv   21617        7               0               0
18          prescription.csv   73109        6               0               0
19  readmission_cleaned.xlsx   10000       26               0               0
20      staff_assignment.csv     207        4               0               0
21                  ward.csv      27        5               0               0

In [2]:
import pandas as pd
import os

hmis_files = [
    f for f in os.listdir()
    if f.lower().endswith(".csv")
]

for file in hmis_files:
    df = pd.read_csv(file)

    print("\n" + "=" * 60)
    print("FILE:", file)
    print("Columns:", list(df.columns))
    print("\nData Types:")
    print(df.dtypes)

============================================================
FILE: admission.csv
Columns: ['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id']

Data Types:
admission_id        int64
admission_date        str
discharge_date        str
admission_type        str
admission_status      str
patient_id          int64
department_id       int64
ward_id             int64
bed_id              int64
disease_id          int64
dtype: object

============================================================
FILE: bed.csv
Columns: ['bed_id', 'bed_number', 'bed_status', 'ward_id']

Data Types:
bed_id        int64
bed_number      str
bed_status      str
ward_id       int64
dtype: object

============================================================
FILE: billing.csv
Columns: ['bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode', 'admission_id']

Data Types:
bill_id                       int64
bill_date                       str
total_amount                  int64
insurance_covered_amount    float64
patient_payable_amount      float64
payment_status                  str
payment_mode                    str
admission_id                  int64
dtype: object

============================================================
FILE: billing_detail.csv
Columns: ['billing_detail_id', 'charge_type', 'reference_id', 'amount', 'bill_id']

Data Types:
billing_detail_id      int64
charge_type              str
reference_id         float64
amount                 int64
bill_id                int64
dtype: object

============================================================
FILE: department.csv
Columns: ['department_id', 'department_name', 'department_type', 'floor_number', 'status']

Data Types:
department_id      int64
department_name      str
department_type      str
floor_number       int64
status               str
dtype: object

============================================================
FILE: diagnostic_test.csv
Columns: ['test_id', 'test_name', 'test_category', 'standard_cost', 'department_id']

Data Types:
test_id          int64
test_name          str
test_category      str
standard_cost    int64
department_id    int64
dtype: object

============================================================
FILE: disease.csv
Columns: ['disease_id', 'disease_name', 'disease_category']

Data Types:
disease_id          int64
disease_name          str
disease_category      str
dtype: object

============================================================
FILE: doctor.csv
Columns: ['doctor_id', 'employee_id', 'specialization', 'qualification', 'experience_years']

Data Types:
doctor_id           int64
employee_id         int64
specialization        str
qualification         str
experience_years    int64
dtype: object

============================================================
FILE: drug.csv
Columns: ['drug_id', 'drug_name', 'brand_name', 'drug_category', 'unit_cost', 'manufacturer_id']

Data Types:
drug_id            int64
drug_name            str
brand_name           str
drug_category        str
unit_cost          int64
manufacturer_id    int64
dtype: object

============================================================
FILE: drug_inventory.csv
Columns: ['inventory_id', 'current_stock', 'reorder_level', 'inventory_status', 'last_restock_date', 'drug_id']

Data Types:
inventory_id         int64
current_stock        int64
reorder_level        int64
inventory_status       str
last_restock_date      str
drug_id              int64
dtype: object

============================================================
FILE: drug_manufacturer.csv
Columns: ['manufacturer_id', 'manufacturer_name', 'country', 'reliability_rating', 'contract_status']

Data Types:
manufacturer_id         int64
manufacturer_name         str
country                   str
reliability_rating    float64
contract_status           str
dtype: object

============================================================
FILE: employee.csv
Columns: ['employee_id', 'employee_name', 'gender', 'role', 'employment_type', 'date_of_joining', 'department_id']

Data Types:
employee_id        int64
employee_name        str
gender               str
role                 str
employment_type      str
date_of_joining      str
department_id      int64
dtype: object

============================================================
FILE: insurance_provider.csv
Columns: ['insurance_provider_id', 'provider_name', 'provider_type', 'contact_details', 'coverage_limit']

Data Types:
insurance_provider_id    int64
provider_name              str
provider_type              str
contact_details          int64
coverage_limit           int64
dtype: object

============================================================
FILE: patient.csv
Columns: ['patient_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number']

Data Types:
patient_id        int64
gender              str
date_of_birth       str
blood_group         str
city                str
contact_number      str
dtype: object

============================================================
FILE: patient_diagnostic.csv
Columns: ['patient_diagnostic_id', 'test_date', 'result_status', 'admission_id', 'test_id', 'doctor_id']

Data Types:
patient_diagnostic_id    int64
test_date                  str
result_status              str
admission_id             int64
test_id                  int64
doctor_id                int64
dtype: object

============================================================
FILE: patient_insurance.csv
Columns: ['patient_insurance_id', 'policy_number', 'coverage_percentage', 'policy_start_date', 'policy_end_date', 'patient_id', 'insurance_provider_id']

Data Types:
patient_insurance_id     int64
policy_number              str
coverage_percentage      int64
policy_start_date          str
policy_end_date            str
patient_id               int64
insurance_provider_id    int64
dtype: object

============================================================
FILE: prescription.csv
Columns: ['prescription_id', 'dosage', 'frequency', 'duration_days', 'admission_id', 'drug_id']

Data Types:
prescription_id    int64
dosage               str
frequency            str
duration_days      int64
admission_id       int64
drug_id            int64
dtype: object

============================================================
FILE: staff_assignment.csv
Columns: ['assignment_id', 'employee_id', 'ward_id', 'shift']

Data Types:
assignment_id    int64
employee_id      int64
ward_id          int64
shift              str
dtype: object

============================================================
FILE: ward.csv
Columns: ['ward_id', 'ward_name', 'ward_type', 'total_beds', 'department_id']

Data Types:
ward_id          int64
ward_name          str
ward_type          str
total_beds       int64
department_id    int64
dtype: object

In [3]:
for file in hmis_files:
    df = pd.read_csv(file)

    print("\n" + "=" * 70)
    print("FILE:", file)

    print("\nNumber of unique values:")
    print(df.nunique())

    print("\nNumber of rows:", len(df))

======================================================================
FILE: admission.csv

Number of unique values:
admission_id        45000
admission_date       2192
discharge_date       2203
admission_type          2
admission_status        1
patient_id          23275
department_id           6
ward_id                27
bed_id                145
disease_id             20
dtype: int64

Number of rows: 45000

======================================================================
FILE: bed.csv

Number of unique values:
bed_id        415
bed_number    415
bed_status      2
ward_id        27
dtype: int64

Number of rows: 415

======================================================================
FILE: billing.csv

Number of unique values:
bill_id                     45000
bill_date                    2203
total_amount                32874
insurance_covered_amount    32763
patient_payable_amount      39533
payment_status                  2
payment_mode                    4
admission_id                45000
dtype: int64

Number of rows: 45000

======================================================================
FILE: billing_detail.csv

Number of unique values:
billing_detail_id    112402
charge_type               4
reference_id            145
amount                31815
bill_id               45000
dtype: int64

Number of rows: 112402

======================================================================
FILE: department.csv

Number of unique values:
department_id      11
department_name    11
department_type     3
floor_number        5
status              1
dtype: int64

Number of rows: 11

======================================================================
FILE: diagnostic_test.csv

Number of unique values:
test_id          9
test_name        9
test_category    2
standard_cost    9
department_id    2
dtype: int64

Number of rows: 9

======================================================================
FILE: disease.csv

Number of unique values:
disease_id          20
disease_name        20
disease_category    11
dtype: int64

Number of rows: 20

======================================================================
FILE: doctor.csv

Number of unique values:
doctor_id           98
employee_id         98
specialization       9
qualification        4
experience_years    34
dtype: int64

Number of rows: 98

======================================================================
FILE: drug.csv

Number of unique values:
drug_id            250
drug_name          142
brand_name         250
drug_category        8
unit_cost          192
manufacturer_id    172
dtype: int64

Number of rows: 250

======================================================================
FILE: drug_inventory.csv

Number of unique values:
inventory_id         250
current_stock        218
reorder_level        151
inventory_status       2
last_restock_date    234
drug_id              250
dtype: int64

Number of rows: 250

======================================================================
FILE: drug_manufacturer.csv

Number of unique values:
manufacturer_id       300
manufacturer_name     295
country                 5
reliability_rating     15
contract_status         2
dtype: int64

Number of rows: 300

======================================================================
FILE: employee.csv

Number of unique values:
employee_id        500
employee_name      499
gender               2
role                 5
employment_type      2
date_of_joining    477
department_id       11
dtype: int64

Number of rows: 500

======================================================================
FILE: insurance_provider.csv

Number of unique values:
insurance_provider_id    50
provider_name            50
provider_type             2
contact_details          50
coverage_limit            7
dtype: int64

Number of rows: 50

======================================================================
FILE: patient.csv

Number of unique values:
patient_id        30000
gender                3
date_of_birth     19760
blood_group           8
city              17836
contact_number    30000
dtype: int64

Number of rows: 30000

======================================================================
FILE: patient_diagnostic.csv

Number of unique values:
patient_diagnostic_id    63269
test_date                 2202
result_status                2
admission_id             31512
test_id                      9
doctor_id                   50
dtype: int64

Number of rows: 63269

======================================================================
FILE: patient_insurance.csv

Number of unique values:
patient_insurance_id     21617
policy_number            21613
coverage_percentage          5
policy_start_date            4
policy_end_date              6
patient_id               18000
insurance_provider_id       50
dtype: int64

Number of rows: 21617

======================================================================
FILE: prescription.csv

Number of unique values:
prescription_id    73109
dosage                 2
frequency              3
duration_days         12
admission_id       29287
drug_id              250
dtype: int64

Number of rows: 73109

======================================================================
FILE: staff_assignment.csv

Number of unique values:
assignment_id    207
employee_id      207
ward_id           27
shift              3
dtype: int64

Number of rows: 207

======================================================================
FILE: ward.csv

Number of unique values:
ward_id          27
ward_name        27
ward_type         4
total_beds        3
department_id     6
dtype: int64

Number of rows: 27

In [5]:
import pandas as pd


patient = pd.read_csv("patient.csv")
admission = pd.read_csv("admission.csv")
department = pd.read_csv("department.csv")
ward = pd.read_csv("ward.csv")
bed = pd.read_csv("bed.csv")
disease = pd.read_csv("disease.csv")

print("Admission → Patient:",
      admission["patient_id"].isin(patient["patient_id"]).sum(),
      "/", len(admission))

print("Admission → Department:",
      admission["department_id"].isin(department["department_id"]).sum(),
      "/", len(admission))

print("Admission → Ward:",
      admission["ward_id"].isin(ward["ward_id"]).sum(),
      "/", len(admission))

print("Admission → Bed:",
      admission["bed_id"].isin(bed["bed_id"]).sum(),
      "/", len(admission))

print("Admission → Disease:",
      admission["disease_id"].isin(disease["disease_id"]).sum(),
      "/", len(admission))

Admission → Patient: 45000 / 45000
Admission → Department: 45000 / 45000
Admission → Ward: 45000 / 45000
Admission → Bed: 45000 / 45000
Admission → Disease: 45000 / 45000

In [7]:
import pandas as pd

# Load tables
billing = pd.read_csv("billing.csv")
billing_detail = pd.read_csv("billing_detail.csv")
doctor = pd.read_csv("doctor.csv")
employee = pd.read_csv("employee.csv")
drug = pd.read_csv("drug.csv")
drug_inventory = pd.read_csv("drug_inventory.csv")
drug_manufacturer = pd.read_csv("drug_manufacturer.csv")
diagnostic_test = pd.read_csv("diagnostic_test.csv")
patient_diagnostic = pd.read_csv("patient_diagnostic.csv")
patient_insurance = pd.read_csv("patient_insurance.csv")
insurance_provider = pd.read_csv("insurance_provider.csv")
prescription = pd.read_csv("prescription.csv")
staff_assignment = pd.read_csv("staff_assignment.csv")
ward = pd.read_csv("ward.csv")


# 1. Billing → Admission
print("Billing → Admission:",
      billing["admission_id"].isin(admission["admission_id"]).sum(),
      "/", len(billing))

# 2. Billing Detail → Billing
print("Billing Detail → Billing:",
      billing_detail["bill_id"].isin(billing["bill_id"]).sum(),
      "/", len(billing_detail))

# 3. Doctor → Employee
print("Doctor → Employee:",
      doctor["employee_id"].isin(employee["employee_id"]).sum(),
      "/", len(doctor))

# 4. Drug → Drug Manufacturer
print("Drug → Manufacturer:",
      drug["manufacturer_id"].isin(
          drug_manufacturer["manufacturer_id"]
      ).sum(),
      "/", len(drug))

# 5. Drug Inventory → Drug
print("Drug Inventory → Drug:",
      drug_inventory["drug_id"].isin(
          drug["drug_id"]
      ).sum(),
      "/", len(drug_inventory))

# 6. Patient Diagnostic → Admission
print("Patient Diagnostic → Admission:",
      patient_diagnostic["admission_id"].isin(
          admission["admission_id"]
      ).sum(),
      "/", len(patient_diagnostic))

# 7. Patient Diagnostic → Diagnostic Test
print("Patient Diagnostic → Test:",
      patient_diagnostic["test_id"].isin(
          diagnostic_test["test_id"]
      ).sum(),
      "/", len(patient_diagnostic))

# 8. Patient Diagnostic → Doctor
print("Patient Diagnostic → Doctor:",
      patient_diagnostic["doctor_id"].isin(
          doctor["doctor_id"]
      ).sum(),
      "/", len(patient_diagnostic))

# 9. Patient Insurance → Patient
print("Patient Insurance → Patient:",
      patient_insurance["patient_id"].isin(
          patient["patient_id"]
      ).sum(),
      "/", len(patient_insurance))

# 10. Patient Insurance → Insurance Provider
print("Patient Insurance → Insurance Provider:",
      patient_insurance["insurance_provider_id"].isin(
          insurance_provider["insurance_provider_id"]
      ).sum(),
      "/", len(patient_insurance))

# 11. Prescription → Admission
print("Prescription → Admission:",
      prescription["admission_id"].isin(
          admission["admission_id"]
      ).sum(),
      "/", len(prescription))

# 12. Prescription → Drug
print("Prescription → Drug:",
      prescription["drug_id"].isin(
          drug["drug_id"]
      ).sum(),
      "/", len(prescription))

# 13. Staff Assignment → Employee
print("Staff Assignment → Employee:",
      staff_assignment["employee_id"].isin(
          employee["employee_id"]
      ).sum(),
      "/", len(staff_assignment))

# 14. Staff Assignment → Ward
print("Staff Assignment → Ward:",
      staff_assignment["ward_id"].isin(
          ward["ward_id"]
      ).sum(),
      "/", len(staff_assignment))

# 15. Ward → Department
print("Ward → Department:",
      ward["department_id"].isin(
          department["department_id"]
      ).sum(),
      "/", len(ward))

Billing → Admission: 45000 / 45000
Billing Detail → Billing: 112402 / 112402
Doctor → Employee: 98 / 98
Drug → Manufacturer: 250 / 250
Drug Inventory → Drug: 250 / 250
Patient Diagnostic → Admission: 63269 / 63269
Patient Diagnostic → Test: 63269 / 63269
Patient Diagnostic → Doctor: 63269 / 63269
Patient Insurance → Patient: 21617 / 21617
Patient Insurance → Insurance Provider: 21617 / 21617
Prescription → Admission: 73109 / 73109
Prescription → Drug: 73109 / 73109
Staff Assignment → Employee: 207 / 207
Staff Assignment → Ward: 207 / 207
Ward → Department: 27 / 27

In [8]:
import pandas as pd
import os

for file in hmis_files:

    df = pd.read_csv(file)

    print("\n" + "=" * 70)
    print("FILE:", file)

    # Missing values
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if len(missing) == 0:
        print("Missing Values: NONE")
    else:
        print("Missing Values:")
        print(missing)

    # Duplicate rows
    duplicates = df.duplicated().sum()

    print("Duplicate Rows:", duplicates)

======================================================================
FILE: admission.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: bed.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: billing.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: billing_detail.csv
Missing Values:
reference_id    67402
dtype: int64
Duplicate Rows: 0

======================================================================
FILE: department.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: diagnostic_test.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: disease.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: doctor.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: drug.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: drug_inventory.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: drug_manufacturer.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: employee.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: insurance_provider.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: patient.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: patient_diagnostic.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: patient_insurance.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: prescription.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: staff_assignment.csv
Missing Values: NONE
Duplicate Rows: 0

======================================================================
FILE: ward.csv
Missing Values: NONE
Duplicate Rows: 0

In [9]:
billing_detail = pd.read_csv("billing_detail.csv")

print(billing_detail.head(10))
print("\nColumns:")
print(billing_detail.columns.tolist())

print("\nReference ID missing:")
print(billing_detail["reference_id"].isnull().sum())

print("\nReference ID available:")
print(billing_detail["reference_id"].notnull().sum())

   billing_detail_id charge_type  reference_id  amount  bill_id
0                  1        Room          76.0    4884        1
1                  2        Drug           NaN    1844        1
2                  3        Room         302.0   70010        2
3                  4        Test           NaN     562        2
4                  5        Drug           NaN    2489        2
5                  6   Procedure           NaN    6205        2
6                  7        Room          11.0   40230        3
7                  8        Test           NaN    1726        3
8                  9        Drug           NaN     615        3
9                 10        Room         128.0   10445        4

Columns:
['billing_detail_id', 'charge_type', 'reference_id', 'amount', 'bill_id']

Reference ID missing:
67402

Reference ID available:
45000

In [10]:
print(
    billing_detail.groupby("charge_type")["reference_id"]
    .agg(
        total_records="size",
        missing_values=lambda x: x.isna().sum(),
        available_values=lambda x: x.notna().sum()
    )
)

             total_records  missing_values  available_values
charge_type
Drug                 31344           31344                 0
Procedure            13575           13575                 0
Room                 45000               0             45000
Test                 22483           22483                 0

In [11]:
for file in hmis_files:

    df = pd.read_csv(file)

    print("\n" + "=" * 70)
    print("FILE:", file)

    print("\nData Types:")
    print(df.dtypes)

    print("\nNumeric Columns Summary:")
    print(df.describe())

======================================================================
FILE: admission.csv

Data Types:
admission_id        int64
admission_date        str
discharge_date        str
admission_type        str
admission_status      str
patient_id          int64
department_id       int64
ward_id             int64
bed_id              int64
disease_id          int64
dtype: object

Numeric Columns Summary:
       admission_id    patient_id  department_id      ward_id       bed_id  \
count  45000.000000  45000.000000   45000.000000  45000.00000  45000.00000
mean   22500.500000  14912.959911       3.159044     13.52620    194.59480
std    12990.525394   8659.657220       1.564617      7.34845    113.66573
min        1.000000      1.000000       1.000000      1.00000      3.00000
25%    11250.750000   7390.750000       2.000000      7.00000     98.00000
50%    22500.500000  14878.500000       3.000000     13.00000    195.00000
75%    33750.250000  22411.000000       4.000000     20.00000    289.00000
max    45000.000000  30000.000000       6.000000     27.00000    414.00000

         disease_id
count  45000.000000
mean      10.459844
std        5.771013
min        1.000000
25%        5.000000
50%       10.000000
75%       15.000000
max       20.000000

======================================================================
FILE: bed.csv

Data Types:
bed_id        int64
bed_number      str
bed_status      str
ward_id       int64
dtype: object

Numeric Columns Summary:
           bed_id     ward_id
count  415.000000  415.000000
mean   208.000000   14.397590
std    119.944432    7.730265
min      1.000000    1.000000
25%    104.500000    8.000000
50%    208.000000   14.000000
75%    311.500000   21.000000
max    415.000000   27.000000

======================================================================
FILE: billing.csv

Data Types:
bill_id                       int64
bill_date                       str
total_amount                  int64
insurance_covered_amount    float64
patient_payable_amount      float64
payment_status                  str
payment_mode                    str
admission_id                  int64
dtype: object

Numeric Columns Summary:
            bill_id  total_amount  insurance_covered_amount  \
count  45000.000000  45000.000000              45000.000000
mean   22500.500000  37427.691311              21708.463711
std    12990.525394  20898.321091              18289.872062
min        1.000000   5001.000000                  0.000000
25%    11250.750000  21231.000000               6580.000000
50%    22500.500000  34623.500000              19210.500000
75%    33750.250000  48039.250000              32752.325000
max    45000.000000  89990.000000              80956.800000

       patient_payable_amount  admission_id
count            45000.000000  45000.000000
mean             15719.227600  22500.500000
std              16216.113367  12990.525394
min                500.300000      1.000000
25%               4743.850000  11250.750000
50%               9712.150000  22500.500000
75%              20746.750000  33750.250000
max              89921.000000  45000.000000

======================================================================
FILE: billing_detail.csv

Data Types:
billing_detail_id      int64
charge_type              str
reference_id         float64
amount                 int64
bill_id                int64
dtype: object

Numeric Columns Summary:
       billing_detail_id  reference_id         amount        bill_id
count      112402.000000   45000.00000  112402.000000  112402.000000
mean        56201.500000     194.59480   13157.063629   22503.190388
std         32447.806816     113.66573   16771.971534   12991.639176
min             1.000000       3.00000     200.000000       1.000000
25%         28101.250000      98.00000    2020.000000   11270.000000
50%         56201.500000     195.00000    4879.000000   22479.500000
75%         84301.750000     289.00000   19000.750000   33752.000000
max        112402.000000     414.00000  120000.000000   45000.000000

======================================================================
FILE: department.csv

Data Types:
department_id      int64
department_name      str
department_type      str
floor_number       int64
status               str
dtype: object

Numeric Columns Summary:
       department_id  floor_number
count      11.000000     11.000000
mean        6.000000      1.272727
std         3.316625      1.348400
min         1.000000      0.000000
25%         3.500000      0.000000
50%         6.000000      1.000000
75%         8.500000      2.000000
max        11.000000      4.000000

======================================================================
FILE: diagnostic_test.csv

Data Types:
test_id          int64
test_name          str
test_category      str
standard_cost    int64
department_id    int64
dtype: object

Numeric Columns Summary:
        test_id  standard_cost  department_id
count  9.000000       9.000000       9.000000
mean   5.000000    2952.555556       7.555556
std    2.738613    1429.076460       0.527046
min    1.000000     924.000000       7.000000
25%    3.000000    1665.000000       7.000000
50%    5.000000    2796.000000       8.000000
75%    7.000000    4257.000000       8.000000
max    9.000000    4852.000000       8.000000

======================================================================
FILE: disease.csv

Data Types:
disease_id          int64
disease_name          str
disease_category      str
dtype: object

Numeric Columns Summary:
       disease_id
count    20.00000
mean     10.50000
std       5.91608
min       1.00000
25%       5.75000
50%      10.50000
75%      15.25000
max      20.00000

======================================================================
FILE: doctor.csv

Data Types:
doctor_id           int64
employee_id         int64
specialization        str
qualification         str
experience_years    int64
dtype: object

Numeric Columns Summary:
       doctor_id  employee_id  experience_years
count  98.000000    98.000000         98.000000
mean   49.500000   252.071429         17.428571
std    28.434134   147.102899         10.404202
min     1.000000     3.000000          1.000000
25%    25.250000   132.250000          8.000000
50%    49.500000   232.500000         17.500000
75%    73.750000   380.500000         26.000000
max    98.000000   498.000000         35.000000

======================================================================
FILE: drug.csv

Data Types:
drug_id            int64
drug_name            str
brand_name           str
drug_category        str
unit_cost          int64
manufacturer_id    int64
dtype: object

Numeric Columns Summary:
          drug_id   unit_cost  manufacturer_id
count  250.000000  250.000000       250.000000
mean   125.500000  247.492000       160.484000
std     72.312977  142.546948        84.526235
min      1.000000   10.000000         2.000000
25%     63.250000  121.000000        94.000000
50%    125.500000  239.500000       172.500000
75%    187.750000  382.750000       231.750000
max    250.000000  498.000000       300.000000

======================================================================
FILE: drug_inventory.csv

Data Types:
inventory_id         int64
current_stock        int64
reorder_level        int64
inventory_status       str
last_restock_date      str
drug_id              int64
dtype: object

Numeric Columns Summary:
       inventory_id  current_stock  reorder_level     drug_id
count    250.000000     250.000000     250.000000  250.000000
mean     125.500000     523.512000     204.540000  125.500000
std       72.312977     279.049408      58.099489   72.312977
min        1.000000      53.000000     102.000000    1.000000
25%       63.250000     292.250000     151.000000   63.250000
50%      125.500000     550.500000     211.500000  125.500000
75%      187.750000     755.750000     252.000000  187.750000
max      250.000000     996.000000     299.000000  250.000000

======================================================================
FILE: drug_manufacturer.csv

Data Types:
manufacturer_id         int64
manufacturer_name         str
country                   str
reliability_rating    float64
contract_status           str
dtype: object

Numeric Columns Summary:
       manufacturer_id  reliability_rating
count       300.000000          300.000000
mean        150.500000            4.195667
std          86.746758            0.415681
min           1.000000            3.500000
25%          75.750000            3.800000
50%         150.500000            4.200000
75%         225.250000            4.500000
max         300.000000            4.900000

======================================================================
FILE: employee.csv

Data Types:
employee_id        int64
employee_name        str
gender               str
role                 str
employment_type      str
date_of_joining      str
department_id      int64
dtype: object

Numeric Columns Summary:
       employee_id  department_id
count   500.000000     500.000000
mean    250.500000       5.940000
std     144.481833       3.209517
min       1.000000       1.000000
25%     125.750000       3.000000
50%     250.500000       6.000000
75%     375.250000       9.000000
max     500.000000      11.000000

======================================================================
FILE: insurance_provider.csv

Data Types:
insurance_provider_id    int64
provider_name              str
provider_type              str
contact_details          int64
coverage_limit           int64
dtype: object

Numeric Columns Summary:
       insurance_provider_id  contact_details  coverage_limit
count               50.00000     5.000000e+01    5.000000e+01
mean                25.50000     2.050368e+11    8.280000e+05
std                 14.57738     3.808284e+11    5.828466e+05
min                  1.00000     3.124159e+08    2.000000e+05
25%                 13.25000     3.150241e+09    3.000000e+05
50%                 25.50000     6.485462e+09    6.250000e+05
75%                 37.75000     9.563986e+09    1.375000e+06
max                 50.00000     9.194075e+11    2.000000e+06

======================================================================
FILE: patient.csv

Data Types:
patient_id        int64
gender              str
date_of_birth       str
blood_group         str
city                str
contact_number      str
dtype: object

Numeric Columns Summary:
         patient_id
count  30000.000000
mean   15000.500000
std     8660.398374
min        1.000000
25%     7500.750000
50%    15000.500000
75%    22500.250000
max    30000.000000

======================================================================
FILE: patient_diagnostic.csv

Data Types:
patient_diagnostic_id    int64
test_date                  str
result_status              str
admission_id             int64
test_id                  int64
doctor_id                int64
dtype: object

Numeric Columns Summary:
       patient_diagnostic_id  admission_id       test_id     doctor_id
count           63269.000000  63269.000000  63269.000000  63269.000000
mean            31635.000000  22444.920150      5.000000     25.495187
std             18264.331428  13022.187557      2.584661     14.455849
min                 1.000000      1.000000      1.000000      1.000000
25%             15818.000000  11094.000000      3.000000     13.000000
50%             31635.000000  22450.000000      5.000000     26.000000
75%             47452.000000  33746.000000      7.000000     38.000000
max             63269.000000  45000.000000      9.000000     50.000000

======================================================================
FILE: patient_insurance.csv

Data Types:
patient_insurance_id     int64
policy_number              str
coverage_percentage      int64
policy_start_date          str
policy_end_date            str
patient_id               int64
insurance_provider_id    int64
dtype: object

Numeric Columns Summary:
       patient_insurance_id  coverage_percentage    patient_id  \
count           21617.00000         21617.000000  21617.000000
mean            10809.00000            70.069852  14953.214045
std              6240.43472            14.160107   8640.645878
min                 1.00000            50.000000      1.000000
25%              5405.00000            60.000000   7535.000000
50%             10809.00000            70.000000  14920.000000
75%             16213.00000            80.000000  22431.000000
max             21617.00000            90.000000  30000.000000

       insurance_provider_id
count           21617.000000
mean               25.434935
std                14.383106
min                 1.000000
25%                13.000000
50%                25.000000
75%                38.000000
max                50.000000

======================================================================
FILE: prescription.csv

Data Types:
prescription_id    int64
dosage               str
frequency            str
duration_days      int64
admission_id       int64
drug_id            int64
dtype: object

Numeric Columns Summary:
       prescription_id  duration_days  admission_id       drug_id
count     73109.000000   73109.000000  73109.000000  73109.000000
mean      36555.000000       8.506545  22471.248437    125.469682
std       21104.894752       3.459250  12977.848698     72.268495
min           1.000000       3.000000      1.000000      1.000000
25%       18278.000000       6.000000  11173.000000     63.000000
50%       36555.000000       9.000000  22472.000000    125.000000
75%       54832.000000      12.000000  33672.000000    188.000000
max       73109.000000      14.000000  45000.000000    250.000000

======================================================================
FILE: staff_assignment.csv

Data Types:
assignment_id    int64
employee_id      int64
ward_id          int64
shift              str
dtype: object

Numeric Columns Summary:
       assignment_id  employee_id     ward_id
count     207.000000   207.000000  207.000000
mean      104.000000   250.492754   14.048309
std        59.899917   142.548233    7.768969
min         1.000000     2.000000    1.000000
25%        52.500000   129.500000    7.500000
50%       104.000000   245.000000   14.000000
75%       155.500000   385.500000   21.500000
max       207.000000   500.000000   27.000000

======================================================================
FILE: ward.csv

Data Types:
ward_id          int64
ward_name          str
ward_type          str
total_beds       int64
department_id    int64
dtype: object

Numeric Columns Summary:
         ward_id  total_beds  department_id
count  27.000000   27.000000      27.000000
mean   14.000000   15.370370       3.296296
std     7.937254    4.143096       1.705530
min     1.000000   10.000000       1.000000
25%     7.500000   10.000000       2.000000
50%    14.000000   15.000000       3.000000
75%    20.500000   20.000000       4.500000
max    27.000000   20.000000       6.000000

In [12]:
for file in hmis_files:
    df = pd.read_csv(file)
    
    print("\n" + "=" * 60)
    print("FILE:", file)
    print("COLUMNS:", df.columns.tolist())

============================================================
FILE: admission.csv
COLUMNS: ['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id']

============================================================
FILE: bed.csv
COLUMNS: ['bed_id', 'bed_number', 'bed_status', 'ward_id']

============================================================
FILE: billing.csv
COLUMNS: ['bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode', 'admission_id']

============================================================
FILE: billing_detail.csv
COLUMNS: ['billing_detail_id', 'charge_type', 'reference_id', 'amount', 'bill_id']

============================================================
FILE: department.csv
COLUMNS: ['department_id', 'department_name', 'department_type', 'floor_number', 'status']

============================================================
FILE: diagnostic_test.csv
COLUMNS: ['test_id', 'test_name', 'test_category', 'standard_cost', 'department_id']

============================================================
FILE: disease.csv
COLUMNS: ['disease_id', 'disease_name', 'disease_category']

============================================================
FILE: doctor.csv
COLUMNS: ['doctor_id', 'employee_id', 'specialization', 'qualification', 'experience_years']

============================================================
FILE: drug.csv
COLUMNS: ['drug_id', 'drug_name', 'brand_name', 'drug_category', 'unit_cost', 'manufacturer_id']

============================================================
FILE: drug_inventory.csv
COLUMNS: ['inventory_id', 'current_stock', 'reorder_level', 'inventory_status', 'last_restock_date', 'drug_id']

============================================================
FILE: drug_manufacturer.csv
COLUMNS: ['manufacturer_id', 'manufacturer_name', 'country', 'reliability_rating', 'contract_status']

============================================================
FILE: employee.csv
COLUMNS: ['employee_id', 'employee_name', 'gender', 'role', 'employment_type', 'date_of_joining', 'department_id']

============================================================
FILE: insurance_provider.csv
COLUMNS: ['insurance_provider_id', 'provider_name', 'provider_type', 'contact_details', 'coverage_limit']

============================================================
FILE: patient.csv
COLUMNS: ['patient_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number']

============================================================
FILE: patient_diagnostic.csv
COLUMNS: ['patient_diagnostic_id', 'test_date', 'result_status', 'admission_id', 'test_id', 'doctor_id']

============================================================
FILE: patient_insurance.csv
COLUMNS: ['patient_insurance_id', 'policy_number', 'coverage_percentage', 'policy_start_date', 'policy_end_date', 'patient_id', 'insurance_provider_id']

============================================================
FILE: prescription.csv
COLUMNS: ['prescription_id', 'dosage', 'frequency', 'duration_days', 'admission_id', 'drug_id']

============================================================
FILE: staff_assignment.csv
COLUMNS: ['assignment_id', 'employee_id', 'ward_id', 'shift']

============================================================
FILE: ward.csv
COLUMNS: ['ward_id', 'ward_name', 'ward_type', 'total_beds', 'department_id']

In [13]:
# ==============================
# HOSPITAL OVERVIEW TABLE
# ==============================

import pandas as pd

# Load required datasets
patient = pd.read_csv("patient.csv")
admission = pd.read_csv("admission.csv")
billing = pd.read_csv("billing.csv")
bed = pd.read_csv("bed.csv")
department = pd.read_csv("department.csv")
doctor = pd.read_csv("doctor.csv")
employee = pd.read_csv("employee.csv")

# Calculate Average Length of Stay
admission["admission_date"] = pd.to_datetime(admission["admission_date"])
admission["discharge_date"] = pd.to_datetime(admission["discharge_date"])

admission["length_of_stay"] = (
    admission["discharge_date"] - admission["admission_date"]
).dt.days

# Create Hospital Overview
hospital_overview = pd.DataFrame({
    "Metric": [
        "Total Patients",
        "Total Admissions",
        "Total Bills",
        "Total Beds",
        "Total Departments",
        "Total Doctors",
        "Total Employees",
        "Total Revenue",
        "Average Length of Stay"
    ],

    "Value": [
        len(patient),
        len(admission),
        len(billing),
        len(bed),
        len(department),
        len(doctor),
        len(employee),
        billing["total_amount"].sum(),
        admission["length_of_stay"].mean()
    ]
})

hospital_overview

                   Metric         Value
0          Total Patients  3.000000e+04
1        Total Admissions  4.500000e+04
2             Total Bills  4.500000e+04
3              Total Beds  4.150000e+02
4       Total Departments  1.100000e+01
5           Total Doctors  9.800000e+01
6         Total Employees  5.000000e+02
7           Total Revenue  1.684246e+09
8  Average Length of Stay  5.155000e+00

In [14]:
# ==========================================
# STEP 3 - PATIENT FLOW TABLE
# ==========================================

# Admission dates ko datetime me convert karna
admission["admission_date"] = pd.to_datetime(admission["admission_date"])
admission["discharge_date"] = pd.to_datetime(admission["discharge_date"])

# Length of Stay calculate karna
admission["length_of_stay"] = (
    admission["discharge_date"] - admission["admission_date"]
).dt.days

# Patient Flow table
patient_flow = admission[
    [
        "admission_id",
        "patient_id",
        "admission_date",
        "discharge_date",
        "admission_type",
        "admission_status",
        "department_id",
        "ward_id",
        "bed_id",
        "disease_id",
        "length_of_stay"
    ]
].copy()

# First 10 records
patient_flow.head(10)

,admission_id,patient_id,admission_date,discharge_date,admission_type,admission_status,department_id,ward_id,bed_id,disease_id,length_of_stay
0,1,166,2020-02-25,2020-02-27,Emergency,Discharged,2,6,76,10,2
1,2,8622,2022-02-22,2022-03-04,Elective,Discharged,5,21,302,11,10
2,3,23976,2021-02-03,2021-02-09,Elective,Discharged,1,2,11,9,6
3,4,16635,2021-12-31,2022-01-05,Elective,Discharged,2,10,128,1,5
4,5,10654,2022-07-02,2022-07-07,Elective,Discharged,3,11,157,7,5
5,6,21044,2021-08-01,2021-08-08,Elective,Discharged,3,11,143,14,7
6,7,10798,2020-06-30,2020-07-01,Emergency,Discharged,2,6,79,19,1
7,8,15425,2025-07-15,2025-07-18,Emergency,Discharged,4,19,276,18,3
8,9,13814,2024-11-25,2024-11-28,Emergency,Discharged,1,4,55,16,3
9,10,1654,2020-05-26,2020-05-30,Elective,Discharged,1,2,11,2,4

In [15]:
# ==========================================
# STEP 4 - DEPARTMENT ANALYTICS TABLE
# ==========================================

# Department-wise admission analysis
department_analytics = admission.groupby("department_id").agg(
    total_admissions=("admission_id", "count"),
    average_length_of_stay=("length_of_stay", "mean")
).reset_index()

# Department-wise revenue
department_revenue = billing.merge(
    admission[["admission_id", "department_id"]],
    on="admission_id",
    how="left"
)

department_revenue = department_revenue.groupby("department_id").agg(
    total_revenue=("total_amount", "sum")
).reset_index()

# Combine admission + revenue data
department_analytics = department_analytics.merge(
    department_revenue,
    on="department_id",
    how="left"
)

# Add department names
department_analytics = department_analytics.merge(
    department[["department_id", "department_name"]],
    on="department_id",
    how="left"
)

# Arrange columns
department_analytics = department_analytics[
    [
        "department_id",
        "department_name",
        "total_admissions",
        "average_length_of_stay",
        "total_revenue"
    ]
]

# Round average stay
department_analytics["average_length_of_stay"] = (
    department_analytics["average_length_of_stay"].round(2)
)

department_analytics

,department_id,department_name,total_admissions,average_length_of_stay,total_revenue
0,1,Emergency,8777,4.69,329738229
1,2,Internal Medicine,7695,4.66,289566059
2,3,Surgery,10126,4.67,377216234
3,4,Pediatrics,8438,4.69,315714822
4,5,Orthopedics,5924,4.68,222585716
5,6,ICU,4040,9.98,149425049

In [16]:
# ==========================================
# STEP 5 - RESOURCE UTILIZATION TABLE
# ==========================================

# Ward-wise occupied bed days
ward_usage = admission.groupby("ward_id").agg(
    total_admissions=("admission_id", "count"),
    occupied_bed_days=("length_of_stay", "sum")
).reset_index()

# Add ward information
resource_utilization = ward_usage.merge(
    ward[["ward_id", "ward_name", "ward_type", "total_beds", "department_id"]],
    on="ward_id",
    how="left"
)

# Calculate total number of days in the dataset period
start_date = admission["admission_date"].min()
end_date = admission["discharge_date"].max()

period_days = (end_date - start_date).days + 1

# Available bed days
resource_utilization["available_bed_days"] = (
    resource_utilization["total_beds"] * period_days
)

# Bed utilization percentage
resource_utilization["bed_utilization_percent"] = (
    resource_utilization["occupied_bed_days"]
    / resource_utilization["available_bed_days"]
) * 100

# Round percentage
resource_utilization["bed_utilization_percent"] = (
    resource_utilization["bed_utilization_percent"].round(2)
)

# Final columns
resource_utilization = resource_utilization[
    [
        "ward_id",
        "ward_name",
        "ward_type",
        "department_id",
        "total_beds",
        "total_admissions",
        "occupied_bed_days",
        "available_bed_days",
        "bed_utilization_percent"
    ]
]

resource_utilization

,ward_id,ward_name,ward_type,department_id,total_beds,total_admissions,occupied_bed_days,available_bed_days,bed_utilization_percent
0,1,Emergency Ward 1,General,1,10,1265,5985,22040,27.16
1,2,Emergency Ward 2,Private,1,15,1867,8808,33060,26.64
2,3,Emergency Ward 3,General,1,10,1206,5515,22040,25.02
3,4,Emergency Ward 4,General,1,20,2227,10422,44080,23.64
4,5,Emergency Ward 5,General,1,20,2212,10456,44080,23.72
5,6,Internal Medicine Ward 1,Private,2,10,1225,5677,22040,25.76
6,7,Internal Medicine Ward 2,Private,2,15,1873,8636,33060,26.12
7,8,Internal Medicine Ward 3,General,2,10,1220,5847,22040,26.53
8,9,Internal Medicine Ward 4,General,2,10,1209,5673,22040,25.74
9,10,Internal Medicine Ward 5,General,2,20,2168,9996,44080,22.68
10,11,Surgery Ward 1,General,3,20,2140,9942,44080,22.55
11,12,Surgery Ward 2,General,3,20,2157,9936,44080,22.54
12,13,Surgery Ward 3,Private,3,20,2147,10146,44080,23.02
13,14,Surgery Ward 4,Private,3,15,1895,9053,33060,27.38
14,15,Surgery Ward 5,General,3,15,1787,8260,33060,24.98
15,16,Pediatrics Ward 1,Semi-Private,4,10,1220,5771,22040,26.18
16,17,Pediatrics Ward 2,General,4,20,2228,10275,44080,23.31
17,18,Pediatrics Ward 3,Semi-Private,4,15,1881,8905,33060,26.94
18,19,Pediatrics Ward 4,Semi-Private,4,10,1266,5944,22040,26.97
19,20,Pediatrics Ward 5,General,4,15,1843,8694,33060,26.30
20,21,Orthopedics Ward 1,General,5,15,1868,8654,33060,26.18
21,22,Orthopedics Ward 2,General,5,15,1849,8510,33060,25.74
22,23,Orthopedics Ward 3,Semi-Private,5,20,2207,10548,44080,23.93
23,24,ICU Ward 1,ICU,6,10,614,6166,22040,27.98
24,25,ICU Ward 2,ICU,6,20,1246,12420,44080,28.18
25,26,ICU Ward 3,ICU,6,15,939,9322,33060,28.20
26,27,ICU Ward 4,ICU,6,20,1241,12414,44080,28.16

In [17]:
# ==========================================
# STEP 6 - FINAL VALIDATION
# ==========================================

print("========== FINAL VALIDATION ==========\n")

# 1. Hospital Overview
print("1. HOSPITAL OVERVIEW")
print("Total Patients:", len(patient))
print("Total Admissions:", len(admission))
print("Total Bills:", len(billing))
print("Total Beds:", len(bed))
print("Total Departments:", len(department))
print("Total Doctors:", len(doctor))
print("Total Employees:", len(employee))


# 2. Patient Flow
print("\n2. PATIENT FLOW")
print("Records:", len(patient_flow))
print("Missing Values:", patient_flow.isnull().sum().sum())
print("Duplicate Rows:", patient_flow.duplicated().sum())


# 3. Department Analytics
print("\n3. DEPARTMENT ANALYTICS")
print("Records:", len(department_analytics))
print("Missing Values:", department_analytics.isnull().sum().sum())
print("Duplicate Rows:", department_analytics.duplicated().sum())


# 4. Resource Utilization
print("\n4. RESOURCE UTILIZATION")
print("Records:", len(resource_utilization))
print("Missing Values:", resource_utilization.isnull().sum().sum())
print("Duplicate Rows:", resource_utilization.duplicated().sum())


# 5. Important consistency checks
print("\n========== CONSISTENCY CHECKS ==========")

print(
    "Patient Flow admissions:",
    len(patient_flow),
    "/ Original admissions:",
    len(admission)
)

print(
    "Department Analytics departments:",
    len(department_analytics),
    "/ Original departments:",
    len(department)
)

print(
    "Resource Utilization wards:",
    len(resource_utilization),
    "/ Original wards:",
    len(ward)
)

# Check invalid utilization values
print(
    "Invalid Bed Utilization values:",
    (
        (resource_utilization["bed_utilization_percent"] < 0) |
        (resource_utilization["bed_utilization_percent"] > 100)
    ).sum()
)

========== FINAL VALIDATION ==========

1. HOSPITAL OVERVIEW
Total Patients: 30000
Total Admissions: 45000
Total Bills: 45000
Total Beds: 415
Total Departments: 11
Total Doctors: 98
Total Employees: 500

2. PATIENT FLOW
Records: 45000
Missing Values: 0
Duplicate Rows: 0

3. DEPARTMENT ANALYTICS
Records: 6
Missing Values: 0
Duplicate Rows: 0

4. RESOURCE UTILIZATION
Records: 27
Missing Values: 0
Duplicate Rows: 0

========== CONSISTENCY CHECKS ==========
Patient Flow admissions: 45000 / Original admissions: 45000
Department Analytics departments: 6 / Original departments: 11
Resource Utilization wards: 27 / Original wards: 27
Invalid Bed Utilization values: 0

In [18]:
print("===== PATIENT FLOW INSIGHTS =====")

print("Total Admissions:", len(patient_flow))

print("Average Length of Stay:",
      round(patient_flow["length_of_stay"].mean(), 2))

print("Maximum Length of Stay:",
      patient_flow["length_of_stay"].max())

print("Minimum Length of Stay:",
      patient_flow["length_of_stay"].min())

print("\nAdmissions by Type:")
print(patient_flow["admission_type"].value_counts())

print("\nAdmissions by Department:")
print(patient_flow["department_id"].value_counts())

===== PATIENT FLOW INSIGHTS =====
Total Admissions: 45000
Average Length of Stay: 5.16
Maximum Length of Stay: 15
Minimum Length of Stay: 1

Admissions by Type:
admission_type
Elective     26923
Emergency    18077
Name: count, dtype: int64

Admissions by Department:
department_id
3    10126
1     8777
4     8438
2     7695
5     5924
6     4040
Name: count, dtype: int64

In [23]:
print("===== DEPARTMENT INSIGHTS =====")

print("Total Departments:", len(department_analytics))

print("\nHighest Admissions Department:")
print(
    department_analytics.loc[
        department_analytics["total_admissions"].idxmax()
    ]
)

print("\nLowest Admissions Department:")
print(
    department_analytics.loc[
        department_analytics["total_admissions"].idxmin()
    ]
)

print("\nHighest Revenue Department:")
print(
    department_analytics.loc[
        department_analytics["total_revenue"].idxmax()
    ]
)

print("\nHighest Average Length of Stay:")
print(
    department_analytics.loc[
        department_analytics["average_length_of_stay"].idxmax()
    ]
)

===== DEPARTMENT INSIGHTS =====
Total Departments: 6

Highest Admissions Department:
department_id                     3
department_name             Surgery
total_admissions              10126
average_length_of_stay         4.67
total_revenue             377216234
Name: 2, dtype: object

Lowest Admissions Department:
department_id                     6
department_name                 ICU
total_admissions               4040
average_length_of_stay         9.98
total_revenue             149425049
Name: 5, dtype: object

Highest Revenue Department:
department_id                     3
department_name             Surgery
total_admissions              10126
average_length_of_stay         4.67
total_revenue             377216234
Name: 2, dtype: object

Highest Average Length of Stay:
department_id                     6
department_name                 ICU
total_admissions               4040
average_length_of_stay         9.98
total_revenue             149425049
Name: 5, dtype: object

In [20]:
print([x for x in globals() if not x.startswith("_")])

['In', 'Out', 'get_ipython', 'exit', 'quit', 'open', 'json', 'sys', 'islice', 'collections', 'NamespaceMagics', 'pd', 'os', 'hmis_files', 'file', 'df', 'patient', 'admission', 'department', 'ward', 'bed', 'disease', 'billing', 'billing_detail', 'doctor', 'employee', 'drug', 'drug_inventory', 'drug_manufacturer', 'patient_diagnostic', 'patient_insurance', 'insurance_provider', 'prescription', 'staff_assignment', 'diagnostic_test', 'missing', 'duplicates', 'hospital_overview', 'patient_flow', 'department_analytics', 'department_revenue', 'ward_usage', 'resource_utilization', 'start_date', 'end_date', 'period_days']

In [22]:
department_analytics.head()

,department_id,department_name,total_admissions,average_length_of_stay,total_revenue
0,1,Emergency,8777,4.69,329738229
1,2,Internal Medicine,7695,4.66,289566059
2,3,Surgery,10126,4.67,377216234
3,4,Pediatrics,8438,4.69,315714822
4,5,Orthopedics,5924,4.68,222585716

In [24]:
print("===== RESOURCE UTILIZATION INSIGHTS =====")

print("Total Wards:", len(resource_utilization))

print("\nHighest Bed Utilization:")
print(
    resource_utilization.loc[
        resource_utilization["bed_utilization_percent"].idxmax()
    ]
)

print("\nLowest Bed Utilization:")
print(
    resource_utilization.loc[
        resource_utilization["bed_utilization_percent"].idxmin()
    ]
)

print("\nAverage Bed Utilization:",
      round(
          resource_utilization["bed_utilization_percent"].mean(),
          2
      ), "%")

===== RESOURCE UTILIZATION INSIGHTS =====
Total Wards: 27

Highest Bed Utilization:
ward_id                            26
ward_name                  ICU Ward 3
ward_type                         ICU
department_id                       6
total_beds                         15
total_admissions                  939
occupied_bed_days                9322
available_bed_days              33060
bed_utilization_percent          28.2
Name: 25, dtype: object

Lowest Bed Utilization:
ward_id                                12
ward_name                  Surgery Ward 2
ward_type                         General
department_id                           3
total_beds                             20
total_admissions                     2157
occupied_bed_days                    9936
available_bed_days                  44080
bed_utilization_percent             22.54
Name: 11, dtype: object

Average Bed Utilization: 25.61 %

In [25]:
print("===== REVENUE & BILLING INSIGHTS =====")

print("Total Revenue:",
      billing["total_amount"].sum())

print("Average Bill Amount:",
      round(billing["total_amount"].mean(), 2))

print("Highest Bill Amount:",
      billing["total_amount"].max())

print("\nPayment Status:")
print(billing["payment_status"].value_counts())

print("\nPayment Mode:")
print(billing["payment_mode"].value_counts())

===== REVENUE & BILLING INSIGHTS =====
Total Revenue: 1684246109
Average Bill Amount: 37427.69
Highest Bill Amount: 89990

Payment Status:
payment_status
Pending    22670
Paid       22330
Name: count, dtype: int64

Payment Mode:
payment_mode
Insurance    35979
UPI           3049
Card          3017
Cash          2955
Name: count, dtype: int64

In [2]:
import pandas as pd

bed_management = pd.read_excel(
    "Bed management.csv.xlsx"
)

print("===== BED MANAGEMENT DATASET =====")

print("Number of Rows:", len(bed_management))
print("Number of Columns:", len(bed_management.columns))

print("\nColumns:")
print(bed_management.columns.tolist())

print("\nFirst 5 Records:")
display(bed_management.head())

===== BED MANAGEMENT DATASET =====
Number of Rows: 1000
Number of Columns: 21

Columns:
['Patient ID', 'Name', 'Age', 'Service', 'Arrival Date', 'Departure Date', 'Length of Stay (days)', 'Week', 'Admission Month', 'Patient Satisfaction Score', 'Available Beds (Wk)', 'Patients Requested (Wk)', 'Patients Admitted (Wk)', 'Patients Refused (Wk)', 'Avg Satisfaction (Wk)', 'Staff Morale (Wk)', 'Notable Event (Wk)', 'Dept Total Staff', 'Dept Doctor Count', 'Dept Nurse Count', 'Dept Nursing Assistant Count']

First 5 Records:

,Patient ID,Name,Age,Service,Arrival Date,Departure Date,Length of Stay (days),Week,Admission Month,Patient Satisfaction Score,...,Patients Requested (Wk),Patients Admitted (Wk),Patients Refused (Wk),Avg Satisfaction (Wk),Staff Morale (Wk),Notable Event (Wk),Dept Total Staff,Dept Doctor Count,Dept Nurse Count,Dept Nursing Assistant Count
0,PAT-09484753,Richard Rodriguez,24,surgery,2025-03-16,2025-03-22,6,11,3,61,...,48,48,0,82,80,none,22,4,13,5
1,PAT-f0644084,Shannon Walker,6,surgery,2025-12-13,2025-12-14,1,50,12,83,...,65,59,6,95,85,none,22,4,13,5
2,PAT-ac6162e4,Julia Torres,24,general_medicine,2025-06-29,2025-07-05,6,26,6,83,...,72,43,29,80,85,none,27,3,19,5
3,PAT-3dda2bb5,Crystal Johnson,32,emergency,2025-10-12,2025-10-23,11,41,10,81,...,92,27,65,69,88,none,29,5,19,5
4,PAT-08591375,Garrett Lin,25,ICU,2025-02-18,2025-02-25,7,8,2,76,...,10,10,0,76,98,none,32,6,18,8

In [29]:
# ==========================================
# STEP 2 - MISSING VALUES & DUPLICATES
# ==========================================

print("===== MISSING VALUES =====")

missing_values = bed_management.isnull().sum()

print(missing_values)


print("\n===== TOTAL MISSING VALUES =====")

print("Total Missing Values:",
      bed_management.isnull().sum().sum())


print("\n===== DUPLICATE RECORDS =====")

print("Total Duplicate Rows:",
      bed_management.duplicated().sum())

===== MISSING VALUES =====
Patient ID                      0
Name                            0
Age                             0
Service                         0
Arrival Date                    0
Departure Date                  0
Length of Stay (days)           0
Week                            0
Admission Month                 0
Patient Satisfaction Score      0
Available Beds (Wk)             0
Patients Requested (Wk)         0
Patients Admitted (Wk)          0
Patients Refused (Wk)           0
Avg Satisfaction (Wk)           0
Staff Morale (Wk)               0
Notable Event (Wk)              0
Dept Total Staff                0
Dept Doctor Count               0
Dept Nurse Count                0
Dept Nursing Assistant Count    0
dtype: int64

===== TOTAL MISSING VALUES =====
Total Missing Values: 0

===== DUPLICATE RECORDS =====
Total Duplicate Rows: 0

In [30]:
print("Total Duplicate Rows:", bed_management.duplicated().sum())

Total Duplicate Rows: 0

In [31]:
print("===== DATA TYPES =====")

print(bed_management.dtypes)

===== DATA TYPES =====
Patient ID                                 str
Name                                       str
Age                                      int64
Service                                    str
Arrival Date                    datetime64[us]
Departure Date                  datetime64[us]
Length of Stay (days)                    int64
Week                                     int64
Admission Month                          int64
Patient Satisfaction Score               int64
Available Beds (Wk)                      int64
Patients Requested (Wk)                  int64
Patients Admitted (Wk)                   int64
Patients Refused (Wk)                    int64
Avg Satisfaction (Wk)                    int64
Staff Morale (Wk)                        int64
Notable Event (Wk)                         str
Dept Total Staff                         int64
Dept Doctor Count                        int64
Dept Nurse Count                         int64
Dept Nursing Assistant Count             int64
dtype: object

In [3]:
# ==========================================
# BED MANAGEMENT - KPI ANALYSIS
# ==========================================

total_patients = bed_management["Patient ID"].nunique()

total_beds = bed_management["Available Beds (Wk)"].sum()

total_requested = bed_management["Patients Requested (Wk)"].sum()

total_admitted = bed_management["Patients Admitted (Wk)"].sum()

total_refused = bed_management["Patients Refused (Wk)"].sum()

admission_rate = (total_admitted / total_requested) * 100

refusal_rate = (total_refused / total_requested) * 100

avg_satisfaction = bed_management["Patient Satisfaction Score"].mean()

avg_staff_morale = bed_management["Staff Morale (Wk)"].mean()


# Display KPIs
print("===== BED MANAGEMENT KPIs =====")

print("Total Patients:", total_patients)
print("Total Beds Available:", total_beds)
print("Total Patients Requested:", total_requested)
print("Total Patients Admitted:", total_admitted)
print("Total Patients Refused:", total_refused)

print("Admission Rate:", round(admission_rate, 2), "%")
print("Refusal Rate:", round(refusal_rate, 2), "%")

print("Average Patient Satisfaction:",
      round(avg_satisfaction, 2))

print("Average Staff Morale:",
      round(avg_staff_morale, 2))

===== BED MANAGEMENT KPIs =====
Total Patients: 1000
Total Beds Available: 30498
Total Patients Requested: 63472
Total Patients Admitted: 28351
Total Patients Refused: 35121
Admission Rate: 44.67 %
Refusal Rate: 55.33 %
Average Patient Satisfaction: 79.6
Average Staff Morale: 72.42

In [4]:
# ==========================================
# BED MANAGEMENT - SERVICE VALUES
# ==========================================

print("Bed Management Services:")
print(bed_management["Service"].unique())

print("\nNumber of Services:",
      bed_management["Service"].nunique())

Bed Management Services:
<ArrowStringArray>
['surgery', 'general_medicine', 'emergency', 'ICU']
Length: 4, dtype: str

Number of Services: 4

In [7]:
# ==========================================
# CHECK DEPARTMENT MAPPING
# ==========================================

print("HMIS Departments:")
print(department["department_name"].unique())

print("\nNumber of HMIS Departments:",
      department["department_name"].nunique())

HMIS Departments:
<ArrowStringArray>
[        'Emergency', 'Internal Medicine',           'Surgery',
        'Pediatrics',       'Orthopedics',               'ICU',
         'Radiology',         'Pathology',          'Pharmacy',
           'Billing',                'HR']
Length: 11, dtype: str

Number of HMIS Departments: 11

In [6]:
import pandas as pd

department = pd.read_csv("department.csv")

print("HMIS Departments:")
print(department["department_name"].unique())

print("\nNumber of HMIS Departments:",
      department["department_name"].nunique())

HMIS Departments:
<ArrowStringArray>
[        'Emergency', 'Internal Medicine',           'Surgery',
        'Pediatrics',       'Orthopedics',               'ICU',
         'Radiology',         'Pathology',          'Pharmacy',
           'Billing',                'HR']
Length: 11, dtype: str

Number of HMIS Departments: 11

In [8]:
# ==========================================
# BED MANAGEMENT ↔ HMIS DEPARTMENT MAPPING
# ==========================================

bed_services = set(
    bed_management["Service"].str.lower().str.strip()
)

hmis_departments = set(
    department["department_name"].astype(str).str.lower().str.strip()
)

print("Services present in both datasets:")
print(bed_services.intersection(hmis_departments))

print("\nServices only in Bed Management:")
print(bed_services - hmis_departments)

print("\nDepartments only in HMIS:")
print(hmis_departments - bed_services)

Services present in both datasets:
{'surgery', 'icu', 'emergency'}

Services only in Bed Management:
{'general_medicine'}

Departments only in HMIS:
{'orthopedics', 'pediatrics', 'internal medicine', 'radiology', 'billing', 'pathology', 'hr', 'pharmacy'}

In [9]:
bed_management.groupby("Service")["Available Beds (Wk)"].nunique()

Service
ICU                 15
emergency           18
general_medicine    33
surgery             31
Name: Available Beds (Wk), dtype: int64

In [10]:
# ==========================================
# BED MANAGEMENT - WEEKLY RESOURCE TABLE
# ==========================================

bed_resource_weekly = (
    bed_management
    .groupby(["Service", "Week"])
    .agg(
        available_beds=("Available Beds (Wk)", "max"),
        patients_requested=("Patients Requested (Wk)", "sum"),
        patients_admitted=("Patients Admitted (Wk)", "sum"),
        patients_refused=("Patients Refused (Wk)", "sum")
    )
    .reset_index()
)

bed_resource_weekly["admission_rate"] = (
    bed_resource_weekly["patients_admitted"]
    / bed_resource_weekly["patients_requested"]
    * 100
).round(2)

bed_resource_weekly["refusal_rate"] = (
    bed_resource_weekly["patients_refused"]
    / bed_resource_weekly["patients_requested"]
    * 100
).round(2)

display(bed_resource_weekly.head(20))

,Service,Week,available_beds,patients_requested,patients_admitted,patients_refused,admission_rate,refusal_rate
0,ICU,1,22,217,154,63,70.97,29.03
1,ICU,2,16,28,28,0,100.00,0.00
2,ICU,3,20,105,100,5,95.24,4.76
3,ICU,4,20,126,120,6,95.24,4.76
4,ICU,5,22,13,13,0,100.00,0.00
5,ICU,6,14,48,48,0,100.00,0.00
6,ICU,7,21,141,63,78,44.68,55.32
7,ICU,8,12,70,70,0,100.00,0.00
8,ICU,9,11,140,77,63,55.00,45.00
9,ICU,10,13,8,8,0,100.00,0.00
10,ICU,11,14,68,56,12,82.35,17.65
11,ICU,12,16,52,52,0,100.00,0.00
12,ICU,13,17,36,36,0,100.00,0.00
13,ICU,14,10,112,70,42,62.50,37.50
14,ICU,15,14,66,66,0,100.00,0.00
15,ICU,16,18,45,45,0,100.00,0.00
16,ICU,17,14,34,28,6,82.35,17.65
17,ICU,18,12,27,27,0,100.00,0.00
18,ICU,19,14,136,112,24,82.35,17.65
19,ICU,20,10,70,50,20,71.43,28.57

In [11]:
# ==========================================
# ADD STAFF & RESOURCE METRICS
# ==========================================

staff_resource = (
    bed_management
    .groupby(["Service", "Week"])
    .agg(
        total_staff=("Dept Total Staff", "max"),
        doctor_count=("Dept Doctor Count", "max"),
        nurse_count=("Dept Nurse Count", "max"),
        nursing_assistant_count=("Dept Nursing Assistant Count", "max"),
        avg_satisfaction=("Avg Satisfaction (Wk)", "max"),
        staff_morale=("Staff Morale (Wk)", "max")
    )
    .reset_index()
)

display(staff_resource.head(20))

,Service,Week,total_staff,doctor_count,nurse_count,nursing_assistant_count,avg_satisfaction,staff_morale
0,ICU,1,32,6,18,8,84,91
1,ICU,2,32,6,18,8,79,85
2,ICU,3,32,6,18,8,82,89
3,ICU,4,32,6,18,8,64,85
4,ICU,5,32,6,18,8,73,88
5,ICU,6,32,6,18,8,87,51
6,ICU,7,32,6,18,8,72,83
7,ICU,8,32,6,18,8,76,98
8,ICU,9,32,6,18,8,97,73
9,ICU,10,32,6,18,8,91,56
10,ICU,11,32,6,18,8,61,50
11,ICU,12,32,6,18,8,79,94
12,ICU,13,32,6,18,8,66,52
13,ICU,14,32,6,18,8,92,54
14,ICU,15,32,6,18,8,92,52
15,ICU,16,32,6,18,8,98,78
16,ICU,17,32,6,18,8,87,83
17,ICU,18,32,6,18,8,63,55
18,ICU,19,32,6,18,8,68,61
19,ICU,20,32,6,18,8,85,65

In [12]:
# ==========================================
# FINAL BED MANAGEMENT RESOURCE TABLE
# ==========================================

bed_management_resource = bed_resource_weekly.merge(
    staff_resource,
    on=["Service", "Week"],
    how="left"
)

print("===== BED MANAGEMENT RESOURCE TABLE =====")
print("Rows:", len(bed_management_resource))
print("Columns:", len(bed_management_resource.columns))

display(bed_management_resource.head(20))

===== BED MANAGEMENT RESOURCE TABLE =====
Rows: 208
Columns: 14

,Service,Week,available_beds,patients_requested,patients_admitted,patients_refused,admission_rate,refusal_rate,total_staff,doctor_count,nurse_count,nursing_assistant_count,avg_satisfaction,staff_morale
0,ICU,1,22,217,154,63,70.97,29.03,32,6,18,8,84,91
1,ICU,2,16,28,28,0,100.00,0.00,32,6,18,8,79,85
2,ICU,3,20,105,100,5,95.24,4.76,32,6,18,8,82,89
3,ICU,4,20,126,120,6,95.24,4.76,32,6,18,8,64,85
4,ICU,5,22,13,13,0,100.00,0.00,32,6,18,8,73,88
5,ICU,6,14,48,48,0,100.00,0.00,32,6,18,8,87,51
6,ICU,7,21,141,63,78,44.68,55.32,32,6,18,8,72,83
7,ICU,8,12,70,70,0,100.00,0.00,32,6,18,8,76,98
8,ICU,9,11,140,77,63,55.00,45.00,32,6,18,8,97,73
9,ICU,10,13,8,8,0,100.00,0.00,32,6,18,8,91,56
10,ICU,11,14,68,56,12,82.35,17.65,32,6,18,8,61,50
11,ICU,12,16,52,52,0,100.00,0.00,32,6,18,8,79,94
12,ICU,13,17,36,36,0,100.00,0.00,32,6,18,8,66,52
13,ICU,14,10,112,70,42,62.50,37.50,32,6,18,8,92,54
14,ICU,15,14,66,66,0,100.00,0.00,32,6,18,8,92,52
15,ICU,16,18,45,45,0,100.00,0.00,32,6,18,8,98,78
16,ICU,17,14,34,28,6,82.35,17.65,32,6,18,8,87,83
17,ICU,18,12,27,27,0,100.00,0.00,32,6,18,8,63,55
18,ICU,19,14,136,112,24,82.35,17.65,32,6,18,8,68,61
19,ICU,20,10,70,50,20,71.43,28.57,32,6,18,8,85,65

In [15]:
import pandas as pd

# Load HMIS cleaned data
hmis_data = pd.ExcelFile("HMIS_Cleaned_Data.xlsx")

# Check available sheets
print("Sheets:")
print(hmis_data.sheet_names)

Sheets:
['patient', 'department', 'ward', 'bed', 'employee', 'doctor', 'staff_assignment', 'admission', 'disease', 'diagnostic_test', 'patient_diagnostic', 'drug', 'drug_manufacturer', 'drug_inventory', 'prescription', 'billing', 'billing_detail', 'insurance_provider', 'patient_insurance']

In [17]:
# Load Patient dataset
patient = pd.read_excel(
    "HMIS_Cleaned_Data.xlsx",
    sheet_name="patient"
)

print("Patient dataset loaded successfully!")
print("Rows:", len(patient))
print("Columns:", patient.columns.tolist())

patient.head()

Patient dataset loaded successfully!
Rows: 30000
Columns: ['patient_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number']

,patient_id,gender,date_of_birth,blood_group,city,contact_number
0,1,FEMALE,1987-08-24,O-,East Stephanieberg,+1-792-342-0981
1,2,MALE,1960-05-18,A-,Manuelbury,793-725-0800
2,3,MALE,1955-04-24,A-,Lake Susanchester,+1-330-617-3749x232
3,4,MALE,2004-06-16,B-,South Leslieburgh,426-611-6235x07684
4,5,MALE,1977-07-22,A-,Lopezchester,(215)330-2831x0821

In [18]:
# ==========================================
# PATIENT DEMOGRAPHICS SUMMARY
# ==========================================

patient_demographics = {
    "Total Patients": patient["patient_id"].nunique(),
    "Male Patients": (patient["gender"].str.lower() == "male").sum(),
    "Female Patients": (patient["gender"].str.lower() == "female").sum(),
    "Other Gender": (~patient["gender"].str.lower().isin(["male", "female"])).sum(),
    "Unique Cities": patient["city"].nunique(),
    "Unique Blood Groups": patient["blood_group"].nunique()
}

print("===== PATIENT DEMOGRAPHICS =====")

for key, value in patient_demographics.items():
    print(f"{key}: {value}")

===== PATIENT DEMOGRAPHICS =====
Total Patients: 30000
Male Patients: 15918
Female Patients: 13478
Other Gender: 604
Unique Cities: 17836
Unique Blood Groups: 8

In [19]:
# ==========================================
# PATIENT DEMOGRAPHIC DISTRIBUTION
# ==========================================

print("===== GENDER DISTRIBUTION =====")

gender_distribution = patient["gender"].value_counts()

print(gender_distribution)


print("\n===== BLOOD GROUP DISTRIBUTION =====")

blood_group_distribution = patient["blood_group"].value_counts()

print(blood_group_distribution)

===== GENDER DISTRIBUTION =====
gender
MALE      15918
FEMALE    13478
OTHER       604
Name: count, dtype: int64

===== BLOOD GROUP DISTRIBUTION =====
blood_group
O+     3851
AB-    3839
O-     3792
A-     3779
AB+    3752
A+     3730
B+     3695
B-     3562
Name: count, dtype: int64

In [22]:
# ==========================================
# PATIENT AGE ANALYSIS
# ==========================================

dob = pd.to_datetime(
    patient["date_of_birth"],
    errors="coerce"
)

current_date = pd.Timestamp.today()

age = (
    (current_date - dob).dt.days / 365.25
).astype(int)

print("===== PATIENT AGE ANALYSIS =====")

print("Average Age:", round(age.mean(), 2))
print("Minimum Age:", age.min())
print("Maximum Age:", age.max())

===== PATIENT AGE ANALYSIS =====
Average Age: 45.22
Minimum Age: 0
Maximum Age: 91

In [24]:
import pandas as pd

readmission = pd.read_excel(
    r"readmission_cleaned.xlsx"
)

print("Readmission dataset loaded successfully!")
print("Rows:", len(readmission))
print("Columns:", readmission.columns.tolist())

display(readmission.head())

Readmission dataset loaded successfully!
Rows: 10000
Columns: ['hospital_name', 'Admission_date', 'hospital_id', 'hospital_beds_available', 'occupied_beds', 'hospital_ward', 'patient_id', 'patient_gender', 'patient_age', 'patient_race', 'patient_sat_score', 'patient_first_initial', 'patient_last_name', 'patient_waittime', 'department_referral', 'time_slot', 'doctor_id', 'doctor_name', 'doctor_specialty', 'patient_assigned_doctor', 'patient_checkin_date', 'patient_checkout_date', 'patient_disease', 'patient_length_of_stay', 'discharge_status', 'readmission']

,hospital_name,Admission_date,hospital_id,hospital_beds_available,occupied_beds,hospital_ward,patient_id,patient_gender,patient_age,patient_race,...,doctor_id,doctor_name,doctor_specialty,patient_assigned_doctor,patient_checkin_date,patient_checkout_date,patient_disease,patient_length_of_stay,discharge_status,readmission
0,The Johns Hopkins Hospital,1/30/2024,3946,260,90,Maternity,1421,Female,48,Asian,...,1725,Justin Morris,Rheumatology,False,7/14/2024,7/19/2024,Anxiety Disorders,6,Deceased,1
1,The Johns Hopkins Hospital,3/20/2022,7147,250,90,ICU,4922,Male,40,Black,...,7510,Latoya Moss,Pulmonology or Allergy and Immunology,False,7/19/2024,7/7/2024,Urinary Tract Infection (UTI),2,Deceased,1
2,The Johns Hopkins Hospital,7/13/2021,4174,350,220,Pediatrics,9804,Female,74,Black,...,7137,Michael Allen,Neurology,False,7/20/2024,6/29/2024,Hypertension (High Blood Pressure),17,Recovered,0
3,The Johns Hopkins Hospital,1/26/2021,2466,190,350,Pediatrics,5622,Male,82,Hispanic,...,8801,Rebecca Mccullough,Cardiology,False,6/25/2024,7/16/2024,Arthritis,28,Recovered,0
4,The Johns Hopkins Hospital,2/6/2024,3014,220,390,Surgery,3314,Male,62,Hispanic,...,3588,John Giles,Rheumatology,False,7/21/2024,7/19/2024,Cancer,16,Transferred,1

In [25]:
# ==========================================
# READMISSION DATASET - KEY INFORMATION
# ==========================================

print("===== READMISSION DATASET =====")

print("Total Records:", len(readmission))

print("\nColumns:")
print(readmission.columns.tolist())

print("\nFirst 5 Records:")
display(readmission.head())

===== READMISSION DATASET =====
Total Records: 10000

Columns:
['hospital_name', 'Admission_date', 'hospital_id', 'hospital_beds_available', 'occupied_beds', 'hospital_ward', 'patient_id', 'patient_gender', 'patient_age', 'patient_race', 'patient_sat_score', 'patient_first_initial', 'patient_last_name', 'patient_waittime', 'department_referral', 'time_slot', 'doctor_id', 'doctor_name', 'doctor_specialty', 'patient_assigned_doctor', 'patient_checkin_date', 'patient_checkout_date', 'patient_disease', 'patient_length_of_stay', 'discharge_status', 'readmission']

First 5 Records:

,hospital_name,Admission_date,hospital_id,hospital_beds_available,occupied_beds,hospital_ward,patient_id,patient_gender,patient_age,patient_race,...,doctor_id,doctor_name,doctor_specialty,patient_assigned_doctor,patient_checkin_date,patient_checkout_date,patient_disease,patient_length_of_stay,discharge_status,readmission
0,The Johns Hopkins Hospital,1/30/2024,3946,260,90,Maternity,1421,Female,48,Asian,...,1725,Justin Morris,Rheumatology,False,7/14/2024,7/19/2024,Anxiety Disorders,6,Deceased,1
1,The Johns Hopkins Hospital,3/20/2022,7147,250,90,ICU,4922,Male,40,Black,...,7510,Latoya Moss,Pulmonology or Allergy and Immunology,False,7/19/2024,7/7/2024,Urinary Tract Infection (UTI),2,Deceased,1
2,The Johns Hopkins Hospital,7/13/2021,4174,350,220,Pediatrics,9804,Female,74,Black,...,7137,Michael Allen,Neurology,False,7/20/2024,6/29/2024,Hypertension (High Blood Pressure),17,Recovered,0
3,The Johns Hopkins Hospital,1/26/2021,2466,190,350,Pediatrics,5622,Male,82,Hispanic,...,8801,Rebecca Mccullough,Cardiology,False,6/25/2024,7/16/2024,Arthritis,28,Recovered,0
4,The Johns Hopkins Hospital,2/6/2024,3014,220,390,Surgery,3314,Male,62,Hispanic,...,3588,John Giles,Rheumatology,False,7/21/2024,7/19/2024,Cancer,16,Transferred,1

In [28]:
# ==========================================
# READMISSION ANALYSIS
# ==========================================

print("===== READMISSION ANALYSIS =====")

total_records = len(readmission)

unique_patients = readmission["patient_id"].nunique()

print("Total Records:", total_records)
print("Unique Patients:", unique_patients)

print("\nReadmission Distribution:")
print(readmission["readmission"].value_counts())

print("\nReadmission Percentage:")
print(
    (readmission["readmission"].value_counts(normalize=True) * 100)
    .round(2)
)

===== READMISSION ANALYSIS =====
Total Records: 10000
Unique Patients: 6022

Readmission Distribution:
readmission
0    5858
1    4142
Name: count, dtype: int64

Readmission Percentage:
readmission
0    58.58
1    41.42
Name: proportion, dtype: float64

In [27]:
print("Actual Readmission Columns:")
for col in readmission.columns:
    print(repr(col))

Actual Readmission Columns:
'hospital_name'
'Admission_date'
'hospital_id'
'hospital_beds_available'
'occupied_beds'
'hospital_ward'
'patient_id'
'patient_gender'
'patient_age'
'patient_race'
'patient_sat_score'
'patient_first_initial'
'patient_last_name'
'patient_waittime'
'department_referral'
'time_slot'
'doctor_id'
'doctor_name'
'doctor_specialty'
'patient_assigned_doctor'
'patient_checkin_date'
'patient_checkout_date'
'patient_disease'
'patient_length_of_stay'
'discharge_status'
'readmission'

In [29]:
# ==========================================
# DEPARTMENT-WISE READMISSION ANALYSIS
# ==========================================

department_readmission = (
    readmission
    .groupby("department_referral")
    .agg(
        total_records=("patient_id", "count"),
        readmitted=("readmission", "sum")
    )
    .reset_index()
)

department_readmission["readmission_rate"] = (
    department_readmission["readmitted"]
    / department_readmission["total_records"]
    * 100
).round(2)

department_readmission = department_readmission.sort_values(
    "readmission_rate",
    ascending=False
)

print("===== DEPARTMENT-WISE READMISSION =====")

display(department_readmission)

===== DEPARTMENT-WISE READMISSION =====

,department_referral,total_records,readmitted,readmission_rate
13,Psychiatry,730,325,44.52
6,Hepatology,367,162,44.14
2,Cardiology or Internal Medicine,346,152,43.93
0,Allergy and Immunology,359,157,43.73
1,Cardiology,374,161,43.05
18,Urology or Nephrology,351,151,43.02
5,Gastroenterology,1094,467,42.69
15,Pulmonology or Allergy and Immunology,380,159,41.84
9,Infectious Disease or Internal Medicine,700,291,41.57
11,Neurology,1790,741,41.40
17,Rheumatology,720,294,40.83
16,Pulmonology or Infectious Disease,336,135,40.18
4,Endocrinology,347,139,40.06
12,Oncology,349,138,39.54
8,Infectious Disease,362,143,39.50
3,Dermatology,339,132,38.94
10,Nephrology,331,125,37.76
14,Pulmonology,354,132,37.29
7,Hepatology or Gastroenterology,371,138,37.20

In [30]:
# ==========================================
# AGE & LENGTH OF STAY VS READMISSION
# ==========================================

readmission_analysis = (
    readmission
    .groupby("readmission")
    .agg(
        patients=("patient_id", "count"),
        average_age=("patient_age", "mean"),
        average_length_of_stay=("patient_length_of_stay", "mean"),
        average_waittime=("patient_waittime", "mean"),
        average_satisfaction=("patient_sat_score", "mean")
    )
    .reset_index()
)

readmission_analysis["average_age"] = (
    readmission_analysis["average_age"].round(2)
)

readmission_analysis["average_length_of_stay"] = (
    readmission_analysis["average_length_of_stay"].round(2)
)

readmission_analysis["average_waittime"] = (
    readmission_analysis["average_waittime"].round(2)
)

readmission_analysis["average_satisfaction"] = (
    readmission_analysis["average_satisfaction"].round(2)
)

print("===== READMISSION PROFILE =====")

display(readmission_analysis)

===== READMISSION PROFILE =====

,readmission,patients,average_age,average_length_of_stay,average_waittime,average_satisfaction
0,0,5858,47.10,15.50,68.04,851.02
1,1,4142,47.55,15.52,67.52,843.25

In [31]:
# ==========================================
# DISCHARGE STATUS VS READMISSION
# ==========================================

discharge_readmission = (
    readmission
    .groupby("discharge_status")
    .agg(
        total_records=("patient_id", "count"),
        readmitted=("readmission", "sum")
    )
    .reset_index()
)

discharge_readmission["readmission_rate"] = (
    discharge_readmission["readmitted"]
    / discharge_readmission["total_records"]
    * 100
).round(2)

discharge_readmission = discharge_readmission.sort_values(
    "readmission_rate",
    ascending=False
)

print("===== DISCHARGE STATUS VS READMISSION =====")

display(discharge_readmission)

===== DISCHARGE STATUS VS READMISSION =====

  discharge_status  total_records  readmitted  readmission_rate
1        Recovered           3384        1450             42.85
2      Transferred           3297        1371             41.58
0         Deceased           3319        1321             39.80

In [33]:
# ==========================================
# CHECK CURRENT DATAFRAMES
# ==========================================

dataframes = []

for name, obj in list(globals().items()):
    if hasattr(obj, "shape") and hasattr(obj, "columns"):
        dataframes.append((name, obj.shape))

print("Current DataFrames:")

for name, shape in dataframes:
    print(name, "->", shape)

Current DataFrames:
_ -> (5, 6)
bed_management -> (1000, 21)
department -> (11, 5)
bed_resource_weekly -> (208, 8)
staff_resource -> (208, 8)
bed_management_resource -> (208, 14)
patient -> (30000, 6)
_17 -> (5, 6)
readmission -> (10000, 26)
department_readmission -> (19, 4)
readmission_analysis -> (2, 6)
discharge_readmission -> (3, 4)

In [37]:
# ==========================================
# LOAD ALL 19 HMIS CSV FILES
# ==========================================

import pandas as pd

admission = pd.read_csv("admission.csv")
bed = pd.read_csv("bed.csv")
billing_detail = pd.read_csv("billing_detail.csv")
billing = pd.read_csv("billing.csv")
department = pd.read_csv("department.csv")
diagnostic_test = pd.read_csv("diagnostic_test.csv")
disease = pd.read_csv("disease.csv")
doctor = pd.read_csv("doctor.csv")
drug_inventory = pd.read_csv("drug_inventory.csv")
drug_manufacturer = pd.read_csv("drug_manufacturer.csv")
drug = pd.read_csv("drug.csv")
employee = pd.read_csv("employee.csv")
insurance_provider = pd.read_csv("insurance_provider.csv")
patient_diagnostic = pd.read_csv("patient_diagnostic.csv")
patient_insurance = pd.read_csv("patient_insurance.csv")
patient = pd.read_csv("patient.csv")
prescription = pd.read_csv("prescription.csv")
staff_assignment = pd.read_csv("staff_assignment.csv")

print("===== HMIS FILES LOADED =====")

files = {
    "admission": admission,
    "bed": bed,
    "billing_detail": billing_detail,
    "billing": billing,
    "department": department,
    "diagnostic_test": diagnostic_test,
    "disease": disease,
    "doctor": doctor,
    "drug_inventory": drug_inventory,
    "drug_manufacturer": drug_manufacturer,
    "drug": drug,
    "employee": employee,
    "insurance_provider": insurance_provider,
    "patient_diagnostic": patient_diagnostic,
    "patient_insurance": patient_insurance,
    "patient": patient,
    "prescription": prescription,
    "staff_assignment": staff_assignment
}

for name, df in files.items():
    print(name, "->", df.shape)

===== HMIS FILES LOADED =====
admission -> (45000, 10)
bed -> (415, 4)
billing_detail -> (112402, 5)
billing -> (45000, 8)
department -> (11, 5)
diagnostic_test -> (9, 5)
disease -> (20, 3)
doctor -> (98, 5)
drug_inventory -> (250, 6)
drug_manufacturer -> (300, 5)
drug -> (250, 6)
employee -> (500, 7)
insurance_provider -> (50, 5)
patient_diagnostic -> (63269, 6)
patient_insurance -> (21617, 7)
patient -> (30000, 6)
prescription -> (73109, 6)
staff_assignment -> (207, 4)

In [38]:
# ==========================================
# CHECK ALL HMIS CSV FILES
# ==========================================

import os

csv_files = [f for f in os.listdir(".") if f.lower().endswith(".csv")]

print("===== CSV FILES IN FOLDER =====")
print("Total CSV files:", len(csv_files))

for i, file in enumerate(csv_files, 1):
    print(i, "->", file)

===== CSV FILES IN FOLDER =====
Total CSV files: 19
1 -> admission.csv
2 -> bed.csv
3 -> billing.csv
4 -> billing_detail.csv
5 -> department.csv
6 -> diagnostic_test.csv
7 -> disease.csv
8 -> doctor.csv
9 -> drug.csv
10 -> drug_inventory.csv
11 -> drug_manufacturer.csv
12 -> employee.csv
13 -> insurance_provider.csv
14 -> patient.csv
15 -> patient_diagnostic.csv
16 -> patient_insurance.csv
17 -> prescription.csv
18 -> staff_assignment.csv
19 -> ward.csv

In [39]:
ward = pd.read_csv("ward.csv")

print("===== WARD DATASET LOADED =====")

print("Rows:", len(ward))
print("Columns:", len(ward.columns))

print("\nColumns:")
print(ward.columns.tolist())

display(ward.head())

===== WARD DATASET LOADED =====
Rows: 27
Columns: 5

Columns:
['ward_id', 'ward_name', 'ward_type', 'total_beds', 'department_id']

   ward_id         ward_name ward_type  total_beds  department_id
0        1  Emergency Ward 1   General          10              1
1        2  Emergency Ward 2   Private          15              1
2        3  Emergency Ward 3   General          10              1
3        4  Emergency Ward 4   General          20              1
4        5  Emergency Ward 5   General          20              1

In [40]:
# ==========================================
# STEP 4 - HMIS RELATIONSHIP VALIDATION
# ==========================================

print("===== HMIS RELATIONSHIP VALIDATION =====")

# Patient -> Admission
patient_check = admission["patient_id"].isin(
    patient["patient_id"]
).sum()

print(
    "Admission records with valid patient_id:",
    patient_check,
    "/",
    len(admission)
)

# Department -> Admission
department_check = admission["department_id"].isin(
    department["department_id"]
).sum()

print(
    "Admission records with valid department_id:",
    department_check,
    "/",
    len(admission)
)

# Ward -> Admission
ward_check = admission["ward_id"].isin(
    ward["ward_id"]
).sum()

print(
    "Admission records with valid ward_id:",
    ward_check,
    "/",
    len(admission)
)

# Bed -> Admission
bed_check = admission["bed_id"].isin(
    bed["bed_id"]
).sum()

print(
    "Admission records with valid bed_id:",
    bed_check,
    "/",
    len(admission)
)

# Admission -> Billing
billing_check = billing["admission_id"].isin(
    admission["admission_id"]
).sum()

print(
    "Billing records with valid admission_id:",
    billing_check,
    "/",
    len(billing)
)

# Department -> Ward
ward_department_check = ward["department_id"].isin(
    department["department_id"]
).sum()

print(
    "Wards with valid department_id:",
    ward_department_check,
    "/",
    len(ward)
)

===== HMIS RELATIONSHIP VALIDATION =====
Admission records with valid patient_id: 45000 / 45000
Admission records with valid department_id: 45000 / 45000
Admission records with valid ward_id: 45000 / 45000
Admission records with valid bed_id: 45000 / 45000
Billing records with valid admission_id: 45000 / 45000
Wards with valid department_id: 27 / 27

In [43]:
# ==========================================
# FINAL TABLE 1 - HOSPITAL OVERVIEW
# ==========================================

# Calculate Length of Stay from admission and discharge dates
admission["admission_date"] = pd.to_datetime(admission["admission_date"])
admission["discharge_date"] = pd.to_datetime(admission["discharge_date"])

admission["length_of_stay"] = (
    admission["discharge_date"] - admission["admission_date"]
).dt.days

# Hospital KPIs
total_patients = patient["patient_id"].nunique()

total_admissions = admission["admission_id"].nunique()

total_departments = department["department_id"].nunique()

total_wards = ward["ward_id"].nunique()

total_beds = bed["bed_id"].nunique()

total_doctors = doctor["doctor_id"].nunique()

average_length_of_stay = admission["length_of_stay"].mean()

total_bills = billing["bill_id"].nunique()

total_revenue = billing_detail["amount"].sum()

readmission_rate = readmission["readmission"].mean() * 100


# Create final table
hospital_overview = pd.DataFrame({
    "KPI": [
        "Total Patients",
        "Total Admissions",
        "Total Departments",
        "Total Wards",
        "Total Beds",
        "Total Doctors",
        "Average Length of Stay",
        "Total Bills",
        "Total Revenue",
        "Readmission Rate (%)"
    ],

    "Value": [
        total_patients,
        total_admissions,
        total_departments,
        total_wards,
        total_beds,
        total_doctors,
        round(average_length_of_stay, 2),
        total_bills,
        round(total_revenue, 2),
        round(readmission_rate, 2)
    ]
})

print("===== FINAL TABLE 1 - HOSPITAL OVERVIEW =====")

display(hospital_overview)

===== FINAL TABLE 1 - HOSPITAL OVERVIEW =====

                      KPI         Value
0          Total Patients  3.000000e+04
1        Total Admissions  4.500000e+04
2       Total Departments  1.100000e+01
3             Total Wards  2.700000e+01
4              Total Beds  4.150000e+02
5           Total Doctors  9.800000e+01
6  Average Length of Stay  5.160000e+00
7             Total Bills  4.500000e+04
8           Total Revenue  1.478880e+09
9    Readmission Rate (%)  4.142000e+01

In [42]:
print("===== ADMISSION COLUMNS =====")

print(admission.columns.tolist())

===== ADMISSION COLUMNS =====
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id']

In [44]:
# ==========================================
# FINAL TABLE 2 - REQUIRED COLUMN CHECK
# ==========================================

tables_to_check = {
    "patient": patient,
    "admission": admission,
    "disease": disease,
    "patient_diagnostic": patient_diagnostic,
    "prescription": prescription,
    "readmission": readmission
}

for name, df in tables_to_check.items():
    print("\n" + "=" * 50)
    print(name.upper())
    print("=" * 50)
    print(df.columns.tolist())

==================================================
PATIENT
==================================================
['patient_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number']

==================================================
ADMISSION
==================================================
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id', 'length_of_stay']

==================================================
DISEASE
==================================================
['disease_id', 'disease_name', 'disease_category']

==================================================
PATIENT_DIAGNOSTIC
==================================================
['patient_diagnostic_id', 'test_date', 'result_status', 'admission_id', 'test_id', 'doctor_id']

==================================================
PRESCRIPTION
==================================================
['prescription_id', 'dosage', 'frequency', 'duration_days', 'admission_id', 'drug_id']

==================================================
READMISSION
==================================================
['hospital_name', 'Admission_date', 'hospital_id', 'hospital_beds_available', 'occupied_beds', 'hospital_ward', 'patient_id', 'patient_gender', 'patient_age', 'patient_race', 'patient_sat_score', 'patient_first_initial', 'patient_last_name', 'patient_waittime', 'department_referral', 'time_slot', 'doctor_id', 'doctor_name', 'doctor_specialty', 'patient_assigned_doctor', 'patient_checkin_date', 'patient_checkout_date', 'patient_disease', 'patient_length_of_stay', 'discharge_status', 'readmission']

In [45]:
# ==========================================
# FINAL TABLE 2 - PATIENT & CLINICAL ANALYTICS
# ==========================================

# 1. Patient-wise admission summary
patient_admission = (
    admission
    .groupby("patient_id")
    .agg(
        total_admissions=("admission_id", "nunique"),
        average_length_of_stay=("length_of_stay", "mean"),
        total_length_of_stay=("length_of_stay", "sum")
    )
    .reset_index()
)


# 2. Patient-wise diagnostic test count
patient_diagnostic_count = (
    patient_diagnostic
    .groupby("admission_id")
    .size()
    .reset_index(name="diagnostic_tests")
)

# Map admission_id -> patient_id
diagnostic_patient = patient_diagnostic_count.merge(
    admission[["admission_id", "patient_id"]],
    on="admission_id",
    how="left"
)

diagnostic_patient = (
    diagnostic_patient
    .groupby("patient_id")
    ["diagnostic_tests"]
    .sum()
    .reset_index()
)


# 3. Patient-wise prescription count
patient_prescription_count = (
    prescription
    .groupby("admission_id")
    .size()
    .reset_index(name="prescription_count")
)

# Map admission_id -> patient_id
prescription_patient = patient_prescription_count.merge(
    admission[["admission_id", "patient_id"]],
    on="admission_id",
    how="left"
)

prescription_patient = (
    prescription_patient
    .groupby("patient_id")
    ["prescription_count"]
    .sum()
    .reset_index()
)


# 4. Patient-wise disease count
patient_disease = (
    admission
    .groupby("patient_id")
    ["disease_id"]
    .nunique()
    .reset_index(name="unique_diseases")
)


# 5. Readmission information
readmission_patient = (
    readmission
    .groupby("patient_id")
    .agg(
        readmission_records=("readmission", "count"),
        readmitted=("readmission", "max")
    )
    .reset_index()
)


# 6. Combine everything
patient_clinical = patient[
    ["patient_id", "gender", "blood_group", "city"]
].copy()

patient_clinical = patient_clinical.merge(
    patient_admission,
    on="patient_id",
    how="left"
)

patient_clinical = patient_clinical.merge(
    diagnostic_patient,
    on="patient_id",
    how="left"
)

patient_clinical = patient_clinical.merge(
    prescription_patient,
    on="patient_id",
    how="left"
)

patient_clinical = patient_clinical.merge(
    patient_disease,
    on="patient_id",
    how="left"
)

patient_clinical = patient_clinical.merge(
    readmission_patient,
    on="patient_id",
    how="left"
)


# 7. Fill patients with no diagnostic/prescription/readmission record
patient_clinical[
    ["diagnostic_tests",
     "prescription_count",
     "unique_diseases",
     "readmission_records",
     "readmitted"]
] = patient_clinical[
    ["diagnostic_tests",
     "prescription_count",
     "unique_diseases",
     "readmission_records",
     "readmitted"]
].fillna(0)


# 8. Round average LOS
patient_clinical["average_length_of_stay"] = (
    patient_clinical["average_length_of_stay"].round(2)
)


print("===== FINAL TABLE 2 - PATIENT & CLINICAL ANALYTICS =====")

print("Rows:", len(patient_clinical))
print("Columns:", len(patient_clinical.columns))

display(patient_clinical.head(10))

===== FINAL TABLE 2 - PATIENT & CLINICAL ANALYTICS =====
Rows: 30000
Columns: 12

,patient_id,gender,blood_group,city,total_admissions,average_length_of_stay,total_length_of_stay,diagnostic_tests,prescription_count,unique_diseases,readmission_records,readmitted
0,1,Female,O-,East Stephanieberg,3.0,3.33,10.0,3.0,3.0,3.0,0.0,0.0
1,2,Male,A-,Manuelbury,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
2,3,Male,A-,Lake Susanchester,2.0,7.50,15.0,3.0,0.0,2.0,0.0,0.0
3,4,Male,B-,South Leslieburgh,2.0,3.50,7.0,2.0,5.0,2.0,0.0,0.0
4,5,Male,A-,Lopezchester,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
5,6,Male,AB+,Port Austinfurt,1.0,2.00,2.0,0.0,4.0,1.0,0.0,0.0
6,7,Male,AB-,Merrittborough,1.0,8.00,8.0,2.0,0.0,1.0,0.0,0.0
7,8,Male,B-,Tinabury,2.0,9.50,19.0,6.0,1.0,2.0,0.0,0.0
8,9,Female,O-,Kingfort,1.0,8.00,8.0,3.0,0.0,1.0,0.0,0.0
9,10,Female,A+,Raymondside,4.0,8.75,35.0,6.0,7.0,4.0,0.0,0.0

In [46]:
# ==========================================
# FINAL TABLE 3 - REQUIRED COLUMN CHECK
# ==========================================

tables_to_check = {
    "department": department,
    "ward": ward,
    "bed": bed,
    "doctor": doctor,
    "staff_assignment": staff_assignment,
    "employee": employee,
    "bed_management": bed_management
}

for name, df in tables_to_check.items():
    print("\n" + "=" * 50)
    print(name.upper())
    print("=" * 50)
    print(df.columns.tolist())

==================================================
DEPARTMENT
==================================================
['department_id', 'department_name', 'department_type', 'floor_number', 'status']

==================================================
WARD
==================================================
['ward_id', 'ward_name', 'ward_type', 'total_beds', 'department_id']

==================================================
BED
==================================================
['bed_id', 'bed_number', 'bed_status', 'ward_id']

==================================================
DOCTOR
==================================================
['doctor_id', 'employee_id', 'specialization', 'qualification', 'experience_years']

==================================================
STAFF_ASSIGNMENT
==================================================
['assignment_id', 'employee_id', 'ward_id', 'shift']

==================================================
EMPLOYEE
==================================================
['employee_id', 'employee_name', 'gender', 'role', 'employment_type', 'date_of_joining', 'department_id']

==================================================
BED_MANAGEMENT
==================================================
['Patient ID', 'Name', 'Age', 'Service', 'Arrival Date', 'Departure Date', 'Length of Stay (days)', 'Week', 'Admission Month', 'Patient Satisfaction Score', 'Available Beds (Wk)', 'Patients Requested (Wk)', 'Patients Admitted (Wk)', 'Patients Refused (Wk)', 'Avg Satisfaction (Wk)', 'Staff Morale (Wk)', 'Notable Event (Wk)', 'Dept Total Staff', 'Dept Doctor Count', 'Dept Nurse Count', 'Dept Nursing Assistant Count']

In [47]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT & RESOURCE ANALYTICS
# ==========================================

# 1. Admissions per department
department_admissions = (
    admission
    .groupby("department_id")
    .agg(
        total_admissions=("admission_id", "nunique"),
        average_length_of_stay=("length_of_stay", "mean")
    )
    .reset_index()
)

# 2. Wards and beds per department
department_wards = (
    ward
    .groupby("department_id")
    .agg(
        total_wards=("ward_id", "nunique"),
        total_ward_beds=("total_beds", "sum")
    )
    .reset_index()
)

# 3. Employees per department
department_staff = (
    employee
    .groupby("department_id")
    .agg(
        total_staff=("employee_id", "nunique")
    )
    .reset_index()
)

# 4. Doctors per department
# Doctor -> Employee -> Department
doctor_department = doctor.merge(
    employee[["employee_id", "department_id"]],
    on="employee_id",
    how="left"
)

department_doctors = (
    doctor_department
    .groupby("department_id")
    .agg(
        total_doctors=("doctor_id", "nunique")
    )
    .reset_index()
)

# 5. Bed status per department
bed_department = bed.merge(
    ward[["ward_id", "department_id"]],
    on="ward_id",
    how="left"
)

department_bed_status = (
    bed_department
    .groupby("department_id")
    .agg(
        total_bed_records=("bed_id", "nunique"),
        occupied_beds=("bed_status", lambda x:
                       (x.astype(str).str.lower() == "occupied").sum()),
        available_beds=("bed_status", lambda x:
                        (x.astype(str).str.lower() == "available").sum())
    )
    .reset_index()
)

# 6. Combine all department-level information
department_resource = department[
    ["department_id", "department_name", "department_type",
     "floor_number", "status"]
].copy()

department_resource = department_resource.merge(
    department_admissions,
    on="department_id",
    how="left"
)

department_resource = department_resource.merge(
    department_wards,
    on="department_id",
    how="left"
)

department_resource = department_resource.merge(
    department_staff,
    on="department_id",
    how="left"
)

department_resource = department_resource.merge(
    department_doctors,
    on="department_id",
    how="left"
)

department_resource = department_resource.merge(
    department_bed_status,
    on="department_id",
    how="left"
)

# 7. Fill missing values
numeric_columns = [
    "total_admissions",
    "average_length_of_stay",
    "total_wards",
    "total_ward_beds",
    "total_staff",
    "total_doctors",
    "total_bed_records",
    "occupied_beds",
    "available_beds"
]

department_resource[numeric_columns] = (
    department_resource[numeric_columns].fillna(0)
)

# 8. Round average LOS
department_resource["average_length_of_stay"] = (
    department_resource["average_length_of_stay"].round(2)
)

print("===== FINAL TABLE 3 - DEPARTMENT & RESOURCE ANALYTICS =====")

print("Rows:", len(department_resource))
print("Columns:", len(department_resource.columns))

display(department_resource)

===== FINAL TABLE 3 - DEPARTMENT & RESOURCE ANALYTICS =====
Rows: 11
Columns: 14

,department_id,department_name,department_type,floor_number,status,total_admissions,average_length_of_stay,total_wards,total_ward_beds,total_staff,total_doctors,total_bed_records,occupied_beds,available_beds
0,1,Emergency,Clinical,0,Active,8777.0,4.69,5.0,75.0,51,13,75.0,47.0,28.0
1,2,Internal Medicine,Clinical,2,Active,7695.0,4.66,5.0,65.0,54,11,65.0,40.0,25.0
2,3,Surgery,Clinical,3,Active,10126.0,4.67,5.0,90.0,43,5,90.0,57.0,33.0
3,4,Pediatrics,Clinical,2,Active,8438.0,4.69,5.0,70.0,33,3,70.0,43.0,27.0
4,5,Orthopedics,Clinical,4,Active,5924.0,4.68,3.0,50.0,40,8,50.0,31.0,19.0
5,6,ICU,Clinical,1,Active,4040.0,9.98,4.0,65.0,45,9,65.0,52.0,13.0
6,7,Radiology,Diagnostic,1,Active,0.0,0.00,0.0,0.0,56,9,0.0,0.0,0.0
7,8,Pathology,Diagnostic,1,Active,0.0,0.00,0.0,0.0,49,11,0.0,0.0,0.0
8,9,Pharmacy,Admin,0,Active,0.0,0.00,0.0,0.0,37,9,0.0,0.0,0.0
9,10,Billing,Admin,0,Active,0.0,0.00,0.0,0.0,49,9,0.0,0.0,0.0
10,11,HR,Admin,0,Active,0.0,0.00,0.0,0.0,43,11,0.0,0.0,0.0

In [48]:
# ==========================================
# FINAL TABLE 4 - REQUIRED COLUMN CHECK
# ==========================================

tables_to_check = {
    "billing": billing,
    "billing_detail": billing_detail,
    "patient_insurance": patient_insurance,
    "insurance_provider": insurance_provider,
    "prescription": prescription,
    "drug": drug,
    "patient_diagnostic": patient_diagnostic,
    "diagnostic_test": diagnostic_test,
    "disease": disease
}

for name, df in tables_to_check.items():
    print("\n" + "=" * 50)
    print(name.upper())
    print("=" * 50)
    print(df.columns.tolist())

==================================================
BILLING
==================================================
['bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode', 'admission_id']

==================================================
BILLING_DETAIL
==================================================
['billing_detail_id', 'charge_type', 'reference_id', 'amount', 'bill_id']

==================================================
PATIENT_INSURANCE
==================================================
['patient_insurance_id', 'policy_number', 'coverage_percentage', 'policy_start_date', 'policy_end_date', 'patient_id', 'insurance_provider_id']

==================================================
INSURANCE_PROVIDER
==================================================
['insurance_provider_id', 'provider_name', 'provider_type', 'contact_details', 'coverage_limit']

==================================================
PRESCRIPTION
==================================================
['prescription_id', 'dosage', 'frequency', 'duration_days', 'admission_id', 'drug_id']

==================================================
DRUG
==================================================
['drug_id', 'drug_name', 'brand_name', 'drug_category', 'unit_cost', 'manufacturer_id']

==================================================
PATIENT_DIAGNOSTIC
==================================================
['patient_diagnostic_id', 'test_date', 'result_status', 'admission_id', 'test_id', 'doctor_id']

==================================================
DIAGNOSTIC_TEST
==================================================
['test_id', 'test_name', 'test_category', 'standard_cost', 'department_id']

==================================================
DISEASE
==================================================
['disease_id', 'disease_name', 'disease_category']

In [49]:
# ==========================================
# FINAL TABLE 4 - BILLING, INSURANCE & CLINICAL UTILIZATION
# ==========================================

# 1. Billing summary
billing_summary = pd.DataFrame({
    "total_bills": [billing["bill_id"].nunique()],
    "total_billed_amount": [billing["total_amount"].sum()],
    "insurance_covered_amount": [billing["insurance_covered_amount"].sum()],
    "patient_payable_amount": [billing["patient_payable_amount"].sum()]
})


# 2. Billing detail summary
billing_detail_summary = pd.DataFrame({
    "total_billing_details": [billing_detail["billing_detail_id"].nunique()],
    "total_charge_amount": [billing_detail["amount"].sum()]
})


# 3. Insurance summary
insurance_summary = pd.DataFrame({
    "insured_patients": [patient_insurance["patient_id"].nunique()],
    "insurance_policies": [patient_insurance["policy_number"].nunique()],
    "insurance_providers": [
        patient_insurance["insurance_provider_id"].nunique()
    ],
    "average_coverage_percentage": [
        patient_insurance["coverage_percentage"].mean()
    ]
})


# 4. Prescription summary
prescription_summary = pd.DataFrame({
    "total_prescriptions": [
        prescription["prescription_id"].nunique()
    ],
    "unique_drugs_prescribed": [
        prescription["drug_id"].nunique()
    ],
    "average_prescription_duration_days": [
        prescription["duration_days"].mean()
    ]
})


# 5. Diagnostic summary
diagnostic_summary = pd.DataFrame({
    "total_diagnostic_tests": [
        patient_diagnostic["patient_diagnostic_id"].nunique()
    ],
    "unique_tests_used": [
        patient_diagnostic["test_id"].nunique()
    ],
    "unique_diagnostic_patients": [
        patient_diagnostic["admission_id"].nunique()
    ]
})


# 6. Disease summary
disease_summary = pd.DataFrame({
    "total_diseases": [
        disease["disease_id"].nunique()
    ],
    "disease_categories": [
        disease["disease_category"].nunique()
    ]
})


# 7. Combine all summaries
final_table_4 = pd.concat(
    [
        billing_summary,
        billing_detail_summary,
        insurance_summary,
        prescription_summary,
        diagnostic_summary,
        disease_summary
    ],
    axis=1
)


# 8. Round decimal values
final_table_4 = final_table_4.round(2)


print("===== FINAL TABLE 4 - BILLING, INSURANCE & CLINICAL UTILIZATION =====")

display(final_table_4)

===== FINAL TABLE 4 - BILLING, INSURANCE & CLINICAL UTILIZATION =====

,total_bills,total_billed_amount,insurance_covered_amount,patient_payable_amount,total_billing_details,total_charge_amount,insured_patients,insurance_policies,insurance_providers,average_coverage_percentage,total_prescriptions,unique_drugs_prescribed,average_prescription_duration_days,total_diagnostic_tests,unique_tests_used,unique_diagnostic_patients,total_diseases,disease_categories
0,45000,1684246109,976880867.0,707365242.0,112402,1478880266,18000,21613,50,70.07,73109,250,8.51,63269,9,31512,20,11

In [50]:
# ==========================================
# FINAL TABLE 4 - COLUMN WISE OUTPUT
# ==========================================

print("===== FINAL TABLE 4 - COLUMN WISE =====\n")

for column in final_table_4.columns:
    print(f"{column}:")
    print(final_table_4[column].iloc[0])
    print("-" * 50)

===== FINAL TABLE 4 - COLUMN WISE =====

total_bills:
45000
--------------------------------------------------
total_billed_amount:
1684246109
--------------------------------------------------
insurance_covered_amount:
976880867.0
--------------------------------------------------
patient_payable_amount:
707365242.0
--------------------------------------------------
total_billing_details:
112402
--------------------------------------------------
total_charge_amount:
1478880266
--------------------------------------------------
insured_patients:
18000
--------------------------------------------------
insurance_policies:
21613
--------------------------------------------------
insurance_providers:
50
--------------------------------------------------
average_coverage_percentage:
70.07
--------------------------------------------------
total_prescriptions:
73109
--------------------------------------------------
unique_drugs_prescribed:
250
--------------------------------------------------
average_prescription_duration_days:
8.51
--------------------------------------------------
total_diagnostic_tests:
63269
--------------------------------------------------
unique_tests_used:
9
--------------------------------------------------
unique_diagnostic_patients:
31512
--------------------------------------------------
total_diseases:
20
--------------------------------------------------
disease_categories:
11
--------------------------------------------------

In [51]:
# ==========================================
# SAVE 4 FINAL TABLES TO EXCEL
# ==========================================

output_file = "HMIS_Final_4_Tables.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

    hospital_overview.to_excel(
        writer,
        sheet_name="Hospital Overview",
        index=False
    )

    patient_clinical.to_excel(
        writer,
        sheet_name="Patient Clinical",
        index=False
    )

    department_resource.to_excel(
        writer,
        sheet_name="Department Resource",
        index=False
    )

    final_table_4.to_excel(
        writer,
        sheet_name="Billing Clinical",
        index=False
    )

print("File saved successfully:")
print(output_file)

File saved successfully:
HMIS_Final_4_Tables.xlsx

In [52]:
# ==========================================
# SAVE ALL 4 FINAL TABLES SEPARATELY
# ==========================================

# FINAL TABLE 1
hospital_overview.to_excel(
    "Final_Table_1_Hospital_Overview.xlsx",
    index=False
)

# FINAL TABLE 2
patient_clinical.to_excel(
    "Final_Table_2_Patient_Clinical.xlsx",
    index=False
)

# FINAL TABLE 3
department_resource.to_excel(
    "Final_Table_3_Department_Resource.xlsx",
    index=False
)

# FINAL TABLE 4
final_table_4.to_excel(
    "Final_Table_4_Billing_Clinical.xlsx",
    index=False
)

print("===== 4 FINAL TABLES SAVED =====")
print("1. Final_Table_1_Hospital_Overview.xlsx")
print("2. Final_Table_2_Patient_Clinical.xlsx")
print("3. Final_Table_3_Department_Resource.xlsx")
print("4. Final_Table_4_Billing_Clinical.xlsx")

===== 4 FINAL TABLES SAVED =====
1. Final_Table_1_Hospital_Overview.xlsx
2. Final_Table_2_Patient_Clinical.xlsx
3. Final_Table_3_Department_Resource.xlsx
4. Final_Table_4_Billing_Clinical.xlsx

In [53]:
# ==========================================
# MEMBER 7 - FINAL TABLES
# STEP 0: CHECK ALL SOURCE DATASETS
# ==========================================

source_tables = {
    "admission": admission,
    "bed": bed,
    "billing": billing,
    "billing_detail": billing_detail,
    "department": department,
    "diagnostic_test": diagnostic_test,
    "disease": disease,
    "doctor": doctor,
    "drug": drug,
    "drug_inventory": drug_inventory,
    "drug_manufacturer": drug_manufacturer,
    "employee": employee,
    "insurance_provider": insurance_provider,
    "patient": patient,
    "patient_diagnostic": patient_diagnostic,
    "patient_insurance": patient_insurance,
    "prescription": prescription,
    "staff_assignment": staff_assignment,
    "ward": ward,
    "bed_management": bed_management,
    "readmission": readmission
}

print("===== ALL 22 SOURCE DATASETS =====\n")

for name, df in source_tables.items():
    print(f"{name:<25} -> {df.shape[0]:>8} rows × {df.shape[1]:>3} columns")

===== ALL 22 SOURCE DATASETS =====

admission                 ->    45000 rows ×  11 columns
bed                       ->      415 rows ×   4 columns
billing                   ->    45000 rows ×   8 columns
billing_detail            ->   112402 rows ×   5 columns
department                ->       11 rows ×   5 columns
diagnostic_test           ->        9 rows ×   5 columns
disease                   ->       20 rows ×   3 columns
doctor                    ->       98 rows ×   5 columns
drug                      ->      250 rows ×   6 columns
drug_inventory            ->      250 rows ×   6 columns
drug_manufacturer         ->      300 rows ×   5 columns
employee                  ->      500 rows ×   7 columns
insurance_provider        ->       50 rows ×   5 columns
patient                   ->    30000 rows ×   6 columns
patient_diagnostic        ->    63269 rows ×   6 columns
patient_insurance         ->    21617 rows ×   7 columns
prescription              ->    73109 rows ×   6 columns
staff_assignment          ->      207 rows ×   4 columns
ward                      ->       27 rows ×   5 columns
bed_management            ->     1000 rows ×  21 columns
readmission               ->    10000 rows ×  26 columns

In [54]:
print("HMIS Cleaned Data object exists:")

if "hmis_cleaned" in globals():
    print("YES -> hmis_cleaned", hmis_cleaned.shape)
elif "hmis_cleaned_data" in globals():
    print("YES -> hmis_cleaned_data", hmis_cleaned_data.shape)
else:
    print("NO separate DataFrame found")

HMIS Cleaned Data object exists:
NO separate DataFrame found

In [55]:
# ==========================================
# LOAD HMIS CLEANED DATA
# ==========================================

import pandas as pd

hmis_cleaned = pd.read_excel("HMIS_Cleaned_Data.xlsx")

print("===== HMIS CLEANED DATA =====")
print("Rows:", hmis_cleaned.shape[0])
print("Columns:", hmis_cleaned.shape[1])

print("\nColumns:")
print(hmis_cleaned.columns.tolist())

===== HMIS CLEANED DATA =====
Rows: 30000
Columns: 6

Columns:
['patient_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number']

In [56]:
print("\nFirst 5 rows:")
display(hmis_cleaned.head())

First 5 rows:

,patient_id,gender,date_of_birth,blood_group,city,contact_number
0,1,FEMALE,1987-08-24,O-,East Stephanieberg,+1-792-342-0981
1,2,MALE,1960-05-18,A-,Manuelbury,793-725-0800
2,3,MALE,1955-04-24,A-,Lake Susanchester,+1-330-617-3749x232
3,4,MALE,2004-06-16,B-,South Leslieburgh,426-611-6235x07684
4,5,MALE,1977-07-22,A-,Lopezchester,(215)330-2831x0821

In [57]:
# ==========================================
# FINAL TABLE 1 - HOSPITAL OVERVIEW
# STEP 1: CHECK REQUIRED COLUMNS
# ==========================================

tables_to_check = {
    "admission": admission,
    "patient": patient,
    "department": department,
    "ward": ward,
    "bed": bed,
    "disease": disease,
    "billing": billing
}

for name, df in tables_to_check.items():
    print("\n" + "=" * 50)
    print(name.upper())
    print("=" * 50)
    print(df.columns.tolist())

==================================================
ADMISSION
==================================================
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id', 'length_of_stay']

==================================================
PATIENT
==================================================
['patient_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number']

==================================================
DEPARTMENT
==================================================
['department_id', 'department_name', 'department_type', 'floor_number', 'status']

==================================================
WARD
==================================================
['ward_id', 'ward_name', 'ward_type', 'total_beds', 'department_id']

==================================================
BED
==================================================
['bed_id', 'bed_number', 'bed_status', 'ward_id']

==================================================
DISEASE
==================================================
['disease_id', 'disease_name', 'disease_category']

==================================================
BILLING
==================================================
['bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode', 'admission_id']

In [58]:
# ==========================================
# FINAL TABLE 1 - HOSPITAL OVERVIEW
# INTEGRATED ADMISSION-LEVEL TABLE
# ==========================================

# Start with admission
hospital_overview = admission.copy()

# Patient information
hospital_overview = hospital_overview.merge(
    patient[
        ["patient_id", "gender", "date_of_birth", "blood_group", "city"]
    ],
    on="patient_id",
    how="left"
)

# Department information
hospital_overview = hospital_overview.merge(
    department[
        ["department_id", "department_name",
         "department_type", "floor_number", "status"]
    ],
    on="department_id",
    how="left"
)

# Ward information
hospital_overview = hospital_overview.merge(
    ward[
        ["ward_id", "ward_name", "ward_type", "total_beds"]
    ],
    on="ward_id",
    how="left"
)

# Bed information
hospital_overview = hospital_overview.merge(
    bed[
        ["bed_id", "bed_number", "bed_status"]
    ],
    on="bed_id",
    how="left"
)

# Disease information
hospital_overview = hospital_overview.merge(
    disease[
        ["disease_id", "disease_name", "disease_category"]
    ],
    on="disease_id",
    how="left"
)

# Billing information
hospital_overview = hospital_overview.merge(
    billing[
        ["bill_id", "bill_date", "total_amount",
         "insurance_covered_amount",
         "patient_payable_amount",
         "payment_status", "payment_mode"]
    ],
    on="admission_id",
    how="left"
)

print("===== FINAL TABLE 1 - HOSPITAL OVERVIEW =====")
print("Rows:", hospital_overview.shape[0])
print("Columns:", hospital_overview.shape[1])

print("\nColumns:")
print(hospital_overview.columns.tolist())

print("\nFirst 5 rows:")
display(hospital_overview.head())

KeyError: 'admission_id'

In [59]:
print("BILLING COLUMNS:")
print(billing.columns.tolist())

print("\nHOSPITAL OVERVIEW COLUMNS:")
print(hospital_overview.columns.tolist())

BILLING COLUMNS:
['bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode', 'admission_id']

HOSPITAL OVERVIEW COLUMNS:
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id', 'length_of_stay', 'gender', 'date_of_birth', 'blood_group', 'city', 'department_name', 'department_type', 'floor_number', 'status', 'ward_name', 'ward_type', 'total_beds', 'bed_number', 'bed_status', 'disease_name', 'disease_category']

In [60]:
print("\nBilling shape:", billing.shape)
print("Billing admission_id nulls:",
      billing["admission_id"].isna().sum())

print("\nUnique billing admission IDs:",
      billing["admission_id"].nunique())

print("\nUnique admission IDs:",
      admission["admission_id"].nunique())

Billing shape: (45000, 8)
Billing admission_id nulls: 0

Unique billing admission IDs: 45000

Unique admission IDs: 45000

In [61]:
# ==========================================
# ADD BILLING INFORMATION
# ==========================================

hospital_overview = hospital_overview.merge(
    billing[
        [
            "admission_id",
            "bill_id",
            "bill_date",
            "total_amount",
            "insurance_covered_amount",
            "patient_payable_amount",
            "payment_status",
            "payment_mode"
        ]
    ],
    on="admission_id",
    how="left",
    validate="one_to_one"
)

print("===== HOSPITAL OVERVIEW TABLE =====")
print("Rows:", hospital_overview.shape[0])
print("Columns:", hospital_overview.shape[1])

print("\nColumns:")
print(hospital_overview.columns.tolist())

print("\nFirst 5 rows:")
display(hospital_overview.head())

===== HOSPITAL OVERVIEW TABLE =====
Rows: 45000
Columns: 33

Columns:
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id', 'length_of_stay', 'gender', 'date_of_birth', 'blood_group', 'city', 'department_name', 'department_type', 'floor_number', 'status', 'ward_name', 'ward_type', 'total_beds', 'bed_number', 'bed_status', 'disease_name', 'disease_category', 'bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode']

First 5 rows:

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,...,bed_status,disease_name,disease_category,bill_id,bill_date,total_amount,insurance_covered_amount,patient_payable_amount,payment_status,payment_mode
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,...,Available,Anemia,Hematological,1,2025-05-26,68483,61634.7,6848.3,Paid,Insurance
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,...,Available,Fracture Femur,Orthopedic,2,2023-11-19,70917,35458.5,35458.5,Paid,Insurance
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,...,Available,Chronic Obstructive Pulmonary Disease,Respiratory,3,2023-02-20,28137,25323.3,2813.7,Pending,Insurance
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,...,Available,Acute Myocardial Infarction,Cardiac,4,2021-09-01,80665,64532.0,16133.0,Pending,Insurance
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,...,Available,Hypertension,Cardiac,5,2021-07-13,54920,27460.0,27460.0,Pending,Insurance

In [62]:
# ==========================================
# FINAL TABLE 1 - VALIDATION
# ==========================================

print("===== HOSPITAL OVERVIEW VALIDATION =====")

print("Original Admission Rows:", len(admission))
print("Final Table Rows:", len(hospital_overview))

print("\nOriginal Unique Admissions:",
      admission["admission_id"].nunique())

print("Final Unique Admissions:",
      hospital_overview["admission_id"].nunique())

print("\nDuplicate Admission IDs in Final Table:",
      hospital_overview["admission_id"].duplicated().sum())

print("\nMissing Admission IDs:",
      hospital_overview["admission_id"].isna().sum())

===== HOSPITAL OVERVIEW VALIDATION =====
Original Admission Rows: 45000
Final Table Rows: 45000

Original Unique Admissions: 45000
Final Unique Admissions: 45000

Duplicate Admission IDs in Final Table: 0

Missing Admission IDs: 0

In [63]:
# Final Table 1
print("Shape:", hospital_overview.shape)

display(hospital_overview.head(20))

Shape: (45000, 33)

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,...,bed_status,disease_name,disease_category,bill_id,bill_date,total_amount,insurance_covered_amount,patient_payable_amount,payment_status,payment_mode
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,...,Available,Anemia,Hematological,1,2025-05-26,68483,61634.7,6848.3,Paid,Insurance
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,...,Available,Fracture Femur,Orthopedic,2,2023-11-19,70917,35458.5,35458.5,Paid,Insurance
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,...,Available,Chronic Obstructive Pulmonary Disease,Respiratory,3,2023-02-20,28137,25323.3,2813.7,Pending,Insurance
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,...,Available,Acute Myocardial Infarction,Cardiac,4,2021-09-01,80665,64532.0,16133.0,Pending,Insurance
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,...,Available,Hypertension,Cardiac,5,2021-07-13,54920,27460.0,27460.0,Pending,Insurance
5,6,2021-08-01,2021-08-08,Elective,Discharged,21044,3,11,143,14,...,Available,Hernia,Surgical,6,2025-08-31,71521,64368.9,7152.1,Pending,Insurance
6,7,2020-06-30,2020-07-01,Emergency,Discharged,10798,2,6,79,19,...,Available,COVID-19,Infectious,7,2022-04-27,13951,0.0,13951.0,Pending,Card
7,8,2025-07-15,2025-07-18,Emergency,Discharged,15425,4,19,276,18,...,Available,Viral Fever,Infectious,8,2021-04-07,46293,0.0,46293.0,Pending,Card
8,9,2024-11-25,2024-11-28,Emergency,Discharged,13814,1,4,55,16,...,Available,Neonatal Jaundice,Pediatric,9,2020-03-28,21830,0.0,21830.0,Pending,Card
9,10,2020-05-26,2020-05-30,Elective,Discharged,1654,1,2,11,2,...,Available,Stroke,Neurological,10,2025-08-09,18606,0.0,18606.0,Pending,Cash
10,11,2021-05-17,2021-05-24,Elective,Discharged,27934,6,25,369,15,...,Available,Pneumonia,Pediatric,11,2023-11-18,43829,0.0,43829.0,Paid,Cash
11,12,2023-01-03,2023-01-09,Elective,Discharged,21107,5,23,334,11,...,Available,Fracture Femur,Orthopedic,12,2024-11-30,81510,65208.0,16302.0,Paid,Insurance
12,13,2022-05-31,2022-06-04,Elective,Discharged,20420,2,10,140,4,...,Available,Sepsis,Infectious,13,2024-09-04,24500,12250.0,12250.0,Pending,Insurance
13,14,2020-08-17,2020-08-20,Emergency,Discharged,9345,2,7,86,4,...,Available,Sepsis,Infectious,14,2020-06-20,79445,71500.5,7944.5,Paid,Insurance
14,15,2024-05-11,2024-05-13,Emergency,Discharged,21042,3,11,157,16,...,Available,Neonatal Jaundice,Pediatric,15,2023-05-05,27295,13647.5,13647.5,Pending,Insurance
15,16,2023-11-24,2023-11-27,Elective,Discharged,22916,4,16,240,17,...,Available,Urinary Tract Infection,Infectious,16,2022-08-10,12310,8617.0,3693.0,Paid,Insurance
16,17,2020-03-18,2020-03-28,Elective,Discharged,21250,5,23,338,15,...,Available,Pneumonia,Pediatric,17,2025-10-07,32813,0.0,32813.0,Pending,UPI
17,18,2023-10-18,2023-10-21,Emergency,Discharged,25308,5,21,308,16,...,Available,Neonatal Jaundice,Pediatric,18,2020-03-08,35289,31760.1,3528.9,Paid,Insurance
18,19,2021-03-25,2021-03-31,Elective,Discharged,6947,5,23,343,4,...,Available,Sepsis,Infectious,19,2025-05-07,72046,57636.8,14409.2,Paid,Insurance
19,20,2021-07-10,2021-07-17,Elective,Discharged,24098,2,10,130,19,...,Available,COVID-19,Infectious,20,2025-04-24,40244,36219.6,4024.4,Pending,Insurance

In [64]:
# ==========================================
# FINAL TABLE 2 - PATIENT FLOW
# STEP 1: CHECK READMISSION RELATIONSHIP
# ==========================================

print("===== READMISSION DATA =====")

print("Readmission Rows:", len(readmission))

print("Unique Patient IDs:",
      readmission["patient_id"].nunique())

print("Duplicate Patient IDs:",
      readmission["patient_id"].duplicated().sum())

print("\nAdmission Patient IDs:",
      admission["patient_id"].nunique())

print("Readmission columns:")
print(readmission.columns.tolist())

===== READMISSION DATA =====
Readmission Rows: 10000
Unique Patient IDs: 6022
Duplicate Patient IDs: 3978

Admission Patient IDs: 23275
Readmission columns:
['hospital_name', 'Admission_date', 'hospital_id', 'hospital_beds_available', 'occupied_beds', 'hospital_ward', 'patient_id', 'patient_gender', 'patient_age', 'patient_race', 'patient_sat_score', 'patient_first_initial', 'patient_last_name', 'patient_waittime', 'department_referral', 'time_slot', 'doctor_id', 'doctor_name', 'doctor_specialty', 'patient_assigned_doctor', 'patient_checkin_date', 'patient_checkout_date', 'patient_disease', 'patient_length_of_stay', 'discharge_status', 'readmission']

In [65]:
# ==========================================
# FINAL TABLE 2 - PATIENT FLOW
# STEP 2: CREATE PATIENT-LEVEL READMISSION SUMMARY
# ==========================================

readmission_patient_summary = (
    readmission
    .groupby("patient_id")
    .agg(
        readmission_records=("patient_id", "size"),
        total_readmissions=("readmission", "sum"),
        average_wait_time=("patient_waittime", "mean"),
        average_satisfaction=("patient_sat_score", "mean"),
        average_length_of_stay=("patient_length_of_stay", "mean")
    )
    .reset_index()
)

print("===== READMISSION PATIENT SUMMARY =====")
print("Rows:", readmission_patient_summary.shape[0])
print("Columns:", readmission_patient_summary.shape[1])

print("\nColumns:")
print(readmission_patient_summary.columns.tolist())

print("\nFirst 10 rows:")
display(readmission_patient_summary.head(10))

===== READMISSION PATIENT SUMMARY =====
Rows: 6022
Columns: 6

Columns:
['patient_id', 'readmission_records', 'total_readmissions', 'average_wait_time', 'average_satisfaction', 'average_length_of_stay']

First 10 rows:

,patient_id,readmission_records,total_readmissions,average_wait_time,average_satisfaction,average_length_of_stay
0,1000,1,0,105.0,890.000000,18.000000
1,1001,1,1,90.0,1510.000000,11.000000
2,1002,2,2,97.5,1035.000000,15.500000
3,1003,1,0,60.0,940.000000,30.000000
4,1005,1,0,60.0,450.000000,27.000000
5,1006,3,3,70.0,623.333333,11.333333
6,1008,2,0,97.5,685.000000,15.000000
7,1009,2,0,105.0,1045.000000,25.500000
8,1010,1,0,15.0,1260.000000,25.000000
9,1011,1,1,15.0,700.000000,15.000000

In [66]:
# ==========================================
# FINAL TABLE 2 - PATIENT FLOW
# STEP 3: CREATE BASE TABLE
# ==========================================

patient_flow = admission.copy()

# Patient information
patient_flow = patient_flow.merge(
    patient[
        [
            "patient_id",
            "gender",
            "date_of_birth",
            "blood_group",
            "city"
        ]
    ],
    on="patient_id",
    how="left",
    validate="many_to_one"
)

# Department information
patient_flow = patient_flow.merge(
    department[
        [
            "department_id",
            "department_name",
            "department_type"
        ]
    ],
    on="department_id",
    how="left",
    validate="many_to_one"
)

# Ward information
patient_flow = patient_flow.merge(
    ward[
        [
            "ward_id",
            "ward_name",
            "ward_type"
        ]
    ],
    on="ward_id",
    how="left",
    validate="many_to_one"
)

# Disease information
patient_flow = patient_flow.merge(
    disease[
        [
            "disease_id",
            "disease_name",
            "disease_category"
        ]
    ],
    on="disease_id",
    how="left",
    validate="many_to_one"
)

print("===== PATIENT FLOW BASE TABLE =====")
print("Rows:", patient_flow.shape[0])
print("Columns:", patient_flow.shape[1])

print("\nColumns:")
print(patient_flow.columns.tolist())

print("\nFirst 5 rows:")
display(patient_flow.head())

===== PATIENT FLOW BASE TABLE =====
Rows: 45000
Columns: 21

Columns:
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id', 'length_of_stay', 'gender', 'date_of_birth', 'blood_group', 'city', 'department_name', 'department_type', 'ward_name', 'ward_type', 'disease_name', 'disease_category']

First 5 rows:

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,...,gender,date_of_birth,blood_group,city,department_name,department_type,ward_name,ward_type,disease_name,disease_category
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,...,Male,1954-11-02,A-,North Dorisland,Internal Medicine,Clinical,Internal Medicine Ward 1,Private,Anemia,Hematological
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,...,Female,1988-02-25,AB+,West Susan,Orthopedics,Clinical,Orthopedics Ward 1,General,Fracture Femur,Orthopedic
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,...,Male,1944-03-02,A-,North Erik,Emergency,Clinical,Emergency Ward 2,Private,Chronic Obstructive Pulmonary Disease,Respiratory
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,...,Male,2017-08-19,A+,Maldonadoton,Internal Medicine,Clinical,Internal Medicine Ward 5,General,Acute Myocardial Infarction,Cardiac
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,...,Male,2015-05-06,A+,Port Stephanie,Surgery,Clinical,Surgery Ward 1,General,Hypertension,Cardiac

In [67]:
# ==========================================
# FINAL TABLE 2 - PATIENT FLOW
# STEP 4: ADD READMISSION SUMMARY
# ==========================================

patient_flow = patient_flow.merge(
    readmission_patient_summary[
        [
            "patient_id",
            "readmission_records",
            "total_readmissions",
            "average_wait_time",
            "average_satisfaction",
            "average_length_of_stay"
        ]
    ],
    on="patient_id",
    how="left",
    validate="many_to_one"
)

print("===== PATIENT FLOW WITH READMISSION =====")
print("Rows:", patient_flow.shape[0])
print("Columns:", patient_flow.shape[1])

print("\nColumns:")
print(patient_flow.columns.tolist())

print("\nFirst 5 rows:")
display(patient_flow.head())

===== PATIENT FLOW WITH READMISSION =====
Rows: 45000
Columns: 26

Columns:
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id', 'length_of_stay', 'gender', 'date_of_birth', 'blood_group', 'city', 'department_name', 'department_type', 'ward_name', 'ward_type', 'disease_name', 'disease_category', 'readmission_records', 'total_readmissions', 'average_wait_time', 'average_satisfaction', 'average_length_of_stay']

First 5 rows:

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,...,department_type,ward_name,ward_type,disease_name,disease_category,readmission_records,total_readmissions,average_wait_time,average_satisfaction,average_length_of_stay
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,...,Clinical,Internal Medicine Ward 1,Private,Anemia,Hematological,NaN,NaN,NaN,NaN,NaN
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,...,Clinical,Orthopedics Ward 1,General,Fracture Femur,Orthopedic,1.0,0.0,60.0,1120.0,30.0
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,...,Clinical,Emergency Ward 2,Private,Chronic Obstructive Pulmonary Disease,Respiratory,NaN,NaN,NaN,NaN,NaN
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,...,Clinical,Internal Medicine Ward 5,General,Acute Myocardial Infarction,Cardiac,NaN,NaN,NaN,NaN,NaN
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,...,Clinical,Surgery Ward 1,General,Hypertension,Cardiac,NaN,NaN,NaN,NaN,NaN

In [68]:
# ==========================================
# FINAL TABLE 2 - PATIENT FLOW VALIDATION
# ==========================================

print("===== PATIENT FLOW VALIDATION =====")

print("Original Admission Rows:", len(admission))
print("Final Patient Flow Rows:", len(patient_flow))

print("\nOriginal Unique Admissions:",
      admission["admission_id"].nunique())

print("Final Unique Admissions:",
      patient_flow["admission_id"].nunique())

print("\nDuplicate Admission IDs:",
      patient_flow["admission_id"].duplicated().sum())

print("\nMissing Admission IDs:",
      patient_flow["admission_id"].isna().sum())

print("\nPatients with Readmission Data:",
      patient_flow["readmission_records"].notna().sum())

print("Patients without Readmission Data:",
      patient_flow["readmission_records"].isna().sum())

===== PATIENT FLOW VALIDATION =====
Original Admission Rows: 45000
Final Patient Flow Rows: 45000

Original Unique Admissions: 45000
Final Unique Admissions: 45000

Duplicate Admission IDs: 0

Missing Admission IDs: 0

Patients with Readmission Data: 9232
Patients without Readmission Data: 35768

In [69]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT ANALYTICS
# STEP 1: DEPARTMENT SUMMARY
# ==========================================

department_analytics = (
    patient_flow
    .groupby(
        [
            "department_id",
            "department_name",
            "department_type"
        ],
        as_index=False
    )
    .agg(
        total_admissions=("admission_id", "nunique"),
        unique_patients=("patient_id", "nunique"),
        average_length_of_stay=("length_of_stay", "mean")
    )
)

print("===== DEPARTMENT ANALYTICS BASE =====")
print("Rows:", department_analytics.shape[0])
print("Columns:", department_analytics.shape[1])

print("\nColumns:")
print(department_analytics.columns.tolist())

print("\nDepartment Summary:")
display(department_analytics)

===== DEPARTMENT ANALYTICS BASE =====
Rows: 6
Columns: 6

Columns:
['department_id', 'department_name', 'department_type', 'total_admissions', 'unique_patients', 'average_length_of_stay']

Department Summary:

,department_id,department_name,department_type,total_admissions,unique_patients,average_length_of_stay
0,1,Emergency,Clinical,8777,7578,4.692492
1,2,Internal Medicine,Clinical,7695,6737,4.656140
2,3,Surgery,Clinical,10126,8594,4.674798
3,4,Pediatrics,Clinical,8438,7388,4.691752
4,5,Orthopedics,Clinical,5924,5344,4.677920
5,6,ICU,Clinical,4040,3759,9.980693

In [70]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT ANALYTICS
# STEP 2: ADD READMISSION METRICS
# ==========================================

readmission_dept = (
    patient_flow
    .groupby(
        [
            "department_id",
            "department_name"
        ],
        as_index=False
    )
    .agg(
        total_readmission_records=("total_readmissions", "sum"),
        patients_with_readmission_data=("readmission_records", "count")
    )
)

# Readmission rate
readmission_dept["readmission_rate"] = (
    readmission_dept["total_readmission_records"]
    / readmission_dept["patients_with_readmission_data"]
    * 100
)

print("===== DEPARTMENT READMISSION SUMMARY =====")
display(readmission_dept)

===== DEPARTMENT READMISSION SUMMARY =====

,department_id,department_name,total_readmission_records,patients_with_readmission_data,readmission_rate
0,1,Emergency,1230.0,1770,69.491525
1,2,Internal Medicine,1074.0,1569,68.451243
2,3,Surgery,1293.0,2006,64.456630
3,4,Pediatrics,1211.0,1790,67.653631
4,5,Orthopedics,819.0,1205,67.966805
5,6,ICU,619.0,892,69.394619

In [71]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT ANALYTICS
# STEP 3: CORRECT READMISSION METRICS
# ==========================================

department_readmission = (
    readmission
    .groupby("department_referral", as_index=False)
    .agg(
        readmission_records=("readmission", "count"),
        total_readmitted=("readmission", "sum")
    )
)

department_readmission["readmission_rate"] = (
    department_readmission["total_readmitted"]
    / department_readmission["readmission_records"]
    * 100
)

print("===== CORRECT DEPARTMENT READMISSION =====")
display(department_readmission)

===== CORRECT DEPARTMENT READMISSION =====

,department_referral,readmission_records,total_readmitted,readmission_rate
0,Allergy and Immunology,359,157,43.732591
1,Cardiology,374,161,43.048128
2,Cardiology or Internal Medicine,346,152,43.930636
3,Dermatology,339,132,38.938053
4,Endocrinology,347,139,40.057637
5,Gastroenterology,1094,467,42.687386
6,Hepatology,367,162,44.141689
7,Hepatology or Gastroenterology,371,138,37.196765
8,Infectious Disease,362,143,39.502762
9,Infectious Disease or Internal Medicine,700,291,41.571429
10,Nephrology,331,125,37.764350
11,Neurology,1790,741,41.396648
12,Oncology,349,138,39.541547
13,Psychiatry,730,325,44.520548
14,Pulmonology,354,132,37.288136
15,Pulmonology or Allergy and Immunology,380,159,41.842105
16,Pulmonology or Infectious Disease,336,135,40.178571
17,Rheumatology,720,294,40.833333
18,Urology or Nephrology,351,151,43.019943

In [72]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT ANALYTICS
# STEP 4: CHECK DEPARTMENT NAME MATCHING
# ==========================================

print("===== HMIS DEPARTMENTS =====")
print(department_analytics["department_name"].tolist())

print("\n===== READMISSION DEPARTMENTS =====")
print(department_readmission["department_referral"].tolist())

# Exact department name matches
matched_departments = set(
    department_analytics["department_name"]
) & set(
    department_readmission["department_referral"]
)

print("\n===== EXACT MATCHES =====")
print(matched_departments)

print("\nNumber of Exact Matches:",
      len(matched_departments))

===== HMIS DEPARTMENTS =====
['Emergency', 'Internal Medicine', 'Surgery', 'Pediatrics', 'Orthopedics', 'ICU']

===== READMISSION DEPARTMENTS =====
['Allergy and Immunology', 'Cardiology', 'Cardiology or Internal Medicine', 'Dermatology', 'Endocrinology', 'Gastroenterology', 'Hepatology', 'Hepatology or Gastroenterology', 'Infectious Disease', 'Infectious Disease or Internal Medicine', 'Nephrology', 'Neurology', 'Oncology', 'Psychiatry', 'Pulmonology', 'Pulmonology or Allergy and Immunology', 'Pulmonology or Infectious Disease', 'Rheumatology', 'Urology or Nephrology']

===== EXACT MATCHES =====
set()

Number of Exact Matches: 0

In [73]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT ANALYTICS
# STEP 5: ADD DEPARTMENT BED RESOURCES
# ==========================================

department_beds = (
    ward
    .groupby("department_id", as_index=False)
    .agg(
        total_beds=("total_beds", "sum"),
        total_wards=("ward_id", "nunique")
    )
)

print("===== DEPARTMENT BED RESOURCES =====")
display(department_beds)

===== DEPARTMENT BED RESOURCES =====

   department_id  total_beds  total_wards
0              1          75            5
1              2          65            5
2              3          90            5
3              4          70            5
4              5          50            3
5              6          65            4

In [74]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT ANALYTICS
# STEP 6: MERGE BED RESOURCES
# ==========================================

department_analytics = department_analytics.merge(
    department_beds,
    on="department_id",
    how="left",
    validate="one_to_one"
)

print("===== DEPARTMENT ANALYTICS =====")
print("Rows:", department_analytics.shape[0])
print("Columns:", department_analytics.shape[1])

print("\nColumns:")
print(department_analytics.columns.tolist())

print("\nFinal Department Analytics:")
display(department_analytics)

===== DEPARTMENT ANALYTICS =====
Rows: 6
Columns: 8

Columns:
['department_id', 'department_name', 'department_type', 'total_admissions', 'unique_patients', 'average_length_of_stay', 'total_beds', 'total_wards']

Final Department Analytics:

,department_id,department_name,department_type,total_admissions,unique_patients,average_length_of_stay,total_beds,total_wards
0,1,Emergency,Clinical,8777,7578,4.692492,75,5
1,2,Internal Medicine,Clinical,7695,6737,4.656140,65,5
2,3,Surgery,Clinical,10126,8594,4.674798,90,5
3,4,Pediatrics,Clinical,8438,7388,4.691752,70,5
4,5,Orthopedics,Clinical,5924,5344,4.677920,50,3
5,6,ICU,Clinical,4040,3759,9.980693,65,4

In [75]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT ANALYTICS
# STEP 7: DOCTOR & STAFF RESOURCE SUMMARY
# ==========================================

# Doctor -> Employee -> Department
doctor_department = doctor.merge(
    employee[
        ["employee_id", "department_id"]
    ],
    on="employee_id",
    how="left",
    validate="many_to_one"
)

# Department-wise doctor count
department_doctors = (
    doctor_department
    .groupby("department_id", as_index=False)
    .agg(
        total_doctors=("doctor_id", "nunique")
    )
)

# Department-wise employee/staff count
department_staff = (
    employee
    .groupby("department_id", as_index=False)
    .agg(
        total_staff=("employee_id", "nunique")
    )
)

print("===== DEPARTMENT DOCTOR RESOURCES =====")
display(department_doctors)

print("\n===== DEPARTMENT STAFF RESOURCES =====")
display(department_staff)

===== DEPARTMENT DOCTOR RESOURCES =====

    department_id  total_doctors
0               1             13
1               2             11
2               3              5
3               4              3
4               5              8
5               6              9
6               7              9
7               8             11
8               9              9
9              10              9
10             11             11

===== DEPARTMENT STAFF RESOURCES =====

    department_id  total_staff
0               1           51
1               2           54
2               3           43
3               4           33
4               5           40
5               6           45
6               7           56
7               8           49
8               9           37
9              10           49
10             11           43

In [76]:
# ==========================================
# FINAL TABLE 3 - DEPARTMENT ANALYTICS
# STEP 8: ADD DOCTOR & STAFF RESOURCES
# ==========================================

department_analytics = department_analytics.merge(
    department_doctors,
    on="department_id",
    how="left",
    validate="one_to_one"
)

department_analytics = department_analytics.merge(
    department_staff,
    on="department_id",
    how="left",
    validate="one_to_one"
)

print("===== DEPARTMENT ANALYTICS WITH RESOURCES =====")

print("Rows:", department_analytics.shape[0])
print("Columns:", department_analytics.shape[1])

print("\nColumns:")
print(department_analytics.columns.tolist())

print("\nFinal Table 3 Preview:")
display(department_analytics)

===== DEPARTMENT ANALYTICS WITH RESOURCES =====
Rows: 6
Columns: 10

Columns:
['department_id', 'department_name', 'department_type', 'total_admissions', 'unique_patients', 'average_length_of_stay', 'total_beds', 'total_wards', 'total_doctors', 'total_staff']

Final Table 3 Preview:

,department_id,department_name,department_type,total_admissions,unique_patients,average_length_of_stay,total_beds,total_wards,total_doctors,total_staff
0,1,Emergency,Clinical,8777,7578,4.692492,75,5,13,51
1,2,Internal Medicine,Clinical,7695,6737,4.656140,65,5,11,54
2,3,Surgery,Clinical,10126,8594,4.674798,90,5,5,43
3,4,Pediatrics,Clinical,8438,7388,4.691752,70,5,3,33
4,5,Orthopedics,Clinical,5924,5344,4.677920,50,3,8,40
5,6,ICU,Clinical,4040,3759,9.980693,65,4,9,45

In [77]:
# ==========================================
# FINAL TABLE 3 - VALIDATION
# ==========================================

print("===== DEPARTMENT ANALYTICS VALIDATION =====")

print("HMIS Departments:", department["department_id"].nunique())

print("Final Table Departments:",
      department_analytics["department_id"].nunique())

print("\nDuplicate Department IDs:",
      department_analytics["department_id"].duplicated().sum())

print("\nMissing Department IDs:",
      department_analytics["department_id"].isna().sum())

print("\nTotal Admissions in Final Table:",
      department_analytics["total_admissions"].sum())

print("Original Admission Records:",
      len(admission))

print("\nTotal Beds in Final Table:",
      department_analytics["total_beds"].sum())

print("Total Wards in Final Table:",
      department_analytics["total_wards"].sum())

===== DEPARTMENT ANALYTICS VALIDATION =====
HMIS Departments: 11
Final Table Departments: 6

Duplicate Department IDs: 0

Missing Department IDs: 0

Total Admissions in Final Table: 45000
Original Admission Records: 45000

Total Beds in Final Table: 415
Total Wards in Final Table: 27

In [78]:
print("===== RESOURCE DATASETS =====")

for name in [
    "bed_management",
    "bed_resource_weekly",
    "staff_resource",
    "bed_management_resource",
    "drug_inventory",
    "staff_assignment",
    "doctor",
    "employee"
]:
    if name in globals():
        print(f"{name} -> {globals()[name].shape}")
    else:
        print(f"{name} -> NOT FOUND")

===== RESOURCE DATASETS =====
bed_management -> (1000, 21)
bed_resource_weekly -> (208, 8)
staff_resource -> (208, 8)
bed_management_resource -> (208, 14)
drug_inventory -> (250, 6)
staff_assignment -> (207, 4)
doctor -> (98, 5)
employee -> (500, 7)

In [79]:
# ==========================================
# FINAL TABLE 4 - RESOURCE UTILIZATION
# STEP 1: CHECK SOURCE COLUMNS
# ==========================================

resource_tables = [
    "bed_management",
    "bed_resource_weekly",
    "staff_resource",
    "bed_management_resource",
    "drug_inventory",
    "staff_assignment",
    "doctor",
    "employee"
]

for name in resource_tables:
    if name in globals():
        df = globals()[name]

        print("\n" + "=" * 50)
        print(name.upper())
        print("=" * 50)
        print("Shape:", df.shape)
        print("Columns:")
        print(df.columns.tolist())

==================================================
BED_MANAGEMENT
==================================================
Shape: (1000, 21)
Columns:
['Patient ID', 'Name', 'Age', 'Service', 'Arrival Date', 'Departure Date', 'Length of Stay (days)', 'Week', 'Admission Month', 'Patient Satisfaction Score', 'Available Beds (Wk)', 'Patients Requested (Wk)', 'Patients Admitted (Wk)', 'Patients Refused (Wk)', 'Avg Satisfaction (Wk)', 'Staff Morale (Wk)', 'Notable Event (Wk)', 'Dept Total Staff', 'Dept Doctor Count', 'Dept Nurse Count', 'Dept Nursing Assistant Count']

==================================================
BED_RESOURCE_WEEKLY
==================================================
Shape: (208, 8)
Columns:
['Service', 'Week', 'available_beds', 'patients_requested', 'patients_admitted', 'patients_refused', 'admission_rate', 'refusal_rate']

==================================================
STAFF_RESOURCE
==================================================
Shape: (208, 8)
Columns:
['Service', 'Week', 'total_staff', 'doctor_count', 'nurse_count', 'nursing_assistant_count', 'avg_satisfaction', 'staff_morale']

==================================================
BED_MANAGEMENT_RESOURCE
==================================================
Shape: (208, 14)
Columns:
['Service', 'Week', 'available_beds', 'patients_requested', 'patients_admitted', 'patients_refused', 'admission_rate', 'refusal_rate', 'total_staff', 'doctor_count', 'nurse_count', 'nursing_assistant_count', 'avg_satisfaction', 'staff_morale']

==================================================
DRUG_INVENTORY
==================================================
Shape: (250, 6)
Columns:
['inventory_id', 'current_stock', 'reorder_level', 'inventory_status', 'last_restock_date', 'drug_id']

==================================================
STAFF_ASSIGNMENT
==================================================
Shape: (207, 4)
Columns:
['assignment_id', 'employee_id', 'ward_id', 'shift']

==================================================
DOCTOR
==================================================
Shape: (98, 5)
Columns:
['doctor_id', 'employee_id', 'specialization', 'qualification', 'experience_years']

==================================================
EMPLOYEE
==================================================
Shape: (500, 7)
Columns:
['employee_id', 'employee_name', 'gender', 'role', 'employment_type', 'date_of_joining', 'department_id']

In [80]:
# ==========================================
# FINAL TABLE 4 - RESOURCE UTILIZATION
# ==========================================

resource_utilization = bed_management_resource.copy()

# Clean column names
resource_utilization.columns = [
    "service",
    "week",
    "available_beds",
    "patients_requested",
    "patients_admitted",
    "patients_refused",
    "admission_rate",
    "refusal_rate",
    "total_staff",
    "doctor_count",
    "nurse_count",
    "nursing_assistant_count",
    "avg_satisfaction",
    "staff_morale"
]

print("===== FINAL TABLE 4 - RESOURCE UTILIZATION =====")

print("Rows:", resource_utilization.shape[0])
print("Columns:", resource_utilization.shape[1])

print("\nColumns:")
print(resource_utilization.columns.tolist())

print("\nFirst 10 rows:")
display(resource_utilization.head(10))

===== FINAL TABLE 4 - RESOURCE UTILIZATION =====
Rows: 208
Columns: 14

Columns:
['service', 'week', 'available_beds', 'patients_requested', 'patients_admitted', 'patients_refused', 'admission_rate', 'refusal_rate', 'total_staff', 'doctor_count', 'nurse_count', 'nursing_assistant_count', 'avg_satisfaction', 'staff_morale']

First 10 rows:

,service,week,available_beds,patients_requested,patients_admitted,patients_refused,admission_rate,refusal_rate,total_staff,doctor_count,nurse_count,nursing_assistant_count,avg_satisfaction,staff_morale
0,ICU,1,22,217,154,63,70.97,29.03,32,6,18,8,84,91
1,ICU,2,16,28,28,0,100.00,0.00,32,6,18,8,79,85
2,ICU,3,20,105,100,5,95.24,4.76,32,6,18,8,82,89
3,ICU,4,20,126,120,6,95.24,4.76,32,6,18,8,64,85
4,ICU,5,22,13,13,0,100.00,0.00,32,6,18,8,73,88
5,ICU,6,14,48,48,0,100.00,0.00,32,6,18,8,87,51
6,ICU,7,21,141,63,78,44.68,55.32,32,6,18,8,72,83
7,ICU,8,12,70,70,0,100.00,0.00,32,6,18,8,76,98
8,ICU,9,11,140,77,63,55.00,45.00,32,6,18,8,97,73
9,ICU,10,13,8,8,0,100.00,0.00,32,6,18,8,91,56

In [81]:
# ==========================================
# FINAL TABLE 4 - VALIDATION
# ==========================================

print("===== RESOURCE UTILIZATION VALIDATION =====")

print("Total Rows:", len(resource_utilization))

print("Unique Services:",
      resource_utilization["service"].nunique())

print("Unique Weeks:",
      resource_utilization["week"].nunique())

print("Duplicate Service-Week combinations:",
      resource_utilization.duplicated(
          subset=["service", "week"]
      ).sum())

print("\nMissing Values:")
print(resource_utilization.isna().sum())

print("\nAdmission Rate Range:",
      resource_utilization["admission_rate"].min(),
      "to",
      resource_utilization["admission_rate"].max())

print("\nRefusal Rate Range:",
      resource_utilization["refusal_rate"].min(),
      "to",
      resource_utilization["refusal_rate"].max())

print("\n===== FINAL TABLE 4 SAMPLE =====")
display(resource_utilization.head())

===== RESOURCE UTILIZATION VALIDATION =====
Total Rows: 208
Unique Services: 4
Unique Weeks: 52
Duplicate Service-Week combinations: 0

Missing Values:
service                    0
week                       0
available_beds             0
patients_requested         0
patients_admitted          0
patients_refused           0
admission_rate             0
refusal_rate               0
total_staff                0
doctor_count               0
nurse_count                0
nursing_assistant_count    0
avg_satisfaction           0
staff_morale               0
dtype: int64

Admission Rate Range: 6.44 to 100.0

Refusal Rate Range: 0.0 to 93.56

===== FINAL TABLE 4 SAMPLE =====

,service,week,available_beds,patients_requested,patients_admitted,patients_refused,admission_rate,refusal_rate,total_staff,doctor_count,nurse_count,nursing_assistant_count,avg_satisfaction,staff_morale
0,ICU,1,22,217,154,63,70.97,29.03,32,6,18,8,84,91
1,ICU,2,16,28,28,0,100.00,0.00,32,6,18,8,79,85
2,ICU,3,20,105,100,5,95.24,4.76,32,6,18,8,82,89
3,ICU,4,20,126,120,6,95.24,4.76,32,6,18,8,64,85
4,ICU,5,22,13,13,0,100.00,0.00,32,6,18,8,73,88

In [83]:
import os

# ==========================================
# EXPORT FINAL 4 TABLES
# ==========================================

output_folder = r"C:\Users\%USERNAME%\Documents\infosys project"
output_folder = os.path.expandvars(output_folder)

os.makedirs(output_folder, exist_ok=True)

# 1. Hospital Overview
file1 = os.path.join(
    output_folder,
    "Final_Table_1_Hospital_Overview.xlsx"
)

hospital_overview.to_excel(
    file1,
    index=False
)

# 2. Patient Flow
file2 = os.path.join(
    output_folder,
    "Final_Table_2_Patient_Flow.xlsx"
)

patient_flow.to_excel(
    file2,
    index=False
)

# 3. Department Analytics
file3 = os.path.join(
    output_folder,
    "Final_Table_3_Department_Analytics.xlsx"
)

department_analytics.to_excel(
    file3,
    index=False
)

# 4. Resource Utilization
file4 = os.path.join(
    output_folder,
    "Final_Table_4_Resource_Utilization.xlsx"
)

resource_utilization.to_excel(
    file4,
    index=False
)

# ==========================================
# EXPORT VALIDATION
# ==========================================

print("===== EXPORT COMPLETED =====")

print("\n1. Hospital Overview")
print("Rows:", len(hospital_overview))
print("Columns:", len(hospital_overview.columns))
print("Saved:", file1)

print("\n2. Patient Flow")
print("Rows:", len(patient_flow))
print("Columns:", len(patient_flow.columns))
print("Saved:", file2)

print("\n3. Department Analytics")
print("Rows:", len(department_analytics))
print("Columns:", len(department_analytics.columns))
print("Saved:", file3)

print("\n4. Resource Utilization")
print("Rows:", len(resource_utilization))
print("Columns:", len(resource_utilization.columns))
print("Saved:", file4)

print("\n===== ALL 4 FILES EXPORTED SUCCESSFULLY =====")

===== EXPORT COMPLETED =====

1. Hospital Overview
Rows: 45000
Columns: 33
Saved: C:\Users\devan\Documents\infosys project\Final_Table_1_Hospital_Overview.xlsx

2. Patient Flow
Rows: 45000
Columns: 26
Saved: C:\Users\devan\Documents\infosys project\Final_Table_2_Patient_Flow.xlsx

3. Department Analytics
Rows: 6
Columns: 10
Saved: C:\Users\devan\Documents\infosys project\Final_Table_3_Department_Analytics.xlsx

4. Resource Utilization
Rows: 208
Columns: 14
Saved: C:\Users\devan\Documents\infosys project\Final_Table_4_Resource_Utilization.xlsx

===== ALL 4 FILES EXPORTED SUCCESSFULLY =====