In [2]:
 import pandas as pd
import os

In [3]:
folder = "/content/drive/MyDrive/RAW"

for file in os.listdir(folder):
    if file.endswith(".csv"):
        path = os.path.join(folder, file)
        df = pd.read_csv(path)

        print("\n" + "="*60)
        print("FILE:", file)
        print("Rows, Columns:", df.shape)
        print("Columns:", list(df.columns))
        print("Missing values:")
        print(df.isnull().sum())
        print("Duplicate rows:", df.duplicated().sum())

============================================================
FILE: patients.csv
Rows, Columns: (1000, 7)
Columns: ['patient_id', 'name', 'age', 'arrival_date', 'departure_date', 'service', 'satisfaction']
Missing values:
patient_id        0
name              0
age               0
arrival_date      0
departure_date    0
service           0
satisfaction      0
dtype: int64
Duplicate rows: 0

============================================================
FILE: Healthcare Data Analysis for readmission.csv
Rows, Columns: (10000, 26)
Columns: ['hospital_name', 'Admission_date', 'hospital_id', 'hospital_beds_available', 'occupied_beds', 'hospital_ward', 'patient_id', 'patient_gender', 'patient_age', 'patient_race', 'patient_sat_score', 'patient_first_initial', 'patient_last_name', 'patient_waittime', 'department_referral', 'time_slot', 'doctor_id', 'doctor_name', 'doctor_specialty', 'patient_assigned_doctor', 'patient_checkin_date', 'patient_checkout_date', 'patient_disease', 'patient_length_of_stay', 'discharge_status', 'readmission']
Missing values:
hospital_name              0
Admission_date             0
hospital_id                0
hospital_beds_available    0
occupied_beds              0
hospital_ward              0
patient_id                 0
patient_gender             0
patient_age                0
patient_race               0
patient_sat_score          0
patient_first_initial      0
patient_last_name          0
patient_waittime           0
department_referral        0
time_slot                  0
doctor_id                  0
doctor_name                0
doctor_specialty           0
patient_assigned_doctor    0
patient_checkin_date       0
patient_checkout_date      0
patient_disease            0
patient_length_of_stay     0
discharge_status           0
readmission                0
dtype: int64
Duplicate rows: 0

/tmp/ipykernel_2879/1000085833.py:6: DtypeWarning: Columns (10,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

============================================================
FILE: Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv
Rows, Columns: (1801551, 33)
Columns: ['Hospital Service Area', 'Hospital County', 'Operating Certificate Number', 'Permanent Facility Id', 'Facility Name', 'Age Group', 'Zip Code - 3 digits', 'Gender', 'Race', 'Ethnicity', 'Length of Stay', 'Type of Admission', 'Patient Disposition', 'Discharge Year', 'CCSR Diagnosis Code', 'CCSR Diagnosis Description', 'CCSR Procedure Code', 'CCSR Procedure Description', 'APR DRG Code', 'APR DRG Description', 'APR MDC Code', 'APR MDC Description', 'APR Severity of Illness Code', 'APR Severity of Illness Description', 'APR Risk of Mortality', 'APR Medical Surgical Description', 'Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3', 'Birth Weight', 'Emergency Department Indicator', 'Total Charges', 'Total Costs']
Missing values:
Hospital Service Area                     9205
Hospital County                           9205
Operating Certificate Number              9205
Permanent Facility Id                     9205
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      37886
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                        942
CCSR Diagnosis Description                 942
CCSR Procedure Code                     495614
CCSR Procedure Description              495614
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          1
APR Severity of Illness Code                 1
APR Severity of Illness Description       1743
APR Risk of Mortality                     1743
APR Medical Surgical Description             1
Payment Typology 1                           1
Payment Typology 2                      905212
Payment Typology 3                     1508528
Birth Weight                           1636054
Emergency Department Indicator               1
Total Charges                                1
Total Costs                                  1
dtype: int64
Duplicate rows: 2982

In [4]:
datasets = {
    "HMIS / Healthcare Readmission Dataset": {
        "file": "Healthcare Data Analysis for readmission.csv",
        "purpose": "Core hospital, patient, admission, bed, department and readmission information"
    },

    "Patient Dataset": {
        "file": "patients.csv",
        "purpose": "Patient-level information including arrival, departure, service and satisfaction"
    },

    "Hospital Inpatient Discharges Dataset": {
        "file": "Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv",
        "purpose": "Inpatient discharge, length of stay, diagnosis, admission, disposition and financial information"
    },

    "Hospital Beds Management Dataset": {
        "file": "Hospital Beds Management.csv",
        "purpose": "Hospital bed and resource capacity information"
    }
}

print("MEDTRACK_DV - DATASET SELECTION")
print("=" * 60)

for name, details in datasets.items():
    print("\nDataset:", name)
    print("File:", details["file"])
    print("Purpose:", details["purpose"])

print("\n" + "=" * 60)
print("Total selected datasets:", len(datasets))

MEDTRACK_DV - DATASET SELECTION
============================================================

Dataset: HMIS / Healthcare Readmission Dataset
File: Healthcare Data Analysis for readmission.csv
Purpose: Core hospital, patient, admission, bed, department and readmission information

Dataset: Patient Dataset
File: patients.csv
Purpose: Patient-level information including arrival, departure, service and satisfaction

Dataset: Hospital Inpatient Discharges Dataset
File: Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv
Purpose: Inpatient discharge, length of stay, diagnosis, admission, disposition and financial information

Dataset: Hospital Beds Management Dataset
File: Hospital Beds Management.csv
Purpose: Hospital bed and resource capacity information

============================================================
Total selected datasets: 4

In [5]:
# ============================================================
# MEDTRACK_DV - MILESTONE 1
# STEP 2: DATA COLLECTION & PROFILING
# ============================================================

import pandas as pd
import os

# Folder containing the datasets
folder = "/content/drive/MyDrive/RAW"

# Find all CSV files
csv_files = [
    file for file in os.listdir(folder)
    if file.lower().endswith(".csv")
]

print("Total CSV files found:", len(csv_files))
print("=" * 80)

# Store loaded datasets
dataframes = {}

# Profile every CSV file
for file in csv_files:

    path = os.path.join(folder, file)

    # low_memory=False avoids mixed-type warning
    df = pd.read_csv(path, low_memory=False)

    dataframes[file] = df

    print("\n" + "=" * 80)
    print("FILE:", file)
    print("=" * 80)

    # Number of rows and columns
    print("\n1. Shape:")
    print(df.shape)

    # Column names
    print("\n2. Columns:")
    print(list(df.columns))

    # First 5 rows
    print("\n3. First 5 rows:")
    display(df.head())

    # Data types
    print("\n4. Data Types:")
    print(df.dtypes)

    # Missing values
    print("\n5. Missing Values:")
    print(df.isnull().sum())

    # Missing percentage
    print("\n6. Missing Percentage:")
    print((df.isnull().mean() * 100).round(2))

    # Duplicate rows
    print("\n7. Duplicate Rows:")
    print(df.duplicated().sum())

    # Number of unique values
    print("\n8. Unique Values:")
    print(df.nunique())

print("\n" + "=" * 80)
print("DATA COLLECTION & PROFILING COMPLETED")
print("=" * 80)

Total CSV files found: 3
================================================================================

================================================================================
FILE: patients.csv
================================================================================

1. Shape:
(1000, 7)

2. Columns:
['patient_id', 'name', 'age', 'arrival_date', 'departure_date', 'service', 'satisfaction']

3. First 5 rows:

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

4. Data Types:
patient_id        object
name              object
age                int64
arrival_date      object
departure_date    object
service           object
satisfaction       int64
dtype: object

5. Missing Values:
patient_id        0
name              0
age               0
arrival_date      0
departure_date    0
service           0
satisfaction      0
dtype: int64

6. Missing Percentage:
patient_id        0.0
name              0.0
age               0.0
arrival_date      0.0
departure_date    0.0
service           0.0
satisfaction      0.0
dtype: float64

7. Duplicate Rows:
0

8. Unique Values:
patient_id        1000
name               993
age                 90
arrival_date       344
departure_date     337
service              4
satisfaction        40
dtype: int64

================================================================================
FILE: Healthcare Data Analysis for readmission.csv
================================================================================

1. Shape:
(10000, 26)

2. Columns:
['hospital_name', 'Admission_date', 'hospital_id', 'hospital_beds_available', 'occupied_beds', 'hospital_ward', 'patient_id', 'patient_gender', 'patient_age', 'patient_race', 'patient_sat_score', 'patient_first_initial', 'patient_last_name', 'patient_waittime', 'department_referral', 'time_slot', 'doctor_id', 'doctor_name', 'doctor_specialty', 'patient_assigned_doctor', 'patient_checkin_date', 'patient_checkout_date', 'patient_disease', 'patient_length_of_stay', 'discharge_status', 'readmission']

3. First 5 rows:

,hospital_name,Admission_date,hospital_id,hospital_beds_available,occupied_beds,hospital_ward,patient_id,patient_gender,patient_age,patient_race,...,doctor_id,doctor_name,doctor_specialty,patient_assigned_doctor,patient_checkin_date,patient_checkout_date,patient_disease,patient_length_of_stay,discharge_status,readmission
0,The Johns Hopkins Hospital,30-01-2024,3946,260,90,Maternity,1421,Female,48,Asian,...,1725,Justin Morris,Rheumatology,False,14-07-2024,19-07-2024,Anxiety Disorders,6,Deceased,1
1,The Johns Hopkins Hospital,20-03-2022,7147,250,90,ICU,4922,Male,40,Black,...,7510,Latoya Moss,Pulmonology or Allergy and Immunology,False,19-07-2024,07/07/2024,Urinary Tract Infection (UTI),2,Deceased,1
2,The Johns Hopkins Hospital,13-07-2021,4174,350,220,Pediatrics,9804,Female,74,Black,...,7137,Michael Allen,Neurology,False,20-07-2024,29-06-2024,Hypertension (High Blood Pressure),17,Recovered,0
3,The Johns Hopkins Hospital,26-01-2021,2466,190,350,Pediatrics,5622,Male,82,Hispanic,...,8801,Rebecca Mccullough,Cardiology,False,25-06-2024,16-07-2024,Arthritis,28,Recovered,0
4,The Johns Hopkins Hospital,06/02/2024,3014,220,390,Surgery,3314,Male,62,Hispanic,...,3588,John Giles,Rheumatology,False,21-07-2024,19-07-2024,Cancer,16,Transferred,1

4. Data Types:
hospital_name              object
Admission_date             object
hospital_id                 int64
hospital_beds_available     int64
occupied_beds               int64
hospital_ward              object
patient_id                  int64
patient_gender             object
patient_age                 int64
patient_race               object
patient_sat_score           int64
patient_first_initial      object
patient_last_name          object
patient_waittime            int64
department_referral        object
time_slot                  object
doctor_id                   int64
doctor_name                object
doctor_specialty           object
patient_assigned_doctor      bool
patient_checkin_date       object
patient_checkout_date      object
patient_disease            object
patient_length_of_stay      int64
discharge_status           object
readmission                 int64
dtype: object

5. Missing Values:
hospital_name              0
Admission_date             0
hospital_id                0
hospital_beds_available    0
occupied_beds              0
hospital_ward              0
patient_id                 0
patient_gender             0
patient_age                0
patient_race               0
patient_sat_score          0
patient_first_initial      0
patient_last_name          0
patient_waittime           0
department_referral        0
time_slot                  0
doctor_id                  0
doctor_name                0
doctor_specialty           0
patient_assigned_doctor    0
patient_checkin_date       0
patient_checkout_date      0
patient_disease            0
patient_length_of_stay     0
discharge_status           0
readmission                0
dtype: int64

6. Missing Percentage:
hospital_name              0.0
Admission_date             0.0
hospital_id                0.0
hospital_beds_available    0.0
occupied_beds              0.0
hospital_ward              0.0
patient_id                 0.0
patient_gender             0.0
patient_age                0.0
patient_race               0.0
patient_sat_score          0.0
patient_first_initial      0.0
patient_last_name          0.0
patient_waittime           0.0
department_referral        0.0
time_slot                  0.0
doctor_id                  0.0
doctor_name                0.0
doctor_specialty           0.0
patient_assigned_doctor    0.0
patient_checkin_date       0.0
patient_checkout_date      0.0
patient_disease            0.0
patient_length_of_stay     0.0
discharge_status           0.0
readmission                0.0
dtype: float64

7. Duplicate Rows:
0

8. Unique Values:
hospital_name                 1
Admission_date             1460
hospital_id                6074
hospital_beds_available      41
occupied_beds                41
hospital_ward                 5
patient_id                 6022
patient_gender                2
patient_age                  96
patient_race                  5
patient_sat_score           151
patient_first_initial        52
patient_last_name           985
patient_waittime              8
department_referral          19
time_slot                  1439
doctor_id                  6019
doctor_name                9379
doctor_specialty             19
patient_assigned_doctor       2
patient_checkin_date         30
patient_checkout_date        29
patient_disease              28
patient_length_of_stay       30
discharge_status              3
readmission                   2
dtype: int64

================================================================================
FILE: Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv
================================================================================

1. Shape:
(1801551, 33)

2. Columns:
['Hospital Service Area', 'Hospital County', 'Operating Certificate Number', 'Permanent Facility Id', 'Facility Name', 'Age Group', 'Zip Code - 3 digits', 'Gender', 'Race', 'Ethnicity', 'Length of Stay', 'Type of Admission', 'Patient Disposition', 'Discharge Year', 'CCSR Diagnosis Code', 'CCSR Diagnosis Description', 'CCSR Procedure Code', 'CCSR Procedure Description', 'APR DRG Code', 'APR DRG Description', 'APR MDC Code', 'APR MDC Description', 'APR Severity of Illness Code', 'APR Severity of Illness Description', 'APR Risk of Mortality', 'APR Medical Surgical Description', 'Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3', 'Birth Weight', 'Emergency Department Indicator', 'Total Charges', 'Total Costs']

3. First 5 rows:

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,70 or Older,104,M,Other Race,Spanish/Hispanic,...,Major,Extreme,Medical,Medicare,Medicaid,NaN,NaN,Y,"320,922.43","60,241.34"
1,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,50 to 69,104,F,White,Not Span/Hispanic,...,Moderate,Minor,Medical,Private Health Insurance,NaN,NaN,NaN,Y,"61,665.22","9,180.69"
2,New York City,Bronx,7000006.0,1168.0,Montefiore Medical Center-Wakefield Hospital,18 to 29,104,F,Other Race,Spanish/Hispanic,...,Minor,Minor,Surgical,Medicaid,NaN,NaN,NaN,N,"42,705.34","11,366.5"
3,New York City,Bronx,7000006.0,3058.0,Montefiore Med Center - Jack D Weiler Hosp of ...,70 or Older,104,M,Other Race,Spanish/Hispanic,...,Major,Major,Medical,Medicare,Medicaid,NaN,NaN,Y,"72,700.17","12,111.75"
4,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,50 to 69,104,F,Black/African American,Not Span/Hispanic,...,Moderate,Minor,Medical,Medicare,Medicaid,NaN,NaN,Y,"55,562.51","8,339.72"

4. Data Types:
Hospital Service Area                   object
Hospital County                         object
Operating Certificate Number           float64
Permanent Facility Id                  float64
Facility Name                           object
Age Group                               object
Zip Code - 3 digits                     object
Gender                                  object
Race                                    object
Ethnicity                               object
Length of Stay                          object
Type of Admission                       object
Patient Disposition                     object
Discharge Year                           int64
CCSR Diagnosis Code                     object
CCSR Diagnosis Description              object
CCSR Procedure Code                     object
CCSR Procedure Description              object
APR DRG Code                             int64
APR DRG Description                     object
APR MDC Code                             int64
APR MDC Description                     object
APR Severity of Illness Code           float64
APR Severity of Illness Description     object
APR Risk of Mortality                   object
APR Medical Surgical Description        object
Payment Typology 1                      object
Payment Typology 2                      object
Payment Typology 3                      object
Birth Weight                            object
Emergency Department Indicator          object
Total Charges                           object
Total Costs                             object
dtype: object

5. Missing Values:
Hospital Service Area                     9205
Hospital County                           9205
Operating Certificate Number              9205
Permanent Facility Id                     9205
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      37886
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                        942
CCSR Diagnosis Description                 942
CCSR Procedure Code                     495614
CCSR Procedure Description              495614
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          1
APR Severity of Illness Code                 1
APR Severity of Illness Description       1743
APR Risk of Mortality                     1743
APR Medical Surgical Description             1
Payment Typology 1                           1
Payment Typology 2                      905212
Payment Typology 3                     1508528
Birth Weight                           1636054
Emergency Department Indicator               1
Total Charges                                1
Total Costs                                  1
dtype: int64

6. Missing Percentage:
Hospital Service Area                   0.51
Hospital County                         0.51
Operating Certificate Number            0.51
Permanent Facility Id                   0.51
Facility Name                           0.00
Age Group                               0.00
Zip Code - 3 digits                     2.10
Gender                                  0.00
Race                                    0.00
Ethnicity                               0.00
Length of Stay                          0.00
Type of Admission                       0.00
Patient Disposition                     0.00
Discharge Year                          0.00
CCSR Diagnosis Code                     0.05
CCSR Diagnosis Description              0.05
CCSR Procedure Code                    27.51
CCSR Procedure Description             27.51
APR DRG Code                            0.00
APR DRG Description                     0.00
APR MDC Code                            0.00
APR MDC Description                     0.00
APR Severity of Illness Code            0.00
APR Severity of Illness Description     0.10
APR Risk of Mortality                   0.10
APR Medical Surgical Description        0.00
Payment Typology 1                      0.00
Payment Typology 2                     50.25
Payment Typology 3                     83.73
Birth Weight                           90.81
Emergency Department Indicator          0.00
Total Charges                           0.00
Total Costs                             0.00
dtype: float64

7. Duplicate Rows:
4109

8. Unique Values:
Hospital Service Area                        8
Hospital County                             56
Operating Certificate Number               166
Permanent Facility Id                      203
Facility Name                              203
Age Group                                    5
Zip Code - 3 digits                         50
Gender                                       3
Race                                         4
Ethnicity                                    4
Length of Stay                             120
Type of Admission                            6
Patient Disposition                         19
Discharge Year                               1
CCSR Diagnosis Code                        477
CCSR Diagnosis Description                 477
CCSR Procedure Code                        320
CCSR Procedure Description                 320
APR DRG Code                               334
APR DRG Description                        334
APR MDC Code                                26
APR MDC Description                         26
APR Severity of Illness Code                 5
APR Severity of Illness Description          4
APR Risk of Mortality                        4
APR Medical Surgical Description             3
Payment Typology 1                           9
Payment Typology 2                           9
Payment Typology 3                           9
Birth Weight                                67
Emergency Department Indicator               2
Total Charges                          1585078
Total Costs                            1374391
dtype: int64

================================================================================
DATA COLLECTION & PROFILING COMPLETED
================================================================================

In [6]:
input_folder = "/content/drive/MyDrive/RAW"
output_folder = "/content/drive/MyDrive/RAW/Cleaned"

os.makedirs(output_folder, exist_ok=True)


# ------------------------------------------------------------
# 2. LOAD DATASETS
# ------------------------------------------------------------

patients = pd.read_csv(
    os.path.join(input_folder, "patients.csv"),
    low_memory=False
)

readmission = pd.read_csv(
    os.path.join(input_folder, "Healthcare Data Analysis for readmission.csv"),
    low_memory=False
)

inpatient = pd.read_csv(
    os.path.join(
        input_folder,
        "Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv"
    ),
    low_memory=False
)

# DATASET 1: PATIENTS

print("Cleaning patients.csv...")

# Standardize column names
patients.columns = patients.columns.str.strip().str.lower()

# Standardize text columns
patients["name"] = patients["name"].astype(str).str.strip()
patients["service"] = patients["service"].astype(str).str.strip().str.lower()

# Convert dates
patients["arrival_date"] = pd.to_datetime(
    patients["arrival_date"],
    errors="coerce"
)

patients["departure_date"] = pd.to_datetime(
    patients["departure_date"],
    errors="coerce"
)

# Remove exact duplicate rows
patients = patients.drop_duplicates()

# Check invalid values
patients.loc[
    (patients["age"] < 0) | (patients["age"] > 120),
    "age"
] = pd.NA

patients.loc[
    (patients["satisfaction"] < 0) | (patients["satisfaction"] > 100),
    "satisfaction"
] = pd.NA

print("Patients cleaned:", patients.shape)


# DATASET 2: READMISSION / HMIS

print("\nCleaning Healthcare Data Analysis for readmission.csv...")

# Standardize column names
readmission.columns = readmission.columns.str.strip().str.lower()

# Standardize text columns
text_columns = [
    "hospital_name",
    "hospital_ward",
    "patient_gender",
    "patient_race",
    "patient_first_initial",
    "patient_last_name",
    "department_referral",
    "time_slot",
    "doctor_name",
    "doctor_specialty",
    "patient_disease",
    "discharge_status"
]

for col in text_columns:
    readmission[col] = (
        readmission[col]
        .astype(str)
        .str.strip()
    )

# Standardize categorical values
readmission["hospital_ward"] = (
    readmission["hospital_ward"]
    .str.lower()
    .str.strip()
)

readmission["department_referral"] = (
    readmission["department_referral"]
    .str.lower()
    .str.strip()
)

readmission["patient_gender"] = (
    readmission["patient_gender"]
    .str.lower()
    .str.strip()
)

readmission["patient_race"] = (
    readmission["patient_race"]
    .str.lower()
    .str.strip()
)

readmission["discharge_status"] = (
    readmission["discharge_status"]
    .str.lower()
    .str.strip()
)

# Convert dates
date_columns = [
    "admission_date",
    "patient_checkin_date",
    "patient_checkout_date"
]

for col in date_columns:
    readmission[col] = pd.to_datetime(
        readmission[col],
        errors="coerce",
        dayfirst=True
    )

# Remove exact duplicates
readmission = readmission.drop_duplicates()

# Standardize IDs
readmission["hospital_id"] = (
    pd.to_numeric(readmission["hospital_id"], errors="coerce")
    .astype("Int64")
)

readmission["patient_id"] = (
    pd.to_numeric(readmission["patient_id"], errors="coerce")
    .astype("Int64")
)

readmission["doctor_id"] = (
    pd.to_numeric(readmission["doctor_id"], errors="coerce")
    .astype("Int64")
)

# Validate numeric ranges
readmission.loc[
    (readmission["patient_age"] < 0) |
    (readmission["patient_age"] > 120),
    "patient_age"
] = pd.NA

readmission.loc[
    readmission["patient_sat_score"] < 0,
    "patient_sat_score"
] = pd.NA

readmission.loc[
    readmission["patient_length_of_stay"] < 0,
    "patient_length_of_stay"
] = pd.NA

readmission.loc[
    readmission["patient_waittime"] < 0,
    "patient_waittime"
] = pd.NA

# Ensure readmission is 0/1
readmission["readmission"] = pd.to_numeric(
    readmission["readmission"],
    errors="coerce"
)

readmission.loc[
    ~readmission["readmission"].isin([0, 1]),
    "readmission"
] = pd.NA

print("Readmission dataset cleaned:", readmission.shape)


# DATASET 3: INPATIENT DISCHARGES

print("\nCleaning Hospital Inpatient Discharges dataset...")

# Standardize column names
inpatient.columns = (
    inpatient.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

# ------------------------------------------------------------
# Remove exact duplicate rows
# ------------------------------------------------------------

before = len(inpatient)

inpatient = inpatient.drop_duplicates()

after = len(inpatient)

print("Duplicate rows removed:", before - after)


# ------------------------------------------------------------
# Standardize text columns
# ------------------------------------------------------------

text_columns = inpatient.select_dtypes(
    include=["object"]
).columns

for col in text_columns:
    inpatient[col] = (
        inpatient[col]
        .astype("string")
        .str.strip()
    )


# ------------------------------------------------------------
# Convert numeric columns
# ------------------------------------------------------------

numeric_columns = [
    "operating_certificate_number",
    "permanent_facility_id",
    "apr_drg_code",
    "apr_mdc_code",
    "apr_severity_of_illness_code"
]

for col in numeric_columns:
    inpatient[col] = pd.to_numeric(
        inpatient[col],
        errors="coerce"
    )


# ------------------------------------------------------------
# Length of Stay
# ------------------------------------------------------------

inpatient["length_of_stay"] = pd.to_numeric(
    inpatient["length_of_stay"],
    errors="coerce"
)

inpatient.loc[
    inpatient["length_of_stay"] < 0,
    "length_of_stay"
] = pd.NA


# ------------------------------------------------------------
# Financial columns
# Remove commas and convert to numeric
# ------------------------------------------------------------

inpatient["total_charges"] = pd.to_numeric(
    inpatient["total_charges"]
    .astype(str)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

inpatient["total_costs"] = pd.to_numeric(
    inpatient["total_costs"]
    .astype(str)
    .str.replace(",", "", regex=False),
    errors="coerce"
)


# ------------------------------------------------------------
# Birth Weight
# ------------------------------------------------------------

inpatient["birth_weight"] = pd.to_numeric(
    inpatient["birth_weight"],
    errors="coerce"
)


# ------------------------------------------------------------
# Standardize categorical values
# ------------------------------------------------------------

categorical_columns = [
    "gender",
    "race",
    "ethnicity",
    "type_of_admission",
    "patient_disposition",
    "apr_risk_of_mortality",
    "apr_medical_surgical_description",
    "payment_typology_1",
    "payment_typology_2",
    "payment_typology_3",
    "emergency_department_indicator"
]

for col in categorical_columns:
    inpatient[col] = (
        inpatient[col]
        .astype("string")
        .str.strip()
        .str.lower()
    )


# ------------------------------------------------------------
# Missing values
# ------------------------------------------------------------
# Do NOT replace all missing values with 0.
# Keep genuine missing information as NA.
#
# Only numerical financial values are retained as numeric;
# categorical missing values remain missing.
# ------------------------------------------------------------


# ============================================================
# SAVE CLEANED DATASETS
# ============================================================

patients.to_csv(
    os.path.join(output_folder, "patients_cleaned.csv"),
    index=False
)

readmission.to_csv(
    os.path.join(output_folder, "readmission_cleaned.csv"),
    index=False
)

inpatient.to_csv(
    os.path.join(output_folder, "inpatient_discharges_cleaned.csv"),
    index=False
)


# CLEANING SUMMARY

print("\n" + "=" * 70)
print("DATA CLEANING COMPLETED")
print("=" * 70)

print("\nPatients:")
print("Rows:", len(patients))
print("Columns:", len(patients.columns))
print("Duplicates:", patients.duplicated().sum())

print("\nReadmission:")
print("Rows:", len(readmission))
print("Columns:", len(readmission.columns))
print("Duplicates:", readmission.duplicated().sum())

print("\nInpatient Discharges:")
print("Rows:", len(inpatient))
print("Columns:", len(inpatient.columns))
print("Duplicates:", inpatient.duplicated().sum())

print("\nCleaned files saved in:")
print(output_folder)

Cleaning patients.csv...
Patients cleaned: (1000, 7)

Cleaning Healthcare Data Analysis for readmission.csv...
Readmission dataset cleaned: (10000, 26)

Cleaning Hospital Inpatient Discharges dataset...
Duplicate rows removed: 4109

======================================================================
DATA CLEANING COMPLETED
======================================================================

Patients:
Rows: 1000
Columns: 7
Duplicates: 0

Readmission:
Rows: 10000
Columns: 26
Duplicates: 0

Inpatient Discharges:
Rows: 1797442
Columns: 33
Duplicates: 0

Cleaned files saved in:
/content/drive/MyDrive/RAW/Cleaned

In [7]:
cleaned_folder = "/content/drive/MyDrive/RAW/Cleaned"
standardized_folder = "/content/drive/MyDrive/RAW/Standardized"
os.makedirs(standardized_folder, exist_ok=True)

# 2. LOAD CLEANED DATASETS

patients = pd.read_csv(
    os.path.join(cleaned_folder, "patients_cleaned.csv"),
    low_memory=False
)

readmission = pd.read_csv(
    os.path.join(cleaned_folder, "readmission_cleaned.csv"),
    low_memory=False
)

inpatient = pd.read_csv(
    os.path.join(cleaned_folder, "inpatient_discharges_cleaned.csv"),
    low_memory=False
)

# 3. PATIENT ID STANDARDIZATION

# patients.csv already has IDs like PAT-09484753
patients["patient_id"] = (
    patients["patient_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Readmission dataset has numeric patient IDs
readmission["patient_id"] = (
    pd.to_numeric(
        readmission["patient_id"],
        errors="coerce"
    )
    .astype("Int64")
)

# Create a consistent text ID format
readmission["patient_id"] = (
    "PAT-" +
    readmission["patient_id"].astype(str)
)


# ============================================================
# 4. HOSPITAL ID STANDARDIZATION
# ============================================================

readmission["hospital_id"] = (
    pd.to_numeric(
        readmission["hospital_id"],
        errors="coerce"
    )
    .astype("Int64")
)

# Convert hospital ID to consistent text format
readmission["hospital_id"] = (
    "HOSP-" +
    readmission["hospital_id"].astype(str)
)


# ============================================================
# 5. DOCTOR ID STANDARDIZATION
# ============================================================

readmission["doctor_id"] = (
    pd.to_numeric(
        readmission["doctor_id"],
        errors="coerce"
    )
    .astype("Int64")
)

# Convert doctor ID to consistent text format
readmission["doctor_id"] = (
    "DOC-" +
    readmission["doctor_id"].astype(str)
)


# ============================================================
# 6. INPATIENT FACILITY ID STANDARDIZATION
# ============================================================

# Permanent Facility ID
inpatient["permanent_facility_id"] = pd.to_numeric(
    inpatient["permanent_facility_id"],
    errors="coerce"
)

inpatient["permanent_facility_id"] = (
    "FAC-" +
    inpatient["permanent_facility_id"]
    .astype("Int64")
    .astype(str)
)

# Operating Certificate Number
inpatient["operating_certificate_number"] = pd.to_numeric(
    inpatient["operating_certificate_number"],
    errors="coerce"
)

inpatient["operating_certificate_number"] = (
    "CERT-" +
    inpatient["operating_certificate_number"]
    .astype("Int64")
    .astype(str)
)


# ============================================================
# 7. VERIFY ID STANDARDIZATION
# ============================================================

print("=" * 70)
print("ID STANDARDIZATION RESULTS")
print("=" * 70)

print("\nPatients - Patient IDs:")
print(patients["patient_id"].head())

print("\nReadmission - Patient IDs:")
print(readmission["patient_id"].head())

print("\nReadmission - Hospital IDs:")
print(readmission["hospital_id"].head())

print("\nReadmission - Doctor IDs:")
print(readmission["doctor_id"].head())

print("\nInpatient - Facility IDs:")
print(inpatient["permanent_facility_id"].head())

print("\nInpatient - Certificate IDs:")
print(inpatient["operating_certificate_number"].head())


# ============================================================
# 8. SAVE STANDARDIZED DATASETS
# ============================================================

patients.to_csv(
    os.path.join(
        standardized_folder,
        "patients_standardized.csv"
    ),
    index=False
)

readmission.to_csv(
    os.path.join(
        standardized_folder,
        "readmission_standardized.csv"
    ),
    index=False
)

inpatient.to_csv(
    os.path.join(
        standardized_folder,
        "inpatient_discharges_standardized.csv"
    ),
    index=False
)

# 9. FINAL CHECK

print("\n" + "=" * 70)
print("ID STANDARDIZATION COMPLETED")
print("=" * 70)

print("\nPatients:", patients.shape)
print("Readmission:", readmission.shape)
print("Inpatient Discharges:", inpatient.shape)

print("\nStandardized files saved to:")
print(standardized_folder)

======================================================================
ID STANDARDIZATION RESULTS
======================================================================

Patients - Patient IDs:
0    PAT-09484753
1    PAT-F0644084
2    PAT-AC6162E4
3    PAT-3DDA2BB5
4    PAT-08591375
Name: patient_id, dtype: object

Readmission - Patient IDs:
0    PAT-1421
1    PAT-4922
2    PAT-9804
3    PAT-5622
4    PAT-3314
Name: patient_id, dtype: object

Readmission - Hospital IDs:
0    HOSP-3946
1    HOSP-7147
2    HOSP-4174
3    HOSP-2466
4    HOSP-3014
Name: hospital_id, dtype: object

Readmission - Doctor IDs:
0    DOC-1725
1    DOC-7510
2    DOC-7137
3    DOC-8801
4    DOC-3588
Name: doctor_id, dtype: object

Inpatient - Facility IDs:
0    FAC-1169
1    FAC-1169
2    FAC-1168
3    FAC-3058
4    FAC-1169
Name: permanent_facility_id, dtype: object

Inpatient - Certificate IDs:
0    CERT-7000006
1    CERT-7000006
2    CERT-7000006
3    CERT-7000006
4    CERT-7000006
Name: operating_certificate_number, dtype: object

======================================================================
ID STANDARDIZATION COMPLETED
======================================================================

Patients: (1000, 7)
Readmission: (10000, 26)
Inpatient Discharges: (1797442, 33)

Standardized files saved to:
/content/drive/MyDrive/RAW/Standardized

In [8]:
standardized_folder = "/content/drive/MyDrive/RAW/Standardized"
department_folder = "/content/drive/MyDrive/RAW/Department_Standardized"

os.makedirs(department_folder, exist_ok=True)


# 2. LOAD STANDARDIZED DATASETS

patients = pd.read_csv(
    os.path.join(standardized_folder, "patients_standardized.csv"),
    low_memory=False
)

readmission = pd.read_csv(
    os.path.join(standardized_folder, "readmission_standardized.csv"),
    low_memory=False
)

inpatient = pd.read_csv(
    os.path.join(
        standardized_folder,
        "inpatient_discharges_standardized.csv"
    ),
    low_memory=False
)


# 3. STANDARDIZE DEPARTMENT / SERVICE NAMES

# Patients dataset
# Column: service

if "service" in patients.columns:

    patients["service"] = (
        patients["service"]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

    # Standardize common naming variations
    patients["service"] = patients["service"].replace({
        "general medicine": "general_medicine",
        "general-medicine": "general_medicine",
        "general medicine ": "general_medicine",
        "icu": "icu",
        "surgery": "surgery",
        "emergency": "emergency"
    })

# Readmission dataset
# Columns: hospital_ward and department_referral

if "hospital_ward" in readmission.columns:

    readmission["hospital_ward"] = (
        readmission["hospital_ward"]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

if "department_referral" in readmission.columns:

    readmission["department_referral"] = (
        readmission["department_referral"]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

# 4. DISPLAY STANDARDIZED DEPARTMENT VALUES

print("=" * 70)
print("STANDARDIZED DEPARTMENT / SERVICE VALUES")
print("=" * 70)

if "service" in patients.columns:
    print("\nPatients - Service:")
    print(sorted(patients["service"].dropna().unique()))

if "hospital_ward" in readmission.columns:
    print("\nReadmission - Hospital Ward:")
    print(sorted(readmission["hospital_ward"].dropna().unique()))

if "department_referral" in readmission.columns:
    print("\nReadmission - Department Referral:")
    print(sorted(readmission["department_referral"].dropna().unique()))

# 5. SAVE DEPARTMENT-STANDARDIZED DATASETS

patients.to_csv(
    os.path.join(
        department_folder,
        "patients_department_standardized.csv"
    ),
    index=False
)

readmission.to_csv(
    os.path.join(
        department_folder,
        "readmission_department_standardized.csv"
    ),
    index=False
)

inpatient.to_csv(
    os.path.join(
        department_folder,
        "inpatient_discharges_department_standardized.csv"
    ),
    index=False
)


# 6. COMPLETION CHECK

print("\n" + "=" * 70)
print("DEPARTMENT STANDARDIZATION COMPLETED")
print("=" * 70)

print("\nPatients:", patients.shape)
print("Readmission:", readmission.shape)
print("Inpatient Discharges:", inpatient.shape)

print("\nFiles saved to:")
print(department_folder)

======================================================================
STANDARDIZED DEPARTMENT / SERVICE VALUES
======================================================================

Patients - Service:
['emergency', 'general_medicine', 'icu', 'surgery']

Readmission - Hospital Ward:
['er', 'icu', 'maternity', 'pediatrics', 'surgery']

Readmission - Department Referral:
['allergy and immunology', 'cardiology', 'cardiology or internal medicine', 'dermatology', 'endocrinology', 'gastroenterology', 'hepatology', 'hepatology or gastroenterology', 'infectious disease', 'infectious disease or internal medicine', 'nephrology', 'neurology', 'oncology', 'psychiatry', 'pulmonology', 'pulmonology or allergy and immunology', 'pulmonology or infectious disease', 'rheumatology', 'urology or nephrology']

======================================================================
DEPARTMENT STANDARDIZATION COMPLETED
======================================================================

Patients: (1000, 7)
Readmission: (10000, 26)
Inpatient Discharges: (1797442, 33)

Files saved to:
/content/drive/MyDrive/RAW/Department_Standardized

In [9]:
input_folder = "/content/drive/MyDrive/RAW/Department_Standardized"
output_folder = "/content/drive/MyDrive/RAW/Date_Standardized"

os.makedirs(output_folder, exist_ok=True)

# 1. LOAD DATASETS

patients = pd.read_csv(
    os.path.join(input_folder, "patients_department_standardized.csv")
)

readmission = pd.read_csv(
    os.path.join(input_folder, "readmission_department_standardized.csv")
)

inpatient = pd.read_csv(
    os.path.join(
        input_folder,
        "inpatient_discharges_department_standardized.csv"
    ),
    low_memory=False
)

# 2. PATIENTS DATASET

patients["arrival_date"] = pd.to_datetime(
    patients["arrival_date"],
    errors="coerce"
)

patients["departure_date"] = pd.to_datetime(
    patients["departure_date"],
    errors="coerce"
)

# Create standard date columns
patients["arrival_date"] = patients["arrival_date"].dt.strftime("%Y-%m-%d")
patients["departure_date"] = patients["departure_date"].dt.strftime("%Y-%m-%d")

# 3. READMISSION DATASET

readmission["admission_date"] = pd.to_datetime(
    readmission["admission_date"],
    errors="coerce"
)

readmission["patient_checkin_date"] = pd.to_datetime(
    readmission["patient_checkin_date"],
    errors="coerce"
)

readmission["patient_checkout_date"] = pd.to_datetime(
    readmission["patient_checkout_date"],
    errors="coerce"
)

# Standard date format
readmission["admission_date"] = readmission["admission_date"].dt.strftime("%Y-%m-%d")
readmission["patient_checkin_date"] = readmission["patient_checkin_date"].dt.strftime("%Y-%m-%d")
readmission["patient_checkout_date"] = readmission["patient_checkout_date"].dt.strftime("%Y-%m-%d")


# 4. INPATIENT DISCHARGES DATASET

# Check whether discharge/admission date columns exist
date_columns = [
    col for col in inpatient.columns
    if "date" in col.lower() or "year" in col.lower() # Include 'year' to catch 'discharge_year'
]

print("Inpatient date-related columns:")
print(date_columns)

# Convert any date-related columns to standard format
for col in date_columns:
    if col == "discharge_year":
        # Create a full date string (YYYY-01-01) for proper conversion
        inpatient[col] = pd.to_datetime(
            inpatient[col].astype(str) + '-01-01',
            errors="coerce"
        )
    else:
        inpatient[col] = pd.to_datetime(
            inpatient[col],
            errors="coerce"
        )
    inpatient[col] = inpatient[col].dt.strftime("%Y-%m-%d")

# 5. CHECK DATE VALUES

print("\n" + "="*70)
print("DATE STANDARDIZATION CHECK")
print("="*70)

print("\nPatients:")
print(patients[["arrival_date", "departure_date"]].head())

print("\nReadmission:")
print(
    readmission[
        ["admission_date", "patient_checkin_date", "patient_checkout_date"]
    ].head()
)

print("\nInpatient date columns:")
for col in date_columns:
    print(f"\n{col}:")
    print(inpatient[col].head())

# 6. SAVE DATASETS

patients.to_csv(
    os.path.join(output_folder, "patients_date_standardized.csv"),
    index=False
)

readmission.to_csv(
    os.path.join(output_folder, "readmission_date_standardized.csv"),
    index=False
)

inpatient.to_csv(
    os.path.join(output_folder, "inpatient_discharges_date_standardized.csv"),
    index=False
)


print("\n" + "="*70)
print("DATE STANDARDIZATION COMPLETED")
print("="*70)

print("Patients:", patients.shape)
print("Readmission:", readmission.shape)
print("Inpatient Discharges:", inpatient.shape)

print("\nFiles saved to:")
print(output_folder)

Inpatient date-related columns:
['discharge_year']

======================================================================
DATE STANDARDIZATION CHECK
======================================================================

Patients:
  arrival_date departure_date
0   2025-03-16     2025-03-22
1   2025-12-13     2025-12-14
2   2025-06-29     2025-07-05
3   2025-10-12     2025-10-23
4   2025-02-18     2025-02-25

Readmission:
  admission_date patient_checkin_date patient_checkout_date
0     2024-01-30           2024-07-14            2024-07-19
1     2022-03-20           2024-07-19                   NaN
2     2021-07-13           2024-07-20            2024-06-29
3     2021-01-26           2024-06-25            2024-07-16
4            NaN           2024-07-21            2024-07-19

Inpatient date columns:

discharge_year:
0    2021-01-01
1    2021-01-01
2    2021-01-01
3    2021-01-01
4    2021-01-01
Name: discharge_year, dtype: object

======================================================================
DATE STANDARDIZATION COMPLETED
======================================================================
Patients: (1000, 7)
Readmission: (10000, 26)
Inpatient Discharges: (1797442, 33)

Files saved to:
/content/drive/MyDrive/RAW/Date_Standardized

In [10]:
input_folder = "/content/drive/MyDrive/RAW/Date_Standardized"
output_folder = "/content/drive/MyDrive/RAW/Missing_Value_Treated"

os.makedirs(output_folder, exist_ok=True)

# LOAD DATASETS

patients = pd.read_csv(
    os.path.join(input_folder, "patients_date_standardized.csv")
)

readmission = pd.read_csv(
    os.path.join(input_folder, "readmission_date_standardized.csv")
)

inpatient = pd.read_csv(
    os.path.join(
        input_folder,
        "inpatient_discharges_date_standardized.csv"
    ),
    low_memory=False
)

# 1. CHECK MISSING VALUES

print("="*70)
print("MISSING VALUES BEFORE TREATMENT")
print("="*70)

print("\n--- PATIENTS ---")
patients_missing = patients.isnull().sum()
print(patients_missing[patients_missing > 0])

print("\n--- READMISSION ---")
readmission_missing = readmission.isnull().sum()
print(readmission_missing[readmission_missing > 0])

print("\n--- INPATIENT DISCHARGES ---")
inpatient_missing = inpatient.isnull().sum()
print(inpatient_missing[inpatient_missing > 0])

# 2. PATIENTS DATASET

# Dates:
# Missing dates are kept as NaN because we should not invent dates.

# Numeric satisfaction:
# Missing values are kept as NaN rather than assuming 0 satisfaction.

# No forced replacement with 0.

# 3. READMISSION DATASET

# Important numerical fields:
# Missing values are kept as NaN.
# We do not assume missing = 0.

# Readmission is different:
# If the readmission field is missing, it cannot safely be
# classified as either readmitted or not readmitted.
# Therefore, keep it as NaN.

# 4. INPATIENT DISCHARGES DATASET

# Large number of missing values exist in this dataset.
# We keep them as NaN because replacing them with 0 could
# incorrectly change the meaning of the data.

# No blanket filling of missing values.

# 5. FINAL MISSING VALUE CHECK

print("\n" + "="*70)
print("MISSING VALUE TREATMENT")
print("="*70)

print("\nNo blanket zero-filling was performed.")
print("Missing values that cannot be reliably inferred remain NaN.")

# 6. SAVE DATASETS

patients.to_csv(
    os.path.join(
        output_folder,
        "patients_missing_treated.csv"
    ),
    index=False
)

readmission.to_csv(
    os.path.join(
        output_folder,
        "readmission_missing_treated.csv"
    ),
    index=False
)

inpatient.to_csv(
    os.path.join(
        output_folder,
        "inpatient_discharges_missing_treated.csv"
    ),
    index=False
)

print("\n" + "="*70)
print("MISSING VALUE TREATMENT COMPLETED")
print("="*70)

print("Patients:", patients.shape)
print("Readmission:", readmission.shape)
print("Inpatient Discharges:", inpatient.shape)

print("\nFiles saved to:")
print(output_folder)

======================================================================
MISSING VALUES BEFORE TREATMENT
======================================================================

--- PATIENTS ---
Series([], dtype: int64)

--- READMISSION ---
admission_date           3919
patient_checkin_date     4074
patient_checkout_date    4127
dtype: int64

--- INPATIENT DISCHARGES ---
hospital_service_area                     9201
hospital_county                           9201
zip_code___3_digits                      37880
length_of_stay                            1213
ccsr_diagnosis_code                        942
ccsr_diagnosis_description                 942
ccsr_procedure_code                     493493
ccsr_procedure_description              493493
apr_mdc_description                          1
apr_severity_of_illness_code                 1
apr_severity_of_illness_description       1743
apr_risk_of_mortality                     1743
apr_medical_surgical_description             1
payment_typology_1                           1
payment_typology_2                      902673
payment_typology_3                     1505237
birth_weight                           1635297
emergency_department_indicator               1
total_charges                                1
total_costs                                  1
dtype: int64

======================================================================
MISSING VALUE TREATMENT
======================================================================

No blanket zero-filling was performed.
Missing values that cannot be reliably inferred remain NaN.

======================================================================
MISSING VALUE TREATMENT COMPLETED
======================================================================
Patients: (1000, 7)
Readmission: (10000, 26)
Inpatient Discharges: (1797442, 33)

Files saved to:
/content/drive/MyDrive/RAW/Missing_Value_Treated

In [11]:
input_folder = "/content/drive/MyDrive/RAW/Missing_Value_Treated"
output_folder = "/content/drive/MyDrive/RAW/Duplicates_Checked"

os.makedirs(output_folder, exist_ok=True)

# LOAD DATASETS

patients = pd.read_csv(
    os.path.join(input_folder, "patients_missing_treated.csv")
)

readmission = pd.read_csv(
    os.path.join(input_folder, "readmission_missing_treated.csv")
)

inpatient = pd.read_csv(
    os.path.join(
        input_folder,
        "inpatient_discharges_missing_treated.csv"
    ),
    low_memory=False
)

# CHECK DUPLICATES

patients_duplicates = patients.duplicated().sum()
readmission_duplicates = readmission.duplicated().sum()
inpatient_duplicates = inpatient.duplicated().sum()

print("="*70)
print("DUPLICATE CHECK")
print("="*70)

print("\nPatients:")
print("Duplicate rows:", patients_duplicates)

print("\nReadmission:")
print("Duplicate rows:", readmission_duplicates)

print("\nInpatient Discharges:")
print("Duplicate rows:", inpatient_duplicates)

# REMOVE ANY REMAINING EXACT DUPLICATES

patients = patients.drop_duplicates().reset_index(drop=True)
readmission = readmission.drop_duplicates().reset_index(drop=True)
inpatient = inpatient.drop_duplicates().reset_index(drop=True)

# FINAL CHECK

print("\n" + "="*70)
print("FINAL DUPLICATE CHECK")
print("="*70)

print("Patients:", patients.duplicated().sum())
print("Readmission:", readmission.duplicated().sum())
print("Inpatient Discharges:", inpatient.duplicated().sum())

# SAVE DATASETS

patients.to_csv(
    os.path.join(
        output_folder,
        "patients_duplicates_checked.csv"
    ),
    index=False
)

readmission.to_csv(
    os.path.join(
        output_folder,
        "readmission_duplicates_checked.csv"
    ),
    index=False
)

inpatient.to_csv(
    os.path.join(
        output_folder,
        "inpatient_discharges_duplicates_checked.csv"
    ),
    index=False
)

print("\n" + "="*70)
print("DUPLICATE HANDLING COMPLETED")
print("="*70)

print("Patients:", patients.shape)
print("Readmission:", readmission.shape)
print("Inpatient Discharges:", inpatient.shape)

print("\nFiles saved to:")
print(output_folder)

======================================================================
DUPLICATE CHECK
======================================================================

Patients:
Duplicate rows: 0

Readmission:
Duplicate rows: 0

Inpatient Discharges:
Duplicate rows: 0

======================================================================
FINAL DUPLICATE CHECK
======================================================================
Patients: 0
Readmission: 0
Inpatient Discharges: 0

======================================================================
DUPLICATE HANDLING COMPLETED
======================================================================
Patients: (1000, 7)
Readmission: (10000, 26)
Inpatient Discharges: (1797442, 33)

Files saved to:
/content/drive/MyDrive/RAW/Duplicates_Checked

In [12]:
input_folder = "/content/drive/MyDrive/RAW/Duplicates_Checked"

# LOAD DATASETS

patients = pd.read_csv(
    os.path.join(
        input_folder,
        "patients_duplicates_checked.csv"
    )
)

readmission = pd.read_csv(
    os.path.join(
        input_folder,
        "readmission_duplicates_checked.csv"
    )
)

inpatient = pd.read_csv(
    os.path.join(
        input_folder,
        "inpatient_discharges_duplicates_checked.csv"
    ),
    low_memory=False
)

# ============================================================
# DISPLAY COLUMNS
# ============================================================

print("="*70)
print("PATIENTS DATASET COLUMNS")
print("="*70)

for i, col in enumerate(patients.columns, 1):
    print(i, "->", col)


print("\n" + "="*70)
print("READMISSION DATASET COLUMNS")
print("="*70)

for i, col in enumerate(readmission.columns, 1):
    print(i, "->", col)


print("\n" + "="*70)
print("INPATIENT DISCHARGES DATASET COLUMNS")
print("="*70)

for i, col in enumerate(inpatient.columns, 1):
    print(i, "->", col)

# DATA TYPES

print("\n" + "="*70)
print("READMISSION DATA TYPES")
print("="*70)

print(readmission.dtypes)


print("\n" + "="*70)
print("INPATIENT DATA TYPES")
print("="*70)

print(inpatient.dtypes)

======================================================================
PATIENTS DATASET COLUMNS
======================================================================
1 -> patient_id
2 -> name
3 -> age
4 -> arrival_date
5 -> departure_date
6 -> service
7 -> satisfaction

======================================================================
READMISSION DATASET COLUMNS
======================================================================
1 -> hospital_name
2 -> admission_date
3 -> hospital_id
4 -> hospital_beds_available
5 -> occupied_beds
6 -> hospital_ward
7 -> patient_id
8 -> patient_gender
9 -> patient_age
10 -> patient_race
11 -> patient_sat_score
12 -> patient_first_initial
13 -> patient_last_name
14 -> patient_waittime
15 -> department_referral
16 -> time_slot
17 -> doctor_id
18 -> doctor_name
19 -> doctor_specialty
20 -> patient_assigned_doctor
21 -> patient_checkin_date
22 -> patient_checkout_date
23 -> patient_disease
24 -> patient_length_of_stay
25 -> discharge_status
26 -> readmission

======================================================================
INPATIENT DISCHARGES DATASET COLUMNS
======================================================================
1 -> hospital_service_area
2 -> hospital_county
3 -> operating_certificate_number
4 -> permanent_facility_id
5 -> facility_name
6 -> age_group
7 -> zip_code___3_digits
8 -> gender
9 -> race
10 -> ethnicity
11 -> length_of_stay
12 -> type_of_admission
13 -> patient_disposition
14 -> discharge_year
15 -> ccsr_diagnosis_code
16 -> ccsr_diagnosis_description
17 -> ccsr_procedure_code
18 -> ccsr_procedure_description
19 -> apr_drg_code
20 -> apr_drg_description
21 -> apr_mdc_code
22 -> apr_mdc_description
23 -> apr_severity_of_illness_code
24 -> apr_severity_of_illness_description
25 -> apr_risk_of_mortality
26 -> apr_medical_surgical_description
27 -> payment_typology_1
28 -> payment_typology_2
29 -> payment_typology_3
30 -> birth_weight
31 -> emergency_department_indicator
32 -> total_charges
33 -> total_costs

======================================================================
READMISSION DATA TYPES
======================================================================
hospital_name               object
admission_date              object
hospital_id                 object
hospital_beds_available      int64
occupied_beds                int64
hospital_ward               object
patient_id                  object
patient_gender              object
patient_age                float64
patient_race                object
patient_sat_score          float64
patient_first_initial       object
patient_last_name           object
patient_waittime           float64
department_referral         object
time_slot                   object
doctor_id                   object
doctor_name                 object
doctor_specialty            object
patient_assigned_doctor       bool
patient_checkin_date        object
patient_checkout_date       object
patient_disease             object
patient_length_of_stay     float64
discharge_status            object
readmission                float64
dtype: object

======================================================================
INPATIENT DATA TYPES
======================================================================
hospital_service_area                   object
hospital_county                         object
operating_certificate_number            object
permanent_facility_id                   object
facility_name                           object
age_group                               object
zip_code___3_digits                     object
gender                                  object
race                                    object
ethnicity                               object
length_of_stay                         float64
type_of_admission                       object
patient_disposition                     object
discharge_year                          object
ccsr_diagnosis_code                     object
ccsr_diagnosis_description              object
ccsr_procedure_code                     object
ccsr_procedure_description              object
apr_drg_code                             int64
apr_drg_description                     object
apr_mdc_code                             int64
apr_mdc_description                     object
apr_severity_of_illness_code           float64
apr_severity_of_illness_description     object
apr_risk_of_mortality                   object
apr_medical_surgical_description        object
payment_typology_1                      object
payment_typology_2                      object
payment_typology_3                      object
birth_weight                           float64
emergency_department_indicator          object
total_charges                          float64
total_costs                            float64
dtype: object

In [13]:
input_folder = "/content/drive/MyDrive/RAW/Duplicates_Checked"
output_folder = "/content/drive/MyDrive/RAW/Analytical_Datasets"

os.makedirs(output_folder, exist_ok=True)

# LOAD DATASETS

patients = pd.read_csv(
    os.path.join(
        input_folder,
        "patients_duplicates_checked.csv"
    )
)

readmission = pd.read_csv(
    os.path.join(
        input_folder,
        "readmission_duplicates_checked.csv"
    )
)

inpatient = pd.read_csv(
    os.path.join(
        input_folder,
        "inpatient_discharges_duplicates_checked.csv"
    ),
    low_memory=False
)

# 1. HOSPITAL OVERVIEW DATASET
# Grain: One row = one patient admission
# Source: Readmission dataset

hospital_overview = readmission.copy()

# Select admission-level fields
hospital_overview = hospital_overview[
    [
        "hospital_id",
        "hospital_name",
        "patient_id",
        "admission_date",
        "patient_gender",
        "patient_age",
        "patient_race",
        "patient_disease",
        "patient_length_of_stay",
        "discharge_status",
        "readmission"
    ]
].copy()

# Rename fields for consistency
hospital_overview.rename(
    columns={
        "patient_gender": "gender",
        "patient_age": "age",
        "patient_race": "race",
        "patient_disease": "disease",
        "patient_length_of_stay": "length_of_stay"
    },
    inplace=True
)

hospital_overview.to_csv(
    os.path.join(
        output_folder,
        "hospital_overview_dataset.csv"
    ),
    index=False
)

print("Hospital Overview:", hospital_overview.shape)

# 2. PATIENT FLOW DATASET
# Grain: One row = one patient movement/event
# Source: Readmission dataset

patient_flow = readmission.copy()

patient_flow = patient_flow[
    [
        "hospital_id",
        "hospital_name",
        "patient_id",
        "admission_date",
        "patient_checkin_date",
        "patient_checkout_date",
        "hospital_ward",
        "department_referral",
        "time_slot",
        "patient_waittime",
        "patient_assigned_doctor",
        "discharge_status"
    ]
].copy()

patient_flow.rename(
    columns={
        "patient_waittime": "wait_time",
        "patient_assigned_doctor": "assigned_doctor"
    },
    inplace=True
)

patient_flow.to_csv(
    os.path.join(
        output_folder,
        "patient_flow_dataset.csv"
    ),
    index=False
)

print("Patient Flow:", patient_flow.shape)

# 3. DEPARTMENT ANALYTICS DATASET
# Grain: Hospital + Department + Day
#
# Department referral is the available department-level field.
# Since the readmission dataset contains admission dates,
# aggregate by hospital + department + admission date.

department_analytics = (
    readmission
    .groupby(
        [
            "hospital_id",
            "hospital_name",
            "department_referral",
            "admission_date"
        ],
        dropna=False
    )
    .agg(
        total_admissions=("patient_id", "nunique"),
        average_age=("patient_age", "mean"),
        average_wait_time=("patient_waittime", "mean"),
        average_length_of_stay=("patient_length_of_stay", "mean"),
        average_satisfaction=("patient_sat_score", "mean"),
        readmitted_patients=("readmission", "sum")
    )
    .reset_index()
)

department_analytics.to_csv(
    os.path.join(
        output_folder,
        "department_analytics_dataset.csv"
    ),
    index=False
)

print("Department Analytics:", department_analytics.shape)

# 4. RESOURCE UTILIZATION DATASET
# Grain: Hospital + Department + Day + Resource Type
#
# Available resource fields in the readmission dataset:
# hospital beds available
# occupied beds
#
# We create a daily hospital/ward-level resource table.

resource_utilization = (
    readmission[
        [
            "hospital_id",
            "hospital_name",
            "hospital_ward",
            "admission_date",
            "hospital_beds_available",
            "occupied_beds"
        ]
    ]
    .groupby(
        [
            "hospital_id",
            "hospital_name",
            "hospital_ward",
            "admission_date"
        ],
        dropna=False
    )
    .agg(
        available_beds=("hospital_beds_available", "max"),
        occupied_beds=("occupied_beds", "max")
    )
    .reset_index()
)

# Calculate utilization percentage
resource_utilization["bed_utilization_rate"] = (
    resource_utilization["occupied_beds"]
    / resource_utilization["available_beds"]
    * 100
)

resource_utilization.to_csv(
    os.path.join(
        output_folder,
        "resource_utilization_dataset.csv"
    ),
    index=False
)

print("Resource Utilization:", resource_utilization.shape)

# FINAL VALIDATION

print("\n" + "="*70)
print("FOUR ANALYTICAL DATASETS CREATED")
print("="*70)

print("\n1. Hospital Overview")
print(hospital_overview.head())

print("\n2. Patient Flow")
print(patient_flow.head())

print("\n3. Department Analytics")
print(department_analytics.head())

print("\n4. Resource Utilization")
print(resource_utilization.head())

print("\n" + "="*70)
print("FILES SAVED TO")
print("="*70)

print(output_folder)

Hospital Overview: (10000, 11)
Patient Flow: (10000, 12)
Department Analytics: (9944, 10)
Resource Utilization: (9838, 7)

======================================================================
FOUR ANALYTICAL DATASETS CREATED
======================================================================

1. Hospital Overview
  hospital_id               hospital_name patient_id admission_date  gender  \
0   HOSP-3946  The Johns Hopkins Hospital   PAT-1421     2024-01-30  female
1   HOSP-7147  The Johns Hopkins Hospital   PAT-4922     2022-03-20    male
2   HOSP-4174  The Johns Hopkins Hospital   PAT-9804     2021-07-13  female
3   HOSP-2466  The Johns Hopkins Hospital   PAT-5622     2021-01-26    male
4   HOSP-3014  The Johns Hopkins Hospital   PAT-3314            NaN    male

    age      race                             disease  length_of_stay  \
0  48.0     asian                   Anxiety Disorders             6.0
1  40.0     black       Urinary Tract Infection (UTI)             2.0
2  74.0     black  Hypertension (High Blood Pressure)            17.0
3  82.0  hispanic                           Arthritis            28.0
4  62.0  hispanic                              Cancer            16.0

  discharge_status  readmission
0         deceased          1.0
1         deceased          1.0
2        recovered          0.0
3        recovered          0.0
4      transferred          1.0

2. Patient Flow
  hospital_id               hospital_name patient_id admission_date  \
0   HOSP-3946  The Johns Hopkins Hospital   PAT-1421     2024-01-30
1   HOSP-7147  The Johns Hopkins Hospital   PAT-4922     2022-03-20
2   HOSP-4174  The Johns Hopkins Hospital   PAT-9804     2021-07-13
3   HOSP-2466  The Johns Hopkins Hospital   PAT-5622     2021-01-26
4   HOSP-3014  The Johns Hopkins Hospital   PAT-3314            NaN

  patient_checkin_date patient_checkout_date hospital_ward  \
0           2024-07-14            2024-07-19     maternity
1           2024-07-19                   NaN           icu
2           2024-07-20            2024-06-29    pediatrics
3           2024-06-25            2024-07-16    pediatrics
4           2024-07-21            2024-07-19       surgery

     department_referral    time_slot  wait_time  assigned_doctor  \
0  urology or nephrology  02:34:00 PM      120.0            False
1              neurology  04:07:00 PM       60.0            False
2              neurology  07:16:00 PM      120.0            False
3       gastroenterology  07:27:00 AM       75.0            False
4            dermatology  01:54:00 PM       90.0            False

  discharge_status
0         deceased
1         deceased
2        recovered
3        recovered
4      transferred

3. Department Analytics
  hospital_id               hospital_name     department_referral  \
0   HOSP-1000  The Johns Hopkins Hospital        gastroenterology
1   HOSP-1000  The Johns Hopkins Hospital      infectious disease
2   HOSP-1003  The Johns Hopkins Hospital               neurology
3   HOSP-1004  The Johns Hopkins Hospital  allergy and immunology
4   HOSP-1004  The Johns Hopkins Hospital               neurology

  admission_date  total_admissions  average_age  average_wait_time  \
0            NaN                 1         88.0               60.0
1     2022-12-18                 1         64.0               30.0
2     2020-11-28                 1         41.0               15.0
3     2022-06-15                 1         68.0               45.0
4            NaN                 1         49.0               75.0

   average_length_of_stay  average_satisfaction  readmitted_patients
0                    28.0                1390.0                  1.0
1                     1.0                 500.0                  1.0
2                    17.0                1280.0                  0.0
3                     8.0                 380.0                  0.0
4                     8.0                 880.0                  0.0

4. Resource Utilization
  hospital_id               hospital_name hospital_ward admission_date  \
0   HOSP-1000  The Johns Hopkins Hospital            er            NaN
1   HOSP-1000  The Johns Hopkins Hospital           icu     2022-12-18
2   HOSP-1003  The Johns Hopkins Hospital    pediatrics     2020-11-28
3   HOSP-1004  The Johns Hopkins Hospital           icu     2022-06-15
4   HOSP-1004  The Johns Hopkins Hospital     maternity            NaN

   available_beds  occupied_beds  bed_utilization_rate
0             390            320             82.051282
1             110            290            263.636364
2             320            370            115.625000
3             410            380             92.682927
4             250            200             80.000000

======================================================================
FILES SAVED TO
======================================================================
/content/drive/MyDrive/RAW/Analytical_Datasets

In [14]:
folder = "/content/drive/MyDrive/RAW/Analytical_Datasets"

# Load analytical datasets
hospital_overview = pd.read_csv(
    os.path.join(folder, "hospital_overview_dataset.csv")
)

patient_flow = pd.read_csv(
    os.path.join(folder, "patient_flow_dataset.csv")
)

department_analytics = pd.read_csv(
    os.path.join(folder, "department_analytics_dataset.csv")
)

resource_utilization = pd.read_csv(
    os.path.join(folder, "resource_utilization_dataset.csv")
)


# ============================================================
# 1. HOSPITAL OVERVIEW <-> PATIENT FLOW
# Validate common patient and hospital IDs
# ============================================================

overview_patients = set(hospital_overview["patient_id"].dropna())
flow_patients = set(patient_flow["patient_id"].dropna())

overview_hospitals = set(hospital_overview["hospital_id"].dropna())
flow_hospitals = set(patient_flow["hospital_id"].dropna())

print("=" * 70)
print("RELATIONSHIP VALIDATION")
print("=" * 70)

print("\n1. HOSPITAL OVERVIEW ↔ PATIENT FLOW")

print("Common Patient IDs:",
      len(overview_patients.intersection(flow_patients)))

print("Common Hospital IDs:",
      len(overview_hospitals.intersection(flow_hospitals)))

# 2. HOSPITAL OVERVIEW <-> DEPARTMENT ANALYTICS
# Validate hospital IDs

department_hospitals = set(
    department_analytics["hospital_id"].dropna()
)

print("\n2. HOSPITAL OVERVIEW ↔ DEPARTMENT ANALYTICS")

print(
    "Common Hospital IDs:",
    len(overview_hospitals.intersection(department_hospitals))
)

# 3. HOSPITAL OVERVIEW <-> RESOURCE UTILIZATION
# Validate hospital IDs

resource_hospitals = set(
    resource_utilization["hospital_id"].dropna()
)

print("\n3. HOSPITAL OVERVIEW ↔ RESOURCE UTILIZATION")

print(
    "Common Hospital IDs:",
    len(overview_hospitals.intersection(resource_hospitals))
)

# 4. CHECK KEY NULL VALUES

print("\n" + "=" * 70)
print("KEY NULL VALUE CHECK")
print("=" * 70)

print("\nHospital Overview:")
print(hospital_overview[
    ["hospital_id", "patient_id", "admission_date"]
].isnull().sum())

print("\nPatient Flow:")
print(patient_flow[
    ["hospital_id", "patient_id", "admission_date"]
].isnull().sum())

print("\nDepartment Analytics:")
print(department_analytics[
    ["hospital_id", "department_referral", "admission_date"]
].isnull().sum())

print("\nResource Utilization:")
print(resource_utilization[
    ["hospital_id", "hospital_ward", "admission_date"]
].isnull().sum())

# 5. VALIDATE BED UTILIZATION

invalid_utilization = resource_utilization[
    resource_utilization["bed_utilization_rate"] > 100
]

print("\n" + "=" * 70)
print("BED UTILIZATION VALIDATION")
print("=" * 70)

print(
    "Records with utilization > 100%:",
    len(invalid_utilization)
)

print("\nSample invalid records:")
display(invalid_utilization.head())

# 6. VALIDATE SATISFACTION VALUES

print("\n" + "=" * 70)
print("SATISFACTION SCORE VALIDATION")
print("=" * 70)

print("Minimum satisfaction:",
      department_analytics["average_satisfaction"].min())

print("Maximum satisfaction:",
      department_analytics["average_satisfaction"].max())

# FINAL SUMMARY

print("\n" + "=" * 70)
print("RELATIONSHIP VALIDATION COMPLETED")
print("=" * 70)

print("Hospital Overview:", hospital_overview.shape)
print("Patient Flow:", patient_flow.shape)
print("Department Analytics:", department_analytics.shape)
print("Resource Utilization:", resource_utilization.shape)

======================================================================
RELATIONSHIP VALIDATION
======================================================================

1. HOSPITAL OVERVIEW ↔ PATIENT FLOW
Common Patient IDs: 6022
Common Hospital IDs: 6074

2. HOSPITAL OVERVIEW ↔ DEPARTMENT ANALYTICS
Common Hospital IDs: 6074

3. HOSPITAL OVERVIEW ↔ RESOURCE UTILIZATION
Common Hospital IDs: 6074

======================================================================
KEY NULL VALUE CHECK
======================================================================

Hospital Overview:
hospital_id          0
patient_id           0
admission_date    3919
dtype: int64

Patient Flow:
hospital_id          0
patient_id           0
admission_date    3919
dtype: int64

Department Analytics:
hospital_id               0
department_referral       0
admission_date         3863
dtype: int64

Resource Utilization:
hospital_id          0
hospital_ward        0
admission_date    3757
dtype: int64

======================================================================
BED UTILIZATION VALIDATION
======================================================================
Records with utilization > 100%: 2729

Sample invalid records:

,hospital_id,hospital_name,hospital_ward,admission_date,available_beds,occupied_beds,bed_utilization_rate
1,HOSP-1000,The Johns Hopkins Hospital,icu,2022-12-18,110,290,263.636364
2,HOSP-1003,The Johns Hopkins Hospital,pediatrics,2020-11-28,320,370,115.625000
6,HOSP-1005,The Johns Hopkins Hospital,icu,NaN,260,340,130.769231
15,HOSP-1010,The Johns Hopkins Hospital,surgery,2023-07-23,270,330,122.222222
16,HOSP-1011,The Johns Hopkins Hospital,maternity,2022-07-22,120,140,116.666667

======================================================================
SATISFACTION SCORE VALIDATION
======================================================================
Minimum satisfaction: 100.0
Maximum satisfaction: 1600.0

======================================================================
RELATIONSHIP VALIDATION COMPLETED
======================================================================
Hospital Overview: (10000, 11)
Patient Flow: (10000, 12)
Department Analytics: (9944, 10)
Resource Utilization: (9838, 7)

In [15]:
folder = "/content/drive/MyDrive/RAW/Analytical_Datasets"

# Load analytical datasets
hospital_overview = pd.read_csv(
    os.path.join(folder, "hospital_overview_dataset.csv")
)

patient_flow = pd.read_csv(
    os.path.join(folder, "patient_flow_dataset.csv")
)

department_analytics = pd.read_csv(
    os.path.join(folder, "department_analytics_dataset.csv")
)

resource_utilization = pd.read_csv(
    os.path.join(folder, "resource_utilization_dataset.csv")
)

# 1. CHECK LINKING KEYS EXIST

print("=" * 70)
print("LINKING KEY VALIDATION")
print("=" * 70)

datasets = {
    "Hospital Overview": hospital_overview,
    "Patient Flow": patient_flow,
    "Department Analytics": department_analytics,
    "Resource Utilization": resource_utilization
}

required_keys = {
    "Hospital Overview": ["hospital_id", "patient_id", "admission_date"],
    "Patient Flow": ["hospital_id", "patient_id", "admission_date"],
    "Department Analytics": [
        "hospital_id",
        "department_referral",
        "admission_date"
    ],
    "Resource Utilization": [
        "hospital_id",
        "hospital_ward",
        "admission_date"
    ]
}

for name, df in datasets.items():

    print("\n" + name)

    for key in required_keys[name]:

        if key in df.columns:
            print("✓", key, "exists")
        else:
            print("✗", key, "MISSING")

# 2. CHECK NULL VALUES IN LINKING KEYS

print("\n" + "=" * 70)
print("NULL VALUES IN LINKING KEYS")
print("=" * 70)

for name, df in datasets.items():

    print("\n" + name)

    for key in required_keys[name]:

        if key in df.columns:

            null_count = df[key].isnull().sum()

            print(
                key,
                "->",
                null_count,
                "null values"
            )

# 3. HOSPITAL ID RELATIONSHIPS

print("\n" + "=" * 70)
print("HOSPITAL ID RELATIONSHIPS")
print("=" * 70)

overview_hospitals = set(
    hospital_overview["hospital_id"].dropna()
)

flow_hospitals = set(
    patient_flow["hospital_id"].dropna()
)

department_hospitals = set(
    department_analytics["hospital_id"].dropna()
)

resource_hospitals = set(
    resource_utilization["hospital_id"].dropna()
)

print(
    "Overview ↔ Patient Flow:",
    len(overview_hospitals & flow_hospitals),
    "common hospitals"
)

print(
    "Overview ↔ Department Analytics:",
    len(overview_hospitals & department_hospitals),
    "common hospitals"
)

print(
    "Overview ↔ Resource Utilization:",
    len(overview_hospitals & resource_hospitals),
    "common hospitals"
)

# 4. PATIENT ID RELATIONSHIP

print("\n" + "=" * 70)
print("PATIENT ID RELATIONSHIP")
print("=" * 70)

overview_patients = set(
    hospital_overview["patient_id"].dropna()
)

flow_patients = set(
    patient_flow["patient_id"].dropna()
)

common_patients = overview_patients & flow_patients

print(
    "Hospital Overview patients:",
    len(overview_patients)
)

print(
    "Patient Flow patients:",
    len(flow_patients)
)

print(
    "Common Patient IDs:",
    len(common_patients)
)

# 5. DEPARTMENT VALUES

print("\n" + "=" * 70)
print("DEPARTMENT VALIDATION")
print("=" * 70)

departments = department_analytics[
    "department_referral"
].dropna().unique()

print("Number of standardized departments:", len(departments))

print("\nDepartments:")
for department in sorted(departments):
    print("-", department)

# 6. RESOURCE VALUES

print("\n" + "=" * 70)
print("RESOURCE VALIDATION")
print("=" * 70)

wards = resource_utilization[
    "hospital_ward"
].dropna().unique()

print("Number of standardized wards:", len(wards))

print("\nHospital Wards:")
for ward in sorted(wards):
    print("-", ward)

# 7. DATE VALIDATION

print("\n" + "=" * 70)
print("DATE VALIDATION")
print("=" * 70)

for name, df in datasets.items():

    if "admission_date" in df.columns:

        valid_dates = pd.to_datetime(
            df["admission_date"],
            errors="coerce"
        )

        print(
            name,
            "-> valid dates:",
            valid_dates.notna().sum(),
            "| missing/invalid:",
            valid_dates.isna().sum()
        )

# 8. CHECK FOR DUPLICATE LINKING KEYS

print("\n" + "=" * 70)
print("DUPLICATE LINKING KEY CHECK")
print("=" * 70)

print(
    "Hospital Overview - patient_id duplicates:",
    hospital_overview["patient_id"].duplicated().sum()
)

print(
    "Patient Flow - patient_id duplicates:",
    patient_flow["patient_id"].duplicated().sum()
)

print(
    "Department Analytics - hospital + department + date duplicates:",
    department_analytics.duplicated(
        subset=[
            "hospital_id",
            "department_referral",
            "admission_date"
        ]
    ).sum()
)

print(
    "Resource Utilization - hospital + ward + date duplicates:",
    resource_utilization.duplicated(
        subset=[
            "hospital_id",
            "hospital_ward",
            "admission_date"
        ]
    ).sum()
)

# FINAL MESSAGE

print("\n" + "=" * 70)
print("RELATIONSHIP / LINKING KEY VALIDATION COMPLETED")
print("=" * 70)

======================================================================
LINKING KEY VALIDATION
======================================================================

Hospital Overview
✓ hospital_id exists
✓ patient_id exists
✓ admission_date exists

Patient Flow
✓ hospital_id exists
✓ patient_id exists
✓ admission_date exists

Department Analytics
✓ hospital_id exists
✓ department_referral exists
✓ admission_date exists

Resource Utilization
✓ hospital_id exists
✓ hospital_ward exists
✓ admission_date exists

======================================================================
NULL VALUES IN LINKING KEYS
======================================================================

Hospital Overview
hospital_id -> 0 null values
patient_id -> 0 null values
admission_date -> 3919 null values

Patient Flow
hospital_id -> 0 null values
patient_id -> 0 null values
admission_date -> 3919 null values

Department Analytics
hospital_id -> 0 null values
department_referral -> 0 null values
admission_date -> 3863 null values

Resource Utilization
hospital_id -> 0 null values
hospital_ward -> 0 null values
admission_date -> 3757 null values

======================================================================
HOSPITAL ID RELATIONSHIPS
======================================================================
Overview ↔ Patient Flow: 6074 common hospitals
Overview ↔ Department Analytics: 6074 common hospitals
Overview ↔ Resource Utilization: 6074 common hospitals

======================================================================
PATIENT ID RELATIONSHIP
======================================================================
Hospital Overview patients: 6022
Patient Flow patients: 6022
Common Patient IDs: 6022

======================================================================
DEPARTMENT VALIDATION
======================================================================
Number of standardized departments: 19

Departments:
- allergy and immunology
- cardiology
- cardiology or internal medicine
- dermatology
- endocrinology
- gastroenterology
- hepatology
- hepatology or gastroenterology
- infectious disease
- infectious disease or internal medicine
- nephrology
- neurology
- oncology
- psychiatry
- pulmonology
- pulmonology or allergy and immunology
- pulmonology or infectious disease
- rheumatology
- urology or nephrology

======================================================================
RESOURCE VALIDATION
======================================================================
Number of standardized wards: 5

Hospital Wards:
- er
- icu
- maternity
- pediatrics
- surgery

======================================================================
DATE VALIDATION
======================================================================
Hospital Overview -> valid dates: 6081 | missing/invalid: 3919
Patient Flow -> valid dates: 6081 | missing/invalid: 3919
Department Analytics -> valid dates: 6081 | missing/invalid: 3863
Resource Utilization -> valid dates: 6081 | missing/invalid: 3757

======================================================================
DUPLICATE LINKING KEY CHECK
======================================================================
Hospital Overview - patient_id duplicates: 3978
Patient Flow - patient_id duplicates: 3978
Department Analytics - hospital + department + date duplicates: 0
Resource Utilization - hospital + ward + date duplicates: 0

======================================================================
RELATIONSHIP / LINKING KEY VALIDATION COMPLETED
======================================================================

In [16]:
folder = "/content/drive/MyDrive/RAW/Analytical_Datasets"

hospital_overview = pd.read_csv(
    os.path.join(
        folder,
        "hospital_overview_dataset.csv"
    )
)

# KPI 1: TOTAL ADMISSIONS

total_admissions = len(hospital_overview)

print("=" * 60)
print("KPI 1: TOTAL ADMISSIONS")
print("=" * 60)

print("Total Admissions:", total_admissions)

============================================================
KPI 1: TOTAL ADMISSIONS
============================================================
Total Admissions: 10000

In [17]:
folder = "/content/drive/MyDrive/RAW/Duplicates_Checked"

readmission = pd.read_csv(
    os.path.join(
        folder,
        "readmission_duplicates_checked.csv"
    )
)

# KPI 2: OCCUPANCY RATE

total_beds = readmission["hospital_beds_available"].sum()
occupied_beds = readmission["occupied_beds"].sum()

occupancy_rate = (
    occupied_beds / total_beds
) * 100

print("=" * 60)
print("KPI 2: OCCUPANCY RATE")
print("=" * 60)

print("Total Beds:", total_beds)
print("Occupied Beds:", occupied_beds)
print("Occupancy Rate:", round(occupancy_rate, 2), "%")

============================================================
KPI 2: OCCUPANCY RATE
============================================================
Total Beds: 2991110
Occupied Beds: 1990850
Occupancy Rate: 66.56 %

In [18]:
folder = "/content/drive/MyDrive/RAW/Analytical_Datasets"

hospital_overview = pd.read_csv(
    os.path.join(
        folder,
        "hospital_overview_dataset.csv"
    )
)

# KPI 3: AVERAGE LENGTH OF STAY

average_los = hospital_overview["length_of_stay"].mean()

print("=" * 60)
print("KPI 3: AVERAGE LENGTH OF STAY")
print("=" * 60)

print("Average Length of Stay:",
      round(average_los, 2),
      "days")

============================================================
KPI 3: AVERAGE LENGTH OF STAY
============================================================
Average Length of Stay: 15.51 days

In [19]:
hospital_overview = pd.read_csv(
    os.path.join(
        folder,
        "hospital_overview_dataset.csv"
    )
)

# KPI 4: READMISSION RATE

# Eligible patients = records where readmission is known
eligible_patients = hospital_overview["readmission"].notna().sum()

# Readmitted patients = readmission value of 1
readmitted_patients = (
    hospital_overview["readmission"] == 1
).sum()

# Calculate rate
readmission_rate = (
    readmitted_patients / eligible_patients
) * 100

print("=" * 60)
print("KPI 4: READMISSION RATE")
print("=" * 60)

print("Eligible Patients:", eligible_patients)
print("Readmitted Patients:", readmitted_patients)
print("Readmission Rate:", round(readmission_rate, 2), "%")

============================================================
KPI 4: READMISSION RATE
============================================================
Eligible Patients: 10000
Readmitted Patients: 4142
Readmission Rate: 41.42 %

In [20]:
resource_utilization = pd.read_csv(
    os.path.join(folder, "resource_utilization_dataset.csv")
)

total_available_beds = resource_utilization["available_beds"].sum()
total_occupied_beds = resource_utilization["occupied_beds"].sum()

bed_utilization_rate = (
    total_occupied_beds / total_available_beds
) * 100

print("=" * 60)
print("KPI 5: BED UTILIZATION RATE")
print("=" * 60)
print("Total Available Beds:", total_available_beds)
print("Total Occupied Beds:", total_occupied_beds)
print("Bed Utilization Rate:", round(bed_utilization_rate, 2), "%")

============================================================
KPI 5: BED UTILIZATION RATE
============================================================
Total Available Beds: 2953930
Total Occupied Beds: 1969490
Bed Utilization Rate: 66.67 %

In [21]:
department = pd.read_csv(
    os.path.join(folder, "department_analytics_dataset.csv")
)

print("=" * 60)
print("DEPARTMENT KPI METRIC RANGES")
print("=" * 60)

print("\nAverage Wait Time:")
print("Min:", department["average_wait_time"].min())
print("Max:", department["average_wait_time"].max())

print("\nAverage Length of Stay:")
print("Min:", department["average_length_of_stay"].min())
print("Max:", department["average_length_of_stay"].max())

print("\nAverage Satisfaction:")
print("Min:", department["average_satisfaction"].min())
print("Max:", department["average_satisfaction"].max())

print("\nReadmission Rate by Department:")
department["department_readmission_rate"] = (
    department["readmitted_patients"]
    / department["total_admissions"]
) * 100

print("Min:", department["department_readmission_rate"].min())
print("Max:", department["department_readmission_rate"].max())

============================================================
DEPARTMENT KPI METRIC RANGES
============================================================

Average Wait Time:
Min: 15.0
Max: 120.0

Average Length of Stay:
Min: 1.0
Max: 30.0

Average Satisfaction:
Min: 100.0
Max: 1600.0

Readmission Rate by Department:
Min: 0.0
Max: 100.0

In [22]:
department = pd.read_csv(
    os.path.join(folder, "department_analytics_dataset.csv")
)

# Calculate department readmission rate
department["department_readmission_rate"] = (
    department["readmitted_patients"]
    / department["total_admissions"]
) * 100


# Min-Max Normalization
# Higher value = better
department["satisfaction_score"] = (
    (department["average_satisfaction"] -
     department["average_satisfaction"].min())
    /
    (department["average_satisfaction"].max() -
     department["average_satisfaction"].min())
) * 100


# Lower value = better
department["wait_time_score"] = (
    (department["average_wait_time"].max() -
     department["average_wait_time"])
    /
    (department["average_wait_time"].max() -
     department["average_wait_time"].min())
) * 100


# Lower value = better
department["los_score"] = (
    (department["average_length_of_stay"].max() -
     department["average_length_of_stay"])
    /
    (department["average_length_of_stay"].max() -
     department["average_length_of_stay"].min())
) * 100


# Lower value = better
department["readmission_score"] = (
    (department["department_readmission_rate"].max() -
     department["department_readmission_rate"])
    /
    (department["department_readmission_rate"].max() -
     department["department_readmission_rate"].min())
) * 100


# Weighted Department Efficiency Score
department["department_efficiency_score"] = (
    department["satisfaction_score"] * 0.30
    + department["wait_time_score"] * 0.25
    + department["los_score"] * 0.20
    + department["readmission_score"] * 0.25
)


print("=" * 60)
print("KPI 6: DEPARTMENT EFFICIENCY SCORE")
print("=" * 60)

print("\nMinimum Efficiency Score:",
      round(department["department_efficiency_score"].min(), 2))

print("Maximum Efficiency Score:",
      round(department["department_efficiency_score"].max(), 2))

print("Average Efficiency Score:",
      round(department["department_efficiency_score"].mean(), 2))

print("\nTop 5 Departments:")
print(
    department[
        ["department_referral", "department_efficiency_score"]
    ]
    .sort_values("department_efficiency_score", ascending=False)
    .head(5)
    .to_string(index=False)
)

============================================================
KPI 6: DEPARTMENT EFFICIENCY SCORE
============================================================

Minimum Efficiency Score: 1.29
Maximum Efficiency Score: 99.4
Average Efficiency Score: 52.03

Top 5 Departments:
                    department_referral  department_efficiency_score
                             hepatology                    99.400000
                             hepatology                    99.200000
                             psychiatry                    98.910345
infectious disease or internal medicine                    98.600000
                             hepatology                    98.200000

In [23]:
folder = "/content/drive/MyDrive/RAW/Analytical_Datasets"

# Load datasets
overview = pd.read_csv(
    os.path.join(folder, "hospital_overview_dataset.csv")
)

resource = pd.read_csv(
    os.path.join(folder, "resource_utilization_dataset.csv")
)

department = pd.read_csv(
    os.path.join(folder, "department_analytics_dataset.csv")
)

# ---------------- KPI 1 ----------------
total_admissions = overview["patient_id"].count()

# ---------------- KPI 2 ----------------
total_beds = overview["hospital_beds_available"] if "hospital_beds_available" in overview.columns else None

# Use resource dataset for bed calculation
available_beds = resource["available_beds"].sum()
occupied_beds = resource["occupied_beds"].sum()

occupancy_rate = (occupied_beds / available_beds) * 100

# ---------------- KPI 3 ----------------
average_los = overview["length_of_stay"].mean()

# ---------------- KPI 4 ----------------
eligible_patients = overview["readmission"].notna().sum()
readmitted_patients = (overview["readmission"] == 1).sum()

readmission_rate = (
    readmitted_patients / eligible_patients
) * 100

# ---------------- KPI 5 ----------------
bed_utilization_rate = (
    occupied_beds / available_beds
) * 100

# ---------------- KPI 6 ----------------
department["department_readmission_rate"] = (
    department["readmitted_patients"]
    / department["total_admissions"]
) * 100

department["satisfaction_score"] = (
    (department["average_satisfaction"]
     - department["average_satisfaction"].min())
    /
    (department["average_satisfaction"].max()
     - department["average_satisfaction"].min())
) * 100

department["wait_time_score"] = (
    (department["average_wait_time"].max()
     - department["average_wait_time"])
    /
    (department["average_wait_time"].max()
     - department["average_wait_time"].min())
) * 100

department["los_score"] = (
    (department["average_length_of_stay"].max()
     - department["average_length_of_stay"])
    /
    (department["average_length_of_stay"].max()
     - department["average_length_of_stay"].min())
) * 100

department["readmission_score"] = (
    (department["department_readmission_rate"].max()
     - department["department_readmission_rate"])
    /
    (department["department_readmission_rate"].max()
     - department["department_readmission_rate"].min())
) * 100

department["department_efficiency_score"] = (
    department["satisfaction_score"] * 0.30
    + department["wait_time_score"] * 0.25
    + department["los_score"] * 0.20
    + department["readmission_score"] * 0.25
)

efficiency_average = department["department_efficiency_score"].mean()


# ---------------- VALIDATION TABLE ----------------

validation = pd.DataFrame({
    "KPI": [
        "Total Admissions",
        "Occupancy Rate",
        "Average Length of Stay",
        "Readmission Rate",
        "Bed Utilization Rate",
        "Department Efficiency Score"
    ],

    "Calculated Value": [
        total_admissions,
        round(occupancy_rate, 2),
        round(average_los, 2),
        round(readmission_rate, 2),
        round(bed_utilization_rate, 2),
        round(efficiency_average, 2)
    ],

    "Formula / Definition": [
        "Count of admission records",
        "Occupied Beds / Available Beds × 100",
        "Average Length of Stay",
        "Readmitted Patients / Eligible Patients × 100",
        "Occupied Beds / Available Beds × 100",
        "Weighted normalized score: Satisfaction 30%, Wait Time 25%, LOS 20%, Readmission 25%"
    ]
})

print("=" * 80)
print("KPI VALIDATION TABLE")
print("=" * 80)

print(validation.to_string(index=False))

================================================================================
KPI VALIDATION TABLE
================================================================================
                        KPI  Calculated Value                                                                 Formula / Definition
           Total Admissions          10000.00                                                           Count of admission records
             Occupancy Rate             66.67                                                 Occupied Beds / Available Beds × 100
     Average Length of Stay             15.51                                                               Average Length of Stay
           Readmission Rate             41.42                                        Readmitted Patients / Eligible Patients × 100
       Bed Utilization Rate             66.67                                                 Occupied Beds / Available Beds × 100
Department Efficiency Score             52.03 Weighted normalized score: Satisfaction 30%, Wait Time 25%, LOS 20%, Readmission 25%

In [24]:
storyboard = {
    "Dashboard": [
        "Hospital Overview",
        "Patient Flow",
        "Department Analytics",
        "Resource Utilization"
    ],

    "Purpose": [
        "Monitor overall hospital performance and key KPIs",
        "Analyze patient movement, waiting time and discharge patterns",
        "Compare department performance and efficiency",
        "Monitor bed capacity and resource utilization"
    ],

    "Primary Dataset": [
        "hospital_overview_dataset.csv",
        "patient_flow_dataset.csv",
        "department_analytics_dataset.csv",
        "resource_utilization_dataset.csv"
    ]
}

storyboard_df = pd.DataFrame(storyboard)

print("=" * 80)
print("MEDTRACK_DV - DASHBOARD STORYBOARD")
print("=" * 80)

print(storyboard_df.to_string(index=False))

================================================================================
MEDTRACK_DV - DASHBOARD STORYBOARD
================================================================================
           Dashboard                                                       Purpose                  Primary Dataset
   Hospital Overview             Monitor overall hospital performance and key KPIs    hospital_overview_dataset.csv
        Patient Flow Analyze patient movement, waiting time and discharge patterns         patient_flow_dataset.csv
Department Analytics                 Compare department performance and efficiency department_analytics_dataset.csv
Resource Utilization                 Monitor bed capacity and resource utilization resource_utilization_dataset.csv

In [27]:
file = os.path.join(folder, "department_analytics_dataset.csv")
department = pd.read_csv(file)

# Department Readmission Rate
department["department_readmission_rate"] = (
    department["readmitted_patients"]
    / department["total_admissions"]
) * 100

# Normalize Satisfaction
department["satisfaction_score"] = (
    (department["average_satisfaction"] -
     department["average_satisfaction"].min())
    /
    (department["average_satisfaction"].max() -
     department["average_satisfaction"].min())
) * 100

# Normalize Wait Time (lower is better)
department["wait_time_score"] = (
    (department["average_wait_time"].max() -
     department["average_wait_time"])
    /
    (department["average_wait_time"].max() -
     department["average_wait_time"].min())
) * 100

# Normalize Length of Stay (lower is better)
department["los_score"] = (
    (department["average_length_of_stay"].max() -
     department["average_length_of_stay"])
    /
    (department["average_length_of_stay"].max() -
     department["average_length_of_stay"].min())
) * 100

# Normalize Readmission Rate (lower is better)
department["readmission_score"] = (
    (department["department_readmission_rate"].max() -
     department["department_readmission_rate"])
    /
    (department["department_readmission_rate"].max() -
     department["department_readmission_rate"].min())
) * 100

# Final weighted score
department["department_efficiency_score"] = (
    department["satisfaction_score"] * 0.30
    + department["wait_time_score"] * 0.25
    + department["los_score"] * 0.20
    + department["readmission_score"] * 0.25
)

# Save updated dataset
department.to_csv(file, index=False)

print("Department dataset updated successfully!")
print("Columns:", department.columns.tolist())
print(
    "Average Department Efficiency Score:",
    round(department["department_efficiency_score"].mean(), 2)
)

Department dataset updated successfully!
Columns: ['hospital_id', 'hospital_name', 'department_referral', 'admission_date', 'total_admissions', 'average_age', 'average_wait_time', 'average_length_of_stay', 'average_satisfaction', 'readmitted_patients', 'department_readmission_rate', 'satisfaction_score', 'wait_time_score', 'los_score', 'readmission_score', 'department_efficiency_score']
Average Department Efficiency Score: 52.03