In [1]:
import pandas as pd
import os

In [4]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

folder = "/content/drive/MyDrive/RAW"

if os.path.exists(folder):
    for file in os.listdir(folder):
        if file.endswith(".csv"):
            path = os.path.join(folder, file)
            df = pd.read_csv(path)

            print("\n" + "="*60)
            print("FILE:", file)
            print("Rows, Columns:", df.shape)
            print("Columns:", list(df.columns))
            print("Missing values:")
            print(df.isnull().sum())
            print("Duplicate rows:", df.duplicated().sum())
else:
    print(f"Error: The folder {folder} does not exist. Please check the path inside your Google Drive.")

Mounted at /content/drive

============================================================
FILE: patients.csv
Rows, Columns: (1000, 7)
Columns: ['patient_id', 'name', 'age', 'arrival_date', 'departure_date', 'service', 'satisfaction']
Missing values:
patient_id        0
name              0
age               0
arrival_date      0
departure_date    0
service           0
satisfaction      0
dtype: int64
Duplicate rows: 0

============================================================
FILE: Healthcare Data Analysis for readmission.csv
Rows, Columns: (10000, 26)
Columns: ['hospital_name', 'Admission_date', 'hospital_id', 'hospital_beds_available', 'occupied_beds', 'hospital_ward', 'patient_id', 'patient_gender', 'patient_age', 'patient_race', 'patient_sat_score', 'patient_first_initial', 'patient_last_name', 'patient_waittime', 'department_referral', 'time_slot', 'doctor_id', 'doctor_name', 'doctor_specialty', 'patient_assigned_doctor', 'patient_checkin_date', 'patient_checkout_date', 'patient_disease', 'patient_length_of_stay', 'discharge_status', 'readmission']
Missing values:
hospital_name              0
Admission_date             0
hospital_id                0
hospital_beds_available    0
occupied_beds              0
hospital_ward              0
patient_id                 0
patient_gender             0
patient_age                0
patient_race               0
patient_sat_score          0
patient_first_initial      0
patient_last_name          0
patient_waittime           0
department_referral        0
time_slot                  0
doctor_id                  0
doctor_name                0
doctor_specialty           0
patient_assigned_doctor    0
patient_checkin_date       0
patient_checkout_date      0
patient_disease            0
patient_length_of_stay     0
discharge_status           0
readmission                0
dtype: int64
Duplicate rows: 0

/tmp/ipykernel_843/3509348921.py:13: DtypeWarning: Columns (10,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

============================================================
FILE: Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv
Rows, Columns: (1801551, 33)
Columns: ['Hospital Service Area', 'Hospital County', 'Operating Certificate Number', 'Permanent Facility Id', 'Facility Name', 'Age Group', 'Zip Code - 3 digits', 'Gender', 'Race', 'Ethnicity', 'Length of Stay', 'Type of Admission', 'Patient Disposition', 'Discharge Year', 'CCSR Diagnosis Code', 'CCSR Diagnosis Description', 'CCSR Procedure Code', 'CCSR Procedure Description', 'APR DRG Code', 'APR DRG Description', 'APR MDC Code', 'APR MDC Description', 'APR Severity of Illness Code', 'APR Severity of Illness Description', 'APR Risk of Mortality', 'APR Medical Surgical Description', 'Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3', 'Birth Weight', 'Emergency Department Indicator', 'Total Charges', 'Total Costs']
Missing values:
Hospital Service Area                     9205
Hospital County                           9205
Operating Certificate Number              9205
Permanent Facility Id                     9205
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      37886
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                        942
CCSR Diagnosis Description                 942
CCSR Procedure Code                     495614
CCSR Procedure Description              495614
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          1
APR Severity of Illness Code                 1
APR Severity of Illness Description       1743
APR Risk of Mortality                     1743
APR Medical Surgical Description             1
Payment Typology 1                           1
Payment Typology 2                      905212
Payment Typology 3                     1508528
Birth Weight                           1636054
Emergency Department Indicator               1
Total Charges                                1
Total Costs                                  1
dtype: int64
Duplicate rows: 2982

In [ ]:
datasets = {
    "HMIS / Healthcare Readmission Dataset": {
        "file": "Healthcare Data Analysis for readmission.csv",
        "purpose": "Core hospital, patient, admission, bed, department and readmission information"
    },

    "Patient Dataset": {
        "file": "patients.csv",
        "purpose": "Patient-level information including arrival, departure, service and satisfaction"
    },

    "Hospital Inpatient Discharges Dataset": {
        "file": "Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv",
        "purpose": "Inpatient discharge, length of stay, diagnosis, admission, disposition and financial information"
    },

    "Hospital Beds Management Dataset": {
        "file": "Hospital Beds Management.csv",
        "purpose": "Hospital bed and resource capacity information"
    }
}

print("MEDTRACK_DV - DATASET SELECTION")
print("=" * 60)

for name, details in datasets.items():
    print("\nDataset:", name)
    print("File:", details["file"])
    print("Purpose:", details["purpose"])

print("\n" + "=" * 60)
print("Total selected datasets:", len(datasets))

In [5]:
# ============================================================
# MEDTRACK_DV - MILESTONE 1
# STEP 2: DATA COLLECTION & PROFILING
# ============================================================

import pandas as pd
import os

# Folder containing the datasets
folder = "/content/drive/MyDrive/RAW"

# Find all CSV files
csv_files = [
    file for file in os.listdir(folder)
    if file.lower().endswith(".csv")
]

print("Total CSV files found:", len(csv_files))
print("=" * 80)

# Store loaded datasets
dataframes = {}

# Profile every CSV file
for file in csv_files:

    path = os.path.join(folder, file)

    # low_memory=False avoids mixed-type warning
    df = pd.read_csv(path, low_memory=False)

    dataframes[file] = df

    print("\n" + "=" * 80)
    print("FILE:", file)
    print("=" * 80)

    # Number of rows and columns
    print("\n1. Shape:")
    print(df.shape)

    # Column names
    print("\n2. Columns:")
    print(list(df.columns))

    # First 5 rows
    print("\n3. First 5 rows:")
    display(df.head())

    # Data types
    print("\n4. Data Types:")
    print(df.dtypes)

    # Missing values
    print("\n5. Missing Values:")
    print(df.isnull().sum())

    # Missing percentage
    print("\n6. Missing Percentage:")
    print((df.isnull().mean() * 100).round(2))

    # Duplicate rows
    print("\n7. Duplicate Rows:")
    print(df.duplicated().sum())

    # Number of unique values
    print("\n8. Unique Values:")
    print(df.nunique())

print("\n" + "=" * 80)
print("DATA COLLECTION & PROFILING COMPLETED")
print("=" * 80)

Total CSV files found: 3
================================================================================

================================================================================
FILE: patients.csv
================================================================================

1. Shape:
(1000, 7)

2. Columns:
['patient_id', 'name', 'age', 'arrival_date', 'departure_date', 'service', 'satisfaction']

3. First 5 rows:

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

4. Data Types:
patient_id        object
name              object
age                int64
arrival_date      object
departure_date    object
service           object
satisfaction       int64
dtype: object

5. Missing Values:
patient_id        0
name              0
age               0
arrival_date      0
departure_date    0
service           0
satisfaction      0
dtype: int64

6. Missing Percentage:
patient_id        0.0
name              0.0
age               0.0
arrival_date      0.0
departure_date    0.0
service           0.0
satisfaction      0.0
dtype: float64

7. Duplicate Rows:
0

8. Unique Values:
patient_id        1000
name               993
age                 90
arrival_date       344
departure_date     337
service              4
satisfaction        40
dtype: int64

================================================================================
FILE: Healthcare Data Analysis for readmission.csv
================================================================================

1. Shape:
(10000, 26)

2. Columns:
['hospital_name', 'Admission_date', 'hospital_id', 'hospital_beds_available', 'occupied_beds', 'hospital_ward', 'patient_id', 'patient_gender', 'patient_age', 'patient_race', 'patient_sat_score', 'patient_first_initial', 'patient_last_name', 'patient_waittime', 'department_referral', 'time_slot', 'doctor_id', 'doctor_name', 'doctor_specialty', 'patient_assigned_doctor', 'patient_checkin_date', 'patient_checkout_date', 'patient_disease', 'patient_length_of_stay', 'discharge_status', 'readmission']

3. First 5 rows:

,hospital_name,Admission_date,hospital_id,hospital_beds_available,occupied_beds,hospital_ward,patient_id,patient_gender,patient_age,patient_race,...,doctor_id,doctor_name,doctor_specialty,patient_assigned_doctor,patient_checkin_date,patient_checkout_date,patient_disease,patient_length_of_stay,discharge_status,readmission
0,The Johns Hopkins Hospital,30-01-2024,3946,260,90,Maternity,1421,Female,48,Asian,...,1725,Justin Morris,Rheumatology,False,14-07-2024,19-07-2024,Anxiety Disorders,6,Deceased,1
1,The Johns Hopkins Hospital,20-03-2022,7147,250,90,ICU,4922,Male,40,Black,...,7510,Latoya Moss,Pulmonology or Allergy and Immunology,False,19-07-2024,07/07/2024,Urinary Tract Infection (UTI),2,Deceased,1
2,The Johns Hopkins Hospital,13-07-2021,4174,350,220,Pediatrics,9804,Female,74,Black,...,7137,Michael Allen,Neurology,False,20-07-2024,29-06-2024,Hypertension (High Blood Pressure),17,Recovered,0
3,The Johns Hopkins Hospital,26-01-2021,2466,190,350,Pediatrics,5622,Male,82,Hispanic,...,8801,Rebecca Mccullough,Cardiology,False,25-06-2024,16-07-2024,Arthritis,28,Recovered,0
4,The Johns Hopkins Hospital,06/02/2024,3014,220,390,Surgery,3314,Male,62,Hispanic,...,3588,John Giles,Rheumatology,False,21-07-2024,19-07-2024,Cancer,16,Transferred,1

4. Data Types:
hospital_name              object
Admission_date             object
hospital_id                 int64
hospital_beds_available     int64
occupied_beds               int64
hospital_ward              object
patient_id                  int64
patient_gender             object
patient_age                 int64
patient_race               object
patient_sat_score           int64
patient_first_initial      object
patient_last_name          object
patient_waittime            int64
department_referral        object
time_slot                  object
doctor_id                   int64
doctor_name                object
doctor_specialty           object
patient_assigned_doctor      bool
patient_checkin_date       object
patient_checkout_date      object
patient_disease            object
patient_length_of_stay      int64
discharge_status           object
readmission                 int64
dtype: object

5. Missing Values:
hospital_name              0
Admission_date             0
hospital_id                0
hospital_beds_available    0
occupied_beds              0
hospital_ward              0
patient_id                 0
patient_gender             0
patient_age                0
patient_race               0
patient_sat_score          0
patient_first_initial      0
patient_last_name          0
patient_waittime           0
department_referral        0
time_slot                  0
doctor_id                  0
doctor_name                0
doctor_specialty           0
patient_assigned_doctor    0
patient_checkin_date       0
patient_checkout_date      0
patient_disease            0
patient_length_of_stay     0
discharge_status           0
readmission                0
dtype: int64

6. Missing Percentage:
hospital_name              0.0
Admission_date             0.0
hospital_id                0.0
hospital_beds_available    0.0
occupied_beds              0.0
hospital_ward              0.0
patient_id                 0.0
patient_gender             0.0
patient_age                0.0
patient_race               0.0
patient_sat_score          0.0
patient_first_initial      0.0
patient_last_name          0.0
patient_waittime           0.0
department_referral        0.0
time_slot                  0.0
doctor_id                  0.0
doctor_name                0.0
doctor_specialty           0.0
patient_assigned_doctor    0.0
patient_checkin_date       0.0
patient_checkout_date      0.0
patient_disease            0.0
patient_length_of_stay     0.0
discharge_status           0.0
readmission                0.0
dtype: float64

7. Duplicate Rows:
0

8. Unique Values:
hospital_name                 1
Admission_date             1460
hospital_id                6074
hospital_beds_available      41
occupied_beds                41
hospital_ward                 5
patient_id                 6022
patient_gender                2
patient_age                  96
patient_race                  5
patient_sat_score           151
patient_first_initial        52
patient_last_name           985
patient_waittime              8
department_referral          19
time_slot                  1439
doctor_id                  6019
doctor_name                9379
doctor_specialty             19
patient_assigned_doctor       2
patient_checkin_date         30
patient_checkout_date        29
patient_disease              28
patient_length_of_stay       30
discharge_status              3
readmission                   2
dtype: int64

================================================================================
FILE: Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv
================================================================================

1. Shape:
(1801551, 33)

2. Columns:
['Hospital Service Area', 'Hospital County', 'Operating Certificate Number', 'Permanent Facility Id', 'Facility Name', 'Age Group', 'Zip Code - 3 digits', 'Gender', 'Race', 'Ethnicity', 'Length of Stay', 'Type of Admission', 'Patient Disposition', 'Discharge Year', 'CCSR Diagnosis Code', 'CCSR Diagnosis Description', 'CCSR Procedure Code', 'CCSR Procedure Description', 'APR DRG Code', 'APR DRG Description', 'APR MDC Code', 'APR MDC Description', 'APR Severity of Illness Code', 'APR Severity of Illness Description', 'APR Risk of Mortality', 'APR Medical Surgical Description', 'Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3', 'Birth Weight', 'Emergency Department Indicator', 'Total Charges', 'Total Costs']

3. First 5 rows:

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,70 or Older,104,M,Other Race,Spanish/Hispanic,...,Major,Extreme,Medical,Medicare,Medicaid,NaN,NaN,Y,"320,922.43","60,241.34"
1,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,50 to 69,104,F,White,Not Span/Hispanic,...,Moderate,Minor,Medical,Private Health Insurance,NaN,NaN,NaN,Y,"61,665.22","9,180.69"
2,New York City,Bronx,7000006.0,1168.0,Montefiore Medical Center-Wakefield Hospital,18 to 29,104,F,Other Race,Spanish/Hispanic,...,Minor,Minor,Surgical,Medicaid,NaN,NaN,NaN,N,"42,705.34","11,366.5"
3,New York City,Bronx,7000006.0,3058.0,Montefiore Med Center - Jack D Weiler Hosp of ...,70 or Older,104,M,Other Race,Spanish/Hispanic,...,Major,Major,Medical,Medicare,Medicaid,NaN,NaN,Y,"72,700.17","12,111.75"
4,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,50 to 69,104,F,Black/African American,Not Span/Hispanic,...,Moderate,Minor,Medical,Medicare,Medicaid,NaN,NaN,Y,"55,562.51","8,339.72"

4. Data Types:
Hospital Service Area                   object
Hospital County                         object
Operating Certificate Number           float64
Permanent Facility Id                  float64
Facility Name                           object
Age Group                               object
Zip Code - 3 digits                     object
Gender                                  object
Race                                    object
Ethnicity                               object
Length of Stay                          object
Type of Admission                       object
Patient Disposition                     object
Discharge Year                           int64
CCSR Diagnosis Code                     object
CCSR Diagnosis Description              object
CCSR Procedure Code                     object
CCSR Procedure Description              object
APR DRG Code                             int64
APR DRG Description                     object
APR MDC Code                             int64
APR MDC Description                     object
APR Severity of Illness Code           float64
APR Severity of Illness Description     object
APR Risk of Mortality                   object
APR Medical Surgical Description        object
Payment Typology 1                      object
Payment Typology 2                      object
Payment Typology 3                      object
Birth Weight                            object
Emergency Department Indicator          object
Total Charges                           object
Total Costs                             object
dtype: object

5. Missing Values:
Hospital Service Area                     9205
Hospital County                           9205
Operating Certificate Number              9205
Permanent Facility Id                     9205
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      37886
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                        942
CCSR Diagnosis Description                 942
CCSR Procedure Code                     495614
CCSR Procedure Description              495614
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          1
APR Severity of Illness Code                 1
APR Severity of Illness Description       1743
APR Risk of Mortality                     1743
APR Medical Surgical Description             1
Payment Typology 1                           1
Payment Typology 2                      905212
Payment Typology 3                     1508528
Birth Weight                           1636054
Emergency Department Indicator               1
Total Charges                                1
Total Costs                                  1
dtype: int64

6. Missing Percentage:
Hospital Service Area                   0.51
Hospital County                         0.51
Operating Certificate Number            0.51
Permanent Facility Id                   0.51
Facility Name                           0.00
Age Group                               0.00
Zip Code - 3 digits                     2.10
Gender                                  0.00
Race                                    0.00
Ethnicity                               0.00
Length of Stay                          0.00
Type of Admission                       0.00
Patient Disposition                     0.00
Discharge Year                          0.00
CCSR Diagnosis Code                     0.05
CCSR Diagnosis Description              0.05
CCSR Procedure Code                    27.51
CCSR Procedure Description             27.51
APR DRG Code                            0.00
APR DRG Description                     0.00
APR MDC Code                            0.00
APR MDC Description                     0.00
APR Severity of Illness Code            0.00
APR Severity of Illness Description     0.10
APR Risk of Mortality                   0.10
APR Medical Surgical Description        0.00
Payment Typology 1                      0.00
Payment Typology 2                     50.25
Payment Typology 3                     83.73
Birth Weight                           90.81
Emergency Department Indicator          0.00
Total Charges                           0.00
Total Costs                             0.00
dtype: float64

7. Duplicate Rows:
4109

8. Unique Values:
Hospital Service Area                        8
Hospital County                             56
Operating Certificate Number               166
Permanent Facility Id                      203
Facility Name                              203
Age Group                                    5
Zip Code - 3 digits                         50
Gender                                       3
Race                                         4
Ethnicity                                    4
Length of Stay                             120
Type of Admission                            6
Patient Disposition                         19
Discharge Year                               1
CCSR Diagnosis Code                        477
CCSR Diagnosis Description                 477
CCSR Procedure Code                        320
CCSR Procedure Description                 320
APR DRG Code                               334
APR DRG Description                        334
APR MDC Code                                26
APR MDC Description                         26
APR Severity of Illness Code                 5
APR Severity of Illness Description          4
APR Risk of Mortality                        4
APR Medical Surgical Description             3
Payment Typology 1                           9
Payment Typology 2                           9
Payment Typology 3                           9
Birth Weight                                67
Emergency Department Indicator               2
Total Charges                          1585078
Total Costs                            1374391
dtype: int64

================================================================================
DATA COLLECTION & PROFILING COMPLETED
================================================================================

In [6]:
input_folder = "/content/drive/MyDrive/RAW"
output_folder = "/content/drive/MyDrive/RAW/Cleaned"

os.makedirs(output_folder, exist_ok=True)


# ------------------------------------------------------------
# 2. LOAD DATASETS
# ------------------------------------------------------------

patients = pd.read_csv(
    os.path.join(input_folder, "patients.csv"),
    low_memory=False
)

readmission = pd.read_csv(
    os.path.join(input_folder, "Healthcare Data Analysis for readmission.csv"),
    low_memory=False
)

inpatient = pd.read_csv(
    os.path.join(
        input_folder,
        "Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv"
    ),
    low_memory=False
)


# ============================================================
# DATASET 1: PATIENTS
# ============================================================

print("Cleaning patients.csv...")

# Standardize column names
patients.columns = patients.columns.str.strip().str.lower()

# Standardize text columns
patients["name"] = patients["name"].astype(str).str.strip()
patients["service"] = patients["service"].astype(str).str.strip().str.lower()

# Convert dates
patients["arrival_date"] = pd.to_datetime(
    patients["arrival_date"],
    errors="coerce"
)

patients["departure_date"] = pd.to_datetime(
    patients["departure_date"],
    errors="coerce"
)

# Remove exact duplicate rows
patients = patients.drop_duplicates()

# Check invalid values
patients.loc[
    (patients["age"] < 0) | (patients["age"] > 120),
    "age"
] = pd.NA

patients.loc[
    (patients["satisfaction"] < 0) | (patients["satisfaction"] > 100),
    "satisfaction"
] = pd.NA

print("Patients cleaned:", patients.shape)


# ============================================================
# DATASET 2: READMISSION / HMIS
# ============================================================

print("\nCleaning Healthcare Data Analysis for readmission.csv...")

# Standardize column names
readmission.columns = readmission.columns.str.strip().str.lower()

# Standardize text columns
text_columns = [
    "hospital_name",
    "hospital_ward",
    "patient_gender",
    "patient_race",
    "patient_first_initial",
    "patient_last_name",
    "department_referral",
    "time_slot",
    "doctor_name",
    "doctor_specialty",
    "patient_disease",
    "discharge_status"
]

for col in text_columns:
    readmission[col] = (
        readmission[col]
        .astype(str)
        .str.strip()
    )

# Standardize categorical values
readmission["hospital_ward"] = (
    readmission["hospital_ward"]
    .str.lower()
    .str.strip()
)

readmission["department_referral"] = (
    readmission["department_referral"]
    .str.lower()
    .str.strip()
)

readmission["patient_gender"] = (
    readmission["patient_gender"]
    .str.lower()
    .str.strip()
)

readmission["patient_race"] = (
    readmission["patient_race"]
    .str.lower()
    .str.strip()
)

readmission["discharge_status"] = (
    readmission["discharge_status"]
    .str.lower()
    .str.strip()
)

# Convert dates
date_columns = [
    "admission_date",
    "patient_checkin_date",
    "patient_checkout_date"
]

for col in date_columns:
    readmission[col] = pd.to_datetime(
        readmission[col],
        errors="coerce",
        dayfirst=True
    )

# Remove exact duplicates
readmission = readmission.drop_duplicates()

# Standardize IDs
readmission["hospital_id"] = (
    pd.to_numeric(readmission["hospital_id"], errors="coerce")
    .astype("Int64")
)

readmission["patient_id"] = (
    pd.to_numeric(readmission["patient_id"], errors="coerce")
    .astype("Int64")
)

readmission["doctor_id"] = (
    pd.to_numeric(readmission["doctor_id"], errors="coerce")
    .astype("Int64")
)

# Validate numeric ranges
readmission.loc[
    (readmission["patient_age"] < 0) |
    (readmission["patient_age"] > 120),
    "patient_age"
] = pd.NA

readmission.loc[
    readmission["patient_sat_score"] < 0,
    "patient_sat_score"
] = pd.NA

readmission.loc[
    readmission["patient_length_of_stay"] < 0,
    "patient_length_of_stay"
] = pd.NA

readmission.loc[
    readmission["patient_waittime"] < 0,
    "patient_waittime"
] = pd.NA

# Ensure readmission is 0/1
readmission["readmission"] = pd.to_numeric(
    readmission["readmission"],
    errors="coerce"
)

readmission.loc[
    ~readmission["readmission"].isin([0, 1]),
    "readmission"
] = pd.NA

print("Readmission dataset cleaned:", readmission.shape)


# ============================================================
# DATASET 3: INPATIENT DISCHARGES
# ============================================================

print("\nCleaning Hospital Inpatient Discharges dataset...")

# Standardize column names
inpatient.columns = (
    inpatient.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

# ------------------------------------------------------------
# Remove exact duplicate rows
# ------------------------------------------------------------

before = len(inpatient)

inpatient = inpatient.drop_duplicates()

after = len(inpatient)

print("Duplicate rows removed:", before - after)


# ------------------------------------------------------------
# Standardize text columns
# ------------------------------------------------------------

text_columns = inpatient.select_dtypes(
    include=["object"]
).columns

for col in text_columns:
    inpatient[col] = (
        inpatient[col]
        .astype("string")
        .str.strip()
    )


# ------------------------------------------------------------
# Convert numeric columns
# ------------------------------------------------------------

numeric_columns = [
    "operating_certificate_number",
    "permanent_facility_id",
    "apr_drg_code",
    "apr_mdc_code",
    "apr_severity_of_illness_code"
]

for col in numeric_columns:
    inpatient[col] = pd.to_numeric(
        inpatient[col],
        errors="coerce"
    )


# ------------------------------------------------------------
# Length of Stay
# ------------------------------------------------------------

inpatient["length_of_stay"] = pd.to_numeric(
    inpatient["length_of_stay"],
    errors="coerce"
)

inpatient.loc[
    inpatient["length_of_stay"] < 0,
    "length_of_stay"
] = pd.NA


# ------------------------------------------------------------
# Financial columns
# Remove commas and convert to numeric
# ------------------------------------------------------------

inpatient["total_charges"] = pd.to_numeric(
    inpatient["total_charges"]
    .astype(str)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

inpatient["total_costs"] = pd.to_numeric(
    inpatient["total_costs"]
    .astype(str)
    .str.replace(",", "", regex=False),
    errors="coerce"
)


# ------------------------------------------------------------
# Birth Weight
# ------------------------------------------------------------

inpatient["birth_weight"] = pd.to_numeric(
    inpatient["birth_weight"],
    errors="coerce"
)


# ------------------------------------------------------------
# Standardize categorical values
# ------------------------------------------------------------

categorical_columns = [
    "gender",
    "race",
    "ethnicity",
    "type_of_admission",
    "patient_disposition",
    "apr_risk_of_mortality",
    "apr_medical_surgical_description",
    "payment_typology_1",
    "payment_typology_2",
    "payment_typology_3",
    "emergency_department_indicator"
]

for col in categorical_columns:
    inpatient[col] = (
        inpatient[col]
        .astype("string")
        .str.strip()
        .str.lower()
    )


# ------------------------------------------------------------
# Missing values
# ------------------------------------------------------------
# Do NOT replace all missing values with 0.
# Keep genuine missing information as NA.
#
# Only numerical financial values are retained as numeric;
# categorical missing values remain missing.
# ------------------------------------------------------------


# ============================================================
# SAVE CLEANED DATASETS
# ============================================================

patients.to_csv(
    os.path.join(output_folder, "patients_cleaned.csv"),
    index=False
)

readmission.to_csv(
    os.path.join(output_folder, "readmission_cleaned.csv"),
    index=False
)

inpatient.to_csv(
    os.path.join(output_folder, "inpatient_discharges_cleaned.csv"),
    index=False
)


# ============================================================
# CLEANING SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("DATA CLEANING COMPLETED")
print("=" * 70)

print("\nPatients:")
print("Rows:", len(patients))
print("Columns:", len(patients.columns))
print("Duplicates:", patients.duplicated().sum())

print("\nReadmission:")
print("Rows:", len(readmission))
print("Columns:", len(readmission.columns))
print("Duplicates:", readmission.duplicated().sum())

print("\nInpatient Discharges:")
print("Rows:", len(inpatient))
print("Columns:", len(inpatient.columns))
print("Duplicates:", inpatient.duplicated().sum())

print("\nCleaned files saved in:")
print(output_folder)

Cleaning patients.csv...
Patients cleaned: (1000, 7)

Cleaning Healthcare Data Analysis for readmission.csv...
Readmission dataset cleaned: (10000, 26)

Cleaning Hospital Inpatient Discharges dataset...
Duplicate rows removed: 4109

======================================================================
DATA CLEANING COMPLETED
======================================================================

Patients:
Rows: 1000
Columns: 7
Duplicates: 0

Readmission:
Rows: 10000
Columns: 26
Duplicates: 0

Inpatient Discharges:
Rows: 1797442
Columns: 33
Duplicates: 0

Cleaned files saved in:
/content/drive/MyDrive/RAW/Cleaned

In [ ]:
cleaned_folder = "/content/drive/MyDrive/RAW/Cleaned"
standardized_folder = "/content/drive/MyDrive/RAW/Standardized"
os.makedirs(standardized_folder, exist_ok=True)


# ------------------------------------------------------------
# 2. LOAD CLEANED DATASETS
# ------------------------------------------------------------

patients = pd.read_csv(
    os.path.join(cleaned_folder, "patients_cleaned.csv"),
    low_memory=False
)

readmission = pd.read_csv(
    os.path.join(cleaned_folder, "readmission_cleaned.csv"),
    low_memory=False
)

inpatient = pd.read_csv(
    os.path.join(cleaned_folder, "inpatient_discharges_cleaned.csv"),
    low_memory=False
)


# ============================================================
# 3. PATIENT ID STANDARDIZATION
# ============================================================

# patients.csv already has IDs like PAT-09484753
patients["patient_id"] = (
    patients["patient_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Readmission dataset has numeric patient IDs
readmission["patient_id"] = (
    pd.to_numeric(
        readmission["patient_id"],
        errors="coerce"
    )
    .astype("Int64")
)

# Create a consistent text ID format
readmission["patient_id"] = (
    "PAT-" +
    readmission["patient_id"].astype(str)
)


# ============================================================
# 4. HOSPITAL ID STANDARDIZATION
# ============================================================

readmission["hospital_id"] = (
    pd.to_numeric(
        readmission["hospital_id"],
        errors="coerce"
    )
    .astype("Int64")
)

# Convert hospital ID to consistent text format
readmission["hospital_id"] = (
    "HOSP-" +
    readmission["hospital_id"].astype(str)
)


# ============================================================
# 5. DOCTOR ID STANDARDIZATION
# ============================================================

readmission["doctor_id"] = (
    pd.to_numeric(
        readmission["doctor_id"],
        errors="coerce"
    )
    .astype("Int64")
)

# Convert doctor ID to consistent text format
readmission["doctor_id"] = (
    "DOC-" +
    readmission["doctor_id"].astype(str)
)


# ============================================================
# 6. INPATIENT FACILITY ID STANDARDIZATION
# ============================================================

# Permanent Facility ID
inpatient["permanent_facility_id"] = pd.to_numeric(
    inpatient["permanent_facility_id"],
    errors="coerce"
)

inpatient["permanent_facility_id"] = (
    "FAC-" +
    inpatient["permanent_facility_id"]
    .astype("Int64")
    .astype(str)
)

# Operating Certificate Number
inpatient["operating_certificate_number"] = pd.to_numeric(
    inpatient["operating_certificate_number"],
    errors="coerce"
)

inpatient["operating_certificate_number"] = (
    "CERT-" +
    inpatient["operating_certificate_number"]
    .astype("Int64")
    .astype(str)
)


# ============================================================
# 7. VERIFY ID STANDARDIZATION
# ============================================================

print("=" * 70)
print("ID STANDARDIZATION RESULTS")
print("=" * 70)

print("\nPatients - Patient IDs:")
print(patients["patient_id"].head())

print("\nReadmission - Patient IDs:")
print(readmission["patient_id"].head())

print("\nReadmission - Hospital IDs:")
print(readmission["hospital_id"].head())

print("\nReadmission - Doctor IDs:")
print(readmission["doctor_id"].head())

print("\nInpatient - Facility IDs:")
print(inpatient["permanent_facility_id"].head())

print("\nInpatient - Certificate IDs:")
print(inpatient["operating_certificate_number"].head())


# ============================================================
# 8. SAVE STANDARDIZED DATASETS
# ============================================================

patients.to_csv(
    os.path.join(
        standardized_folder,
        "patients_standardized.csv"
    ),
    index=False
)

readmission.to_csv(
    os.path.join(
        standardized_folder,
        "readmission_standardized.csv"
    ),
    index=False
)

inpatient.to_csv(
    os.path.join(
        standardized_folder,
        "inpatient_discharges_standardized.csv"
    ),
    index=False
)


# ============================================================
# 9. FINAL CHECK
# ============================================================

print("\n" + "=" * 70)
print("ID STANDARDIZATION COMPLETED")
print("=" * 70)

print("\nPatients:", patients.shape)
print("Readmission:", readmission.shape)
print("Inpatient Discharges:", inpatient.shape)

print("\nStandardized files saved to:")
print(standardized_folder)

In [ ]:
standardized_folder = "/content/drive/MyDrive/RAW/Standardized"
department_folder = "/content/drive/MyDrive/RAW/Department_Standardized"

os.makedirs(department_folder, exist_ok=True)


# ------------------------------------------------------------
# 2. LOAD STANDARDIZED DATASETS
# ------------------------------------------------------------

patients = pd.read_csv(
    os.path.join(standardized_folder, "patients_standardized.csv"),
    low_memory=False
)

readmission = pd.read_csv(
    os.path.join(standardized_folder, "readmission_standardized.csv"),
    low_memory=False
)

inpatient = pd.read_csv(
    os.path.join(
        standardized_folder,
        "inpatient_discharges_standardized.csv"
    ),
    low_memory=False
)


# ============================================================
# 3. STANDARDIZE DEPARTMENT / SERVICE NAMES
# ============================================================

# ------------------------------------------------------------
# Patients dataset
# Column: service
# ------------------------------------------------------------

if "service" in patients.columns:

    patients["service"] = (
        patients["service"]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

    # Standardize common naming variations
    patients["service"] = patients["service"].replace({
        "general medicine": "general_medicine",
        "general-medicine": "general_medicine",
        "general medicine ": "general_medicine",
        "icu": "icu",
        "surgery": "surgery",
        "emergency": "emergency"
    })


# ------------------------------------------------------------
# Readmission dataset
# Columns: hospital_ward and department_referral
# ------------------------------------------------------------

if "hospital_ward" in readmission.columns:

    readmission["hospital_ward"] = (
        readmission["hospital_ward"]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

if "department_referral" in readmission.columns:

    readmission["department_referral"] = (
        readmission["department_referral"]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )


# ============================================================
# 4. DISPLAY STANDARDIZED DEPARTMENT VALUES
# ============================================================

print("=" * 70)
print("STANDARDIZED DEPARTMENT / SERVICE VALUES")
print("=" * 70)

if "service" in patients.columns:
    print("\nPatients - Service:")
    print(sorted(patients["service"].dropna().unique()))

if "hospital_ward" in readmission.columns:
    print("\nReadmission - Hospital Ward:")
    print(sorted(readmission["hospital_ward"].dropna().unique()))

if "department_referral" in readmission.columns:
    print("\nReadmission - Department Referral:")
    print(sorted(readmission["department_referral"].dropna().unique()))


# ============================================================
# 5. SAVE DEPARTMENT-STANDARDIZED DATASETS
# ============================================================

patients.to_csv(
    os.path.join(
        department_folder,
        "patients_department_standardized.csv"
    ),
    index=False
)

readmission.to_csv(
    os.path.join(
        department_folder,
        "readmission_department_standardized.csv"
    ),
    index=False
)

inpatient.to_csv(
    os.path.join(
        department_folder,
        "inpatient_discharges_department_standardized.csv"
    ),
    index=False
)


# ============================================================
# 6. COMPLETION CHECK
# ============================================================

print("\n" + "=" * 70)
print("DEPARTMENT STANDARDIZATION COMPLETED")
print("=" * 70)

print("\nPatients:", patients.shape)
print("Readmission:", readmission.shape)
print("Inpatient Discharges:", inpatient.shape)

print("\nFiles saved to:")
print(department_folder)

In [ ]:
input_folder = "/content/drive/MyDrive/RAW/Department_Standardized"
output_folder = "/content/drive/MyDrive/RAW/Date_Standardized"

os.makedirs(output_folder, exist_ok=True)

# ============================================================
# 1. LOAD DATASETS
# ============================================================

patients = pd.read_csv(
    os.path.join(input_folder, "patients_department_standardized.csv")
)

readmission = pd.read_csv(
    os.path.join(input_folder, "readmission_department_standardized.csv")
)

inpatient = pd.read_csv(
    os.path.join(
        input_folder,
        "inpatient_discharges_department_standardized.csv"
    ),
    low_memory=False
)

# ============================================================
# 2. PATIENTS DATASET
# ============================================================

patients["arrival_date"] = pd.to_datetime(
    patients["arrival_date"],
    errors="coerce"
)

patients["departure_date"] = pd.to_datetime(
    patients["departure_date"],
    errors="coerce"
)

# Create standard date columns
patients["arrival_date"] = patients["arrival_date"].dt.strftime("%Y-%m-%d")
patients["departure_date"] = patients["departure_date"].dt.strftime("%Y-%m-%d")


# ============================================================
# 3. READMISSION DATASET
# ============================================================

readmission["admission_date"] = pd.to_datetime(
    readmission["admission_date"],
    errors="coerce"
)

readmission["patient_checkin_date"] = pd.to_datetime(
    readadmission["patient_checkin_date"],
    errors="coerce"
)

readmission["patient_checkout_date"] = pd.to_datetime(
    readmission["patient_checkout_date"],
    errors="coerce"
)

# Standard date format
readmission["admission_date"] = readmission["admission_date"].dt.strftime("%Y-%m-%d")
readmission["patient_checkin_date"] = readmission["patient_checkin_date"].dt.strftime("%Y-%m-%d")
readmission["patient_checkout_date"] = readmission["patient_checkout_date"].dt.strftime("%Y-%m-%d")


# ============================================================
# 4. INPATIENT DISCHARGES DATASET
# ============================================================

# Check whether discharge/admission date columns exist
date_columns = [
    col for col in inpatient.columns
    if "date" in col.lower() or "year" in col.lower() # Include 'year' to catch 'discharge_year'
]

print("Inpatient date-related columns:")
print(date_columns)

# Convert any date-related columns to standard format
for col in date_columns:
    if col == "discharge_year":
        # Create a full date string (YYYY-01-01) for proper conversion
        inpatient[col] = pd.to_datetime(
            inpatient[col].astype(str) + '-01-01',
            errors="coerce"
        )
    else:
        inpatient[col] = pd.to_datetime(
            inpatient[col],
            errors="coerce"
        )
    inpatient[col] = inpatient[col].dt.strftime("%Y-%m-%d")


# ============================================================
# 5. CHECK DATE VALUES
# ============================================================

print("\n" + "="*70)
print("DATE STANDARDIZATION CHECK")
print("="*70)

print("\nPatients:")
print(patients[["arrival_date", "departure_date"]].head())

print("\nReadmission:")
print(
    readmission[
        ["admission_date", "patient_checkin_date", "patient_checkout_date"]
    ].head()
)

print("\nInpatient date columns:")
for col in date_columns:
    print(f"\n{col}:")
    print(inpatient[col].head())


# ============================================================
# 6. SAVE DATASETS
# ============================================================

patients.to_csv(
    os.path.join(output_folder, "patients_date_standardized.csv"),
    index=False
)

readmission.to_csv(
    os.path.join(output_folder, "readmission_date_standardized.csv"),
    index=False
)

inpatient.to_csv(
    os.path.join(output_folder, "inpatient_discharges_date_standardized.csv"),
    index=False
)


print("\n" + "="*70)
print("DATE STANDARDIZATION COMPLETED")
print("="*70)

print("Patients:", patients.shape)
print("Readmission:", readmission.shape)
print("Inpatient Discharges:", inpatient.shape)

print("\nFiles saved to:")
print(output_folder)