# MedTrack_DV — 01. Data Loading & Profiling

Loads and profiles the raw files for all 3 approved datasets, per the project's Data Finalization Rule
(profile before cleaning; do not skip to cleaning without understanding shape, types, and quality first).

**Datasets in this project:**
1. **HMIS** (19 relational tables) — PRIMARY / BACKBONE dataset. Every row in all 4 final tables originates here.
2. **Beds Management** (4 tables) — SUPPLEMENT dataset. No shared key with HMIS; bridged later via department name + week-to-date mapping.
3. **Readmission dataset** (1 table) — BENCHMARK dataset. No shared key with HMIS; used only for disease-level mortality/readmission/satisfaction benchmarks.

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display, Markdown

PROJECT_ROOT = Path.cwd().parent

## 1. HMIS — Hospital HMIS Dataset for Healthcare Analytics

In [2]:
HMIS_RAW_DATA_DIR = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "Hospital HMIS Dataset for Healthcare Analytics"
    / "hospital_synthetic_shalaka"
    / "hospital_data"
)
print(HMIS_RAW_DATA_DIR)

hmis_file_names = [
    # Parent / Master Tables
    "department.csv", "patient.csv", "employee.csv", "disease.csv",
    "insurance_provider.csv", "drug_manufacturer.csv",
    # First-Level Dependent Tables
    "doctor.csv", "ward.csv", "drug.csv", "patient_insurance.csv",
    # Operational Resources
    "bed.csv", "drug_inventory.csv",
    # Hospital Transactions
    "staff_assignment.csv", "admission.csv",
    # Clinical Transactions
    "diagnostic_test.csv", "patient_diagnostic.csv", "prescription.csv",
    # Financial Transactions
    "billing.csv", "billing_detail.csv",
]
for file_name in hmis_file_names:
    file_path = HMIS_RAW_DATA_DIR / file_name
    print(f"\u2713 {file_name} found" if file_path.exists() else f"\u2717 {file_name} NOT found")

C:\Users\sr189\OneDrive\Desktop\Hospital Management Data Analysis\MedTrack_DV\data\raw\Hospital HMIS Dataset for Healthcare Analytics\hospital_synthetic_shalaka\hospital_data
✓ department.csv found
✓ patient.csv found
✓ employee.csv found
✓ disease.csv found
✓ insurance_provider.csv found
✓ drug_manufacturer.csv found
✓ doctor.csv found
✓ ward.csv found
✓ drug.csv found
✓ patient_insurance.csv found
✓ bed.csv found
✓ drug_inventory.csv found
✓ staff_assignment.csv found
✓ admission.csv found
✓ diagnostic_test.csv found
✓ patient_diagnostic.csv found
✓ prescription.csv found
✓ billing.csv found
✓ billing_detail.csv found

In [3]:
def profile_table(df, file_name):
    """Prints a compact but complete profile of one raw table:
    preview, dimensions, one combined column-profile table
    (dtype + non-null/missing counts/% + unique values - avoids
    the redundant overlapping sections an earlier draft had),
    a statistical summary, and a duplicate-row check."""

    display(Markdown("---"))
    display(Markdown(f"# \U0001F4CA Data Profile: `{file_name}`"))

    display(Markdown("## 1. Dataset Preview"))
    display(df.head())

    display(Markdown("## 2. Dataset Dimensions"))
    print(f"Number of Rows    : {df.shape[0]}")
    print(f"Number of Columns : {df.shape[1]}")

    display(Markdown("## 3. Column Profile"))
    column_profile = pd.DataFrame({
        "Data Type": df.dtypes.astype(str),
        "Non-Null Count": df.notnull().sum(),
        "Missing Count": df.isnull().sum(),
        "Missing %": (df.isnull().sum() / len(df) * 100).round(2),
        "Unique Values": df.nunique()
    })
    display(column_profile)

    display(Markdown("## 4. Statistical Summary"))
    display(df.describe(include="all").T)

    display(Markdown("## 5. Duplicate Record Check"))
    duplicate_count = df.duplicated().sum()
    print(f"Duplicate Rows: {duplicate_count}")
    if duplicate_count == 0:
        print("\u2713 No duplicate rows found.")

In [4]:
for file_name in hmis_file_names:
    df = pd.read_csv(HMIS_RAW_DATA_DIR / file_name)
    profile_table(df, file_name)

---

# 📊 Data Profile: `department.csv`

## 1. Dataset Preview

   department_id    department_name department_type  floor_number  status
0              1          Emergency        Clinical             0  Active
1              2  Internal Medicine        Clinical             2  Active
2              3            Surgery        Clinical             3  Active
3              4         Pediatrics        Clinical             2  Active
4              5        Orthopedics        Clinical             4  Active

## 2. Dataset Dimensions

Number of Rows    : 11
Number of Columns : 5

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
department_id,int64,11,0,0.0,11
department_name,object,11,0,0.0,11
department_type,object,11,0,0.0,3
floor_number,int64,11,0,0.0,5
status,object,11,0,0.0,1

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
department_id,11.0,NaN,NaN,NaN,6.0,3.316625,1.0,3.5,6.0,8.5,11.0
department_name,11,11,Emergency,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
department_type,11,3,Clinical,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
floor_number,11.0,NaN,NaN,NaN,1.272727,1.3484,0.0,0.0,1.0,2.0,4.0
status,11,1,Active,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `patient.csv`

## 1. Dataset Preview

,patient_id,gender,date_of_birth,blood_group,city,contact_number
0,1,Female,1987-08-24,O-,East Stephanieberg,+1-792-342-0981
1,2,Male,1960-05-18,A-,Manuelbury,793-725-0800
2,3,Male,1955-04-24,A-,Lake Susanchester,+1-330-617-3749x232
3,4,Male,2004-06-16,B-,South Leslieburgh,426-611-6235x07684
4,5,Male,1977-07-22,A-,Lopezchester,(215)330-2831x0821

## 2. Dataset Dimensions

Number of Rows    : 30000
Number of Columns : 6

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
patient_id,int64,30000,0,0.0,30000
gender,object,30000,0,0.0,3
date_of_birth,object,30000,0,0.0,19760
blood_group,object,30000,0,0.0,8
city,object,30000,0,0.0,17836
contact_number,object,30000,0,0.0,30000

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
patient_id,30000.0,NaN,NaN,NaN,15000.5,8660.398374,1.0,7500.75,15000.5,22500.25,30000.0
gender,30000,3,Male,15918,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date_of_birth,30000,19760,1936-10-24,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
blood_group,30000,8,O+,3851,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,30000,17836,South Michael,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contact_number,30000,30000,001-407-949-9164,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `employee.csv`

## 1. Dataset Preview

,employee_id,employee_name,gender,role,employment_type,date_of_joining,department_id
0,1,Sanaya Kalla,Male,Admin,Contract,2024-04-17,11
1,2,Dayamai Raj,Female,Nurse,Full-time,2011-05-09,6
2,3,Logan Lata,Male,Doctor,Contract,2020-10-27,8
3,4,Vyanjana Kota,Female,Technician,Contract,2013-05-01,9
4,5,Nachiket Mani,Female,Admin,Contract,2013-02-16,3

## 2. Dataset Dimensions

Number of Rows    : 500
Number of Columns : 7

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
employee_id,int64,500,0,0.0,500
employee_name,object,500,0,0.0,499
gender,object,500,0,0.0,2
role,object,500,0,0.0,5
employment_type,object,500,0,0.0,2
date_of_joining,object,500,0,0.0,477
department_id,int64,500,0,0.0,11

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
employee_id,500.0,NaN,NaN,NaN,250.5,144.481833,1.0,125.75,250.5,375.25,500.0
employee_name,500,499,Saksham Sehgal,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,500,2,Female,277,NaN,NaN,NaN,NaN,NaN,NaN,NaN
role,500,5,Nurse,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
employment_type,500,2,Contract,251,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date_of_joining,500,477,2013-05-01,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
department_id,500.0,NaN,NaN,NaN,5.94,3.209517,1.0,3.0,6.0,9.0,11.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `disease.csv`

## 1. Dataset Preview

   disease_id                 disease_name disease_category
0           1  Acute Myocardial Infarction          Cardiac
1           2                       Stroke     Neurological
2           3        Road Traffic Accident           Trauma
3           4                       Sepsis       Infectious
4           5   Acute Respiratory Distress      Respiratory

## 2. Dataset Dimensions

Number of Rows    : 20
Number of Columns : 3

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
disease_id,int64,20,0,0.0,20
disease_name,object,20,0,0.0,20
disease_category,object,20,0,0.0,11

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
disease_id,20.0,NaN,NaN,NaN,10.5,5.91608,1.0,5.75,10.5,15.25,20.0
disease_name,20,20,Acute Myocardial Infarction,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disease_category,20,11,Infectious,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `insurance_provider.csv`

## 1. Dataset Preview

,insurance_provider_id,provider_name,provider_type,contact_details,coverage_limit
0,1,Bhatti Group Health Insurance,Private,312415859,1500000
1,2,"Buch, Sane and Mital Health Insurance",Govt,4725671570,1500000
2,3,Raval-Panchal Health Insurance,Private,3558053298,300000
3,4,Dalal Group Health Insurance,Private,2200795707,200000
4,5,"Sridhar, Upadhyay and Dewan Health Insurance",Private,905244964,300000

## 2. Dataset Dimensions

Number of Rows    : 50
Number of Columns : 5

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
insurance_provider_id,int64,50,0,0.0,50
provider_name,object,50,0,0.0,50
provider_type,object,50,0,0.0,2
contact_details,int64,50,0,0.0,50
coverage_limit,int64,50,0,0.0,7

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
insurance_provider_id,50.0,NaN,NaN,NaN,25.5,14.57738,1.0,13.25,25.5,37.75,50.0
provider_name,50,50,Bhatti Group Health Insurance,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
provider_type,50,2,Govt,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contact_details,50.0,NaN,NaN,NaN,205036753127.26001,380828440961.722778,312415859.0,3150241119.0,6485461524.0,9563985855.0,919407524674.0
coverage_limit,50.0,NaN,NaN,NaN,828000.0,582846.638561,200000.0,300000.0,625000.0,1375000.0,2000000.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `drug_manufacturer.csv`

## 1. Dataset Preview

,manufacturer_id,manufacturer_name,country,reliability_rating,contract_status
0,1,"Dora, Yogi and Deshpande",USA,3.8,Active
1,2,Dhawan-Bhasin,UK,4.4,Expired
2,3,"Trivedi, Chaudhry and Parmar",UK,4.3,Active
3,4,"Chada, Mall and Parmar",Germany,3.9,Expired
4,5,Khanna-Chand,UK,4.5,Expired

## 2. Dataset Dimensions

Number of Rows    : 300
Number of Columns : 5

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
manufacturer_id,int64,300,0,0.0,300
manufacturer_name,object,300,0,0.0,295
country,object,300,0,0.0,5
reliability_rating,float64,300,0,0.0,15
contract_status,object,300,0,0.0,2

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
manufacturer_id,300.0,NaN,NaN,NaN,150.5,86.746758,1.0,75.75,150.5,225.25,300.0
manufacturer_name,300,295,Dhar Ltd,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,300,5,Switzerland,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reliability_rating,300.0,NaN,NaN,NaN,4.195667,0.415681,3.5,3.8,4.2,4.5,4.9
contract_status,300,2,Expired,159,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `doctor.csv`

## 1. Dataset Preview

   doctor_id  employee_id specialization qualification  experience_years
0          1            3    Orthopedics            DM                31
1          2            9     Pediatrics            MS                 7
2          3           13      Neurology            MS                21
3          4           25        Surgery            MS                25
4          5           26      Neurology          MBBS                 5

## 2. Dataset Dimensions

Number of Rows    : 98
Number of Columns : 5

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
doctor_id,int64,98,0,0.0,98
employee_id,int64,98,0,0.0,98
specialization,object,98,0,0.0,9
qualification,object,98,0,0.0,4
experience_years,int64,98,0,0.0,34

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
doctor_id,98.0,NaN,NaN,NaN,49.5,28.434134,1.0,25.25,49.5,73.75,98.0
employee_id,98.0,NaN,NaN,NaN,252.071429,147.102899,3.0,132.25,232.5,380.5,498.0
specialization,98,9,Neurology,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
qualification,98,4,DM,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
experience_years,98.0,NaN,NaN,NaN,17.428571,10.404202,1.0,8.0,17.5,26.0,35.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `ward.csv`

## 1. Dataset Preview

   ward_id         ward_name ward_type  total_beds  department_id
0        1  Emergency Ward 1   General          10              1
1        2  Emergency Ward 2   Private          15              1
2        3  Emergency Ward 3   General          10              1
3        4  Emergency Ward 4   General          20              1
4        5  Emergency Ward 5   General          20              1

## 2. Dataset Dimensions

Number of Rows    : 27
Number of Columns : 5

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
ward_id,int64,27,0,0.0,27
ward_name,object,27,0,0.0,27
ward_type,object,27,0,0.0,4
total_beds,int64,27,0,0.0,3
department_id,int64,27,0,0.0,6

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ward_id,27.0,NaN,NaN,NaN,14.0,7.937254,1.0,7.5,14.0,20.5,27.0
ward_name,27,27,Emergency Ward 1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ward_type,27,4,General,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_beds,27.0,NaN,NaN,NaN,15.37037,4.143096,10.0,10.0,15.0,20.0,20.0
department_id,27.0,NaN,NaN,NaN,3.296296,1.70553,1.0,2.0,3.0,4.5,6.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `drug.csv`

## 1. Dataset Preview

,drug_id,drug_name,brand_name,drug_category,unit_cost,manufacturer_id
0,1,Earum,Arora-Pandya,Antibiotic,252,44
1,2,Minus,"Bhakta, Dass and Chakraborty",Antipyretic,243,240
2,3,Dolore,Kala Inc,Analgesic,13,215
3,4,Neque,"Bhargava, Andra and Nath",Antacid,356,7
4,5,Tempore,Lalla-Char,Antihypertensive,359,113

## 2. Dataset Dimensions

Number of Rows    : 250
Number of Columns : 6

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
drug_id,int64,250,0,0.0,250
drug_name,object,250,0,0.0,142
brand_name,object,250,0,0.0,250
drug_category,object,250,0,0.0,8
unit_cost,int64,250,0,0.0,192
manufacturer_id,int64,250,0,0.0,172

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
drug_id,250.0,NaN,NaN,NaN,125.5,72.312977,1.0,63.25,125.5,187.75,250.0
drug_name,250,142,Nostrum,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
brand_name,250,250,Arora-Pandya,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drug_category,250,8,Analgesic,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unit_cost,250.0,NaN,NaN,NaN,247.492,142.546948,10.0,121.0,239.5,382.75,498.0
manufacturer_id,250.0,NaN,NaN,NaN,160.484,84.526235,2.0,94.0,172.5,231.75,300.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `patient_insurance.csv`

## 1. Dataset Preview

,patient_insurance_id,policy_number,coverage_percentage,policy_start_date,policy_end_date,patient_id,insurance_provider_id
0,1,POL55116683,50,2020-01-01,2022-12-31,2309,39
1,2,POL94717622,80,2022-12-31,2025-12-30,2309,1
2,3,POL90122917,80,2020-01-01,2020-12-31,22405,12
3,4,POL58454937,70,2020-12-31,2023-12-31,22405,17
4,5,POL84239721,50,2020-01-01,2020-12-31,23398,28

## 2. Dataset Dimensions

Number of Rows    : 21617
Number of Columns : 7

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
patient_insurance_id,int64,21617,0,0.0,21617
policy_number,object,21617,0,0.0,21613
coverage_percentage,int64,21617,0,0.0,5
policy_start_date,object,21617,0,0.0,4
policy_end_date,object,21617,0,0.0,6
patient_id,int64,21617,0,0.0,18000
insurance_provider_id,int64,21617,0,0.0,50

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
patient_insurance_id,21617.0,NaN,NaN,NaN,10809.0,6240.43472,1.0,5405.0,10809.0,16213.0,21617.0
policy_number,21617,21613,POL21840563,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
coverage_percentage,21617.0,NaN,NaN,NaN,70.069852,14.160107,50.0,60.0,70.0,80.0,90.0
policy_start_date,21617,4,2020-01-01,18000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
policy_end_date,21617,6,2022-12-31,6891,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_id,21617.0,NaN,NaN,NaN,14953.214045,8640.645878,1.0,7535.0,14920.0,22431.0,30000.0
insurance_provider_id,21617.0,NaN,NaN,NaN,25.434935,14.383106,1.0,13.0,25.0,38.0,50.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `bed.csv`

## 1. Dataset Preview

   bed_id bed_number bed_status  ward_id
0       1        1-1   Occupied        1
1       2        1-2   Occupied        1
2       3        1-3  Available        1
3       4        1-4   Occupied        1
4       5        1-5   Occupied        1

## 2. Dataset Dimensions

Number of Rows    : 415
Number of Columns : 4

## 3. Column Profile

           Data Type  Non-Null Count  Missing Count  Missing %  Unique Values
bed_id         int64             415              0        0.0            415
bed_number    object             415              0        0.0            415
bed_status    object             415              0        0.0              2
ward_id        int64             415              0        0.0             27

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
bed_id,415.0,NaN,NaN,NaN,208.0,119.944432,1.0,104.5,208.0,311.5,415.0
bed_number,415,415,27-20,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bed_status,415,2,Occupied,270,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ward_id,415.0,NaN,NaN,NaN,14.39759,7.730265,1.0,8.0,14.0,21.0,27.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `drug_inventory.csv`

## 1. Dataset Preview

,inventory_id,current_stock,reorder_level,inventory_status,last_restock_date,drug_id
0,1,347,170,Normal,2025-04-21,1
1,2,949,125,Normal,2023-03-30,2
2,3,293,246,Normal,2020-02-09,3
3,4,433,252,Normal,2021-03-06,4
4,5,641,114,Normal,2024-02-08,5

## 2. Dataset Dimensions

Number of Rows    : 250
Number of Columns : 6

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
inventory_id,int64,250,0,0.0,250
current_stock,int64,250,0,0.0,218
reorder_level,int64,250,0,0.0,151
inventory_status,object,250,0,0.0,2
last_restock_date,object,250,0,0.0,234
drug_id,int64,250,0,0.0,250

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
inventory_id,250.0,NaN,NaN,NaN,125.5,72.312977,1.0,63.25,125.5,187.75,250.0
current_stock,250.0,NaN,NaN,NaN,523.512,279.049408,53.0,292.25,550.5,755.75,996.0
reorder_level,250.0,NaN,NaN,NaN,204.54,58.099489,102.0,151.0,211.5,252.0,299.0
inventory_status,250,2,Normal,206,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last_restock_date,250,234,2023-01-29,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drug_id,250.0,NaN,NaN,NaN,125.5,72.312977,1.0,63.25,125.5,187.75,250.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `staff_assignment.csv`

## 1. Dataset Preview

   assignment_id  employee_id  ward_id    shift
0              1            2       24  Morning
1              2            4        2  Morning
2              3           17       24    Night
3              4           19       12    Night
4              5           20       22  Morning

## 2. Dataset Dimensions

Number of Rows    : 207
Number of Columns : 4

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
assignment_id,int64,207,0,0.0,207
employee_id,int64,207,0,0.0,207
ward_id,int64,207,0,0.0,27
shift,object,207,0,0.0,3

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
assignment_id,207.0,NaN,NaN,NaN,104.0,59.899917,1.0,52.5,104.0,155.5,207.0
employee_id,207.0,NaN,NaN,NaN,250.492754,142.548233,2.0,129.5,245.0,385.5,500.0
ward_id,207.0,NaN,NaN,NaN,14.048309,7.768969,1.0,7.5,14.0,21.5,27.0
shift,207,3,Night,76,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `admission.csv`

## 1. Dataset Preview

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7

## 2. Dataset Dimensions

Number of Rows    : 45000
Number of Columns : 10

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
admission_id,int64,45000,0,0.0,45000
admission_date,object,45000,0,0.0,2192
discharge_date,object,45000,0,0.0,2203
admission_type,object,45000,0,0.0,2
admission_status,object,45000,0,0.0,1
patient_id,int64,45000,0,0.0,23275
department_id,int64,45000,0,0.0,6
ward_id,int64,45000,0,0.0,27
bed_id,int64,45000,0,0.0,145
disease_id,int64,45000,0,0.0,20

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
admission_id,45000.0,NaN,NaN,NaN,22500.5,12990.525394,1.0,11250.75,22500.5,33750.25,45000.0
admission_date,45000,2192,2024-07-18,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discharge_date,45000,2203,2020-09-05,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
admission_type,45000,2,Elective,26923,NaN,NaN,NaN,NaN,NaN,NaN,NaN
admission_status,45000,1,Discharged,45000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_id,45000.0,NaN,NaN,NaN,14912.959911,8659.65722,1.0,7390.75,14878.5,22411.0,30000.0
department_id,45000.0,NaN,NaN,NaN,3.159044,1.564617,1.0,2.0,3.0,4.0,6.0
ward_id,45000.0,NaN,NaN,NaN,13.5262,7.34845,1.0,7.0,13.0,20.0,27.0
bed_id,45000.0,NaN,NaN,NaN,194.5948,113.66573,3.0,98.0,195.0,289.0,414.0
disease_id,45000.0,NaN,NaN,NaN,10.459844,5.771013,1.0,5.0,10.0,15.0,20.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `diagnostic_test.csv`

## 1. Dataset Preview

   test_id             test_name test_category  standard_cost  department_id
0        1           X-Ray Chest     Radiology           1328              7
1        2         CT Scan Brain     Radiology           4852              7
2        3             MRI Spine     Radiology           3541              7
3        4    Ultrasound Abdomen     Radiology           1665              7
4        5  Complete Blood Count     Pathology           4257              8

## 2. Dataset Dimensions

Number of Rows    : 9
Number of Columns : 5

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
test_id,int64,9,0,0.0,9
test_name,object,9,0,0.0,9
test_category,object,9,0,0.0,2
standard_cost,int64,9,0,0.0,9
department_id,int64,9,0,0.0,2

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
test_id,9.0,NaN,NaN,NaN,5.0,2.738613,1.0,3.0,5.0,7.0,9.0
test_name,9,9,X-Ray Chest,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
test_category,9,2,Pathology,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
standard_cost,9.0,NaN,NaN,NaN,2952.555556,1429.07646,924.0,1665.0,2796.0,4257.0,4852.0
department_id,9.0,NaN,NaN,NaN,7.555556,0.527046,7.0,7.0,8.0,8.0,8.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `patient_diagnostic.csv`

## 1. Dataset Preview

,patient_diagnostic_id,test_date,result_status,admission_id,test_id,doctor_id
0,1,2020-02-25,Normal,1,8,47
1,2,2020-02-25,Normal,1,2,43
2,3,2020-02-27,Abnormal,1,6,3
3,4,2022-03-04,Normal,2,1,3
4,5,2021-02-07,Abnormal,3,9,39

## 2. Dataset Dimensions

Number of Rows    : 63269
Number of Columns : 6

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
patient_diagnostic_id,int64,63269,0,0.0,63269
test_date,object,63269,0,0.0,2202
result_status,object,63269,0,0.0,2
admission_id,int64,63269,0,0.0,31512
test_id,int64,63269,0,0.0,9
doctor_id,int64,63269,0,0.0,50

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
patient_diagnostic_id,63269.0,NaN,NaN,NaN,31635.0,18264.331428,1.0,15818.0,31635.0,47452.0,63269.0
test_date,63269,2202,2021-07-23,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
result_status,63269,2,Abnormal,31823,NaN,NaN,NaN,NaN,NaN,NaN,NaN
admission_id,63269.0,NaN,NaN,NaN,22444.92015,13022.187557,1.0,11094.0,22450.0,33746.0,45000.0
test_id,63269.0,NaN,NaN,NaN,5.0,2.584661,1.0,3.0,5.0,7.0,9.0
doctor_id,63269.0,NaN,NaN,NaN,25.495187,14.455849,1.0,13.0,26.0,38.0,50.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `prescription.csv`

## 1. Dataset Preview

,prescription_id,dosage,frequency,duration_days,admission_id,drug_id
0,1,1 tablet,Twice a day,12,1,227
1,2,2 tablet,Twice a day,7,1,70
2,3,2 tablet,Thrice a day,3,1,234
3,4,2 tablet,Once a day,13,1,205
4,5,2 tablet,Twice a day,12,3,145

## 2. Dataset Dimensions

Number of Rows    : 73109
Number of Columns : 6

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
prescription_id,int64,73109,0,0.0,73109
dosage,object,73109,0,0.0,2
frequency,object,73109,0,0.0,3
duration_days,int64,73109,0,0.0,12
admission_id,int64,73109,0,0.0,29287
drug_id,int64,73109,0,0.0,250

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
prescription_id,73109.0,NaN,NaN,NaN,36555.0,21104.894752,1.0,18278.0,36555.0,54832.0,73109.0
dosage,73109,2,2 tablet,36596,NaN,NaN,NaN,NaN,NaN,NaN,NaN
frequency,73109,3,Twice a day,24498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration_days,73109.0,NaN,NaN,NaN,8.506545,3.45925,3.0,6.0,9.0,12.0,14.0
admission_id,73109.0,NaN,NaN,NaN,22471.248437,12977.848698,1.0,11173.0,22472.0,33672.0,45000.0
drug_id,73109.0,NaN,NaN,NaN,125.469682,72.268495,1.0,63.0,125.0,188.0,250.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `billing.csv`

## 1. Dataset Preview

,bill_id,bill_date,total_amount,insurance_covered_amount,patient_payable_amount,payment_status,payment_mode,admission_id
0,1,2025-05-26,68483,61634.7,6848.3,Paid,Insurance,1
1,2,2023-11-19,70917,35458.5,35458.5,Paid,Insurance,2
2,3,2023-02-20,28137,25323.3,2813.7,Pending,Insurance,3
3,4,2021-09-01,80665,64532.0,16133.0,Pending,Insurance,4
4,5,2021-07-13,54920,27460.0,27460.0,Pending,Insurance,5

## 2. Dataset Dimensions

Number of Rows    : 45000
Number of Columns : 8

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
bill_id,int64,45000,0,0.0,45000
bill_date,object,45000,0,0.0,2203
total_amount,int64,45000,0,0.0,32874
insurance_covered_amount,float64,45000,0,0.0,32763
patient_payable_amount,float64,45000,0,0.0,39533
payment_status,object,45000,0,0.0,2
payment_mode,object,45000,0,0.0,4
admission_id,int64,45000,0,0.0,45000

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
bill_id,45000.0,NaN,NaN,NaN,22500.5,12990.525394,1.0,11250.75,22500.5,33750.25,45000.0
bill_date,45000,2203,2020-09-05,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_amount,45000.0,NaN,NaN,NaN,37427.691311,20898.321091,5001.0,21231.0,34623.5,48039.25,89990.0
insurance_covered_amount,45000.0,NaN,NaN,NaN,21708.463711,18289.872062,0.0,6580.0,19210.5,32752.325,80956.8
patient_payable_amount,45000.0,NaN,NaN,NaN,15719.2276,16216.113367,500.3,4743.85,9712.15,20746.75,89921.0
payment_status,45000,2,Pending,22670,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_mode,45000,4,Insurance,35979,NaN,NaN,NaN,NaN,NaN,NaN,NaN
admission_id,45000.0,NaN,NaN,NaN,22500.5,12990.525394,1.0,11250.75,22500.5,33750.25,45000.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `billing_detail.csv`

## 1. Dataset Preview

   billing_detail_id charge_type  reference_id  amount  bill_id
0                  1        Room          76.0    4884        1
1                  2        Drug           NaN    1844        1
2                  3        Room         302.0   70010        2
3                  4        Test           NaN     562        2
4                  5        Drug           NaN    2489        2

## 2. Dataset Dimensions

Number of Rows    : 112402
Number of Columns : 5

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
billing_detail_id,int64,112402,0,0.00,112402
charge_type,object,112402,0,0.00,4
reference_id,float64,45000,67402,59.97,145
amount,int64,112402,0,0.00,31815
bill_id,int64,112402,0,0.00,45000

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
billing_detail_id,112402.0,NaN,NaN,NaN,56201.5,32447.806816,1.0,28101.25,56201.5,84301.75,112402.0
charge_type,112402,4,Room,45000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reference_id,45000.0,NaN,NaN,NaN,194.5948,113.66573,3.0,98.0,195.0,289.0,414.0
amount,112402.0,NaN,NaN,NaN,13157.063629,16771.971534,200.0,2020.0,4879.0,19000.75,120000.0
bill_id,112402.0,NaN,NaN,NaN,22503.190388,12991.639176,1.0,11270.0,22479.5,33752.0,45000.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

## 2. Beds Management — Hospital Beds Management

In [5]:
BEDS_RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw" / "Hospital Beds Management"
print(BEDS_RAW_DATA_DIR)

beds_file_names = ["patients.csv", "services_weekly.csv", "staff.csv", "staff_schedule.csv"]
for file_name in beds_file_names:
    file_path = BEDS_RAW_DATA_DIR / file_name
    print(f"\u2713 {file_name} found" if file_path.exists() else f"\u2717 {file_name} NOT found")

C:\Users\sr189\OneDrive\Desktop\Hospital Management Data Analysis\MedTrack_DV\data\raw\Hospital Beds Management
✓ patients.csv found
✓ services_weekly.csv found
✓ staff.csv found
✓ staff_schedule.csv found

In [6]:
for file_name in beds_file_names:
    df = pd.read_csv(BEDS_RAW_DATA_DIR / file_name)
    profile_table(df, file_name)

---

# 📊 Data Profile: `patients.csv`

## 1. Dataset Preview

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

## 2. Dataset Dimensions

Number of Rows    : 1000
Number of Columns : 7

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
patient_id,object,1000,0,0.0,1000
name,object,1000,0,0.0,993
age,int64,1000,0,0.0,90
arrival_date,object,1000,0,0.0,344
departure_date,object,1000,0,0.0,337
service,object,1000,0,0.0,4
satisfaction,int64,1000,0,0.0,40

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
patient_id,1000,1000,PAT-e2ef9c5f,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,1000,993,Matthew Moore,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,1000.0,NaN,NaN,NaN,45.337,25.999912,0.0,23.0,46.0,68.0,89.0
arrival_date,1000,344,2025-01-19,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
departure_date,1000,337,2025-10-16,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
service,1000,4,emergency,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
satisfaction,1000.0,NaN,NaN,NaN,79.597,11.550325,60.0,70.0,80.0,89.25,99.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `services_weekly.csv`

## 1. Dataset Preview

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none

## 2. Dataset Dimensions

Number of Rows    : 208
Number of Columns : 10

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
week,int64,208,0,0.0,52
month,int64,208,0,0.0,12
service,object,208,0,0.0,4
available_beds,int64,208,0,0.0,56
patients_request,int64,208,0,0.0,110
patients_admitted,int64,208,0,0.0,56
patients_refused,int64,208,0,0.0,80
patient_satisfaction,int64,208,0,0.0,40
staff_morale,int64,208,0,0.0,55
event,object,208,0,0.0,4

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
week,208.0,NaN,NaN,NaN,26.5,15.044539,1.0,13.75,26.5,39.25,52.0
month,208.0,NaN,NaN,NaN,6.923077,3.634755,1.0,4.0,7.0,10.0,12.0
service,208,4,emergency,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
available_beds,208.0,NaN,NaN,NaN,30.346154,15.172929,8.0,18.0,27.5,40.0,74.0
patients_request,208.0,NaN,NaN,NaN,64.870192,58.738572,5.0,23.75,49.0,86.0,388.0
patients_admitted,208.0,NaN,NaN,NaN,28.129808,14.676791,5.0,16.0,26.0,37.0,74.0
patients_refused,208.0,NaN,NaN,NaN,36.740385,55.015763,0.0,0.0,13.5,52.5,363.0
patient_satisfaction,208.0,NaN,NaN,NaN,80.0,11.125546,60.0,70.0,81.0,89.0,99.0
staff_morale,208.0,NaN,NaN,NaN,72.567308,15.457759,31.0,60.0,73.0,86.0,99.0
event,208,4,none,164,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `staff.csv`

## 1. Dataset Preview

       staff_id       staff_name    role    service
0  STF-5ca26577     Allison Hill  doctor  emergency
1  STF-02ae59ca      Noah Rhodes  doctor  emergency
2  STF-d8006e7c  Angie Henderson  doctor  emergency
3  STF-212d8b31    Daniel Wagner  doctor  emergency
4  STF-107a58e4  Cristian Santos  doctor  emergency

## 2. Dataset Dimensions

Number of Rows    : 110
Number of Columns : 4

## 3. Column Profile

           Data Type  Non-Null Count  Missing Count  Missing %  Unique Values
staff_id      object             110              0        0.0            110
staff_name    object             110              0        0.0            110
role          object             110              0        0.0              3
service       object             110              0        0.0              4

## 4. Statistical Summary

           count unique           top freq
staff_id     110    110  STF-5ca26577    1
staff_name   110    110  Allison Hill    1
role         110      3         nurse   69
service      110      4           ICU   32

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

---

# 📊 Data Profile: `staff_schedule.csv`

## 1. Dataset Preview

   week      staff_id    staff_name    role    service  present
0     1  STF-b77cdc60  Allison Hill  doctor  emergency        1
1     2  STF-b77cdc60  Allison Hill  doctor  emergency        1
2     3  STF-b77cdc60  Allison Hill  doctor  emergency        0
3     4  STF-b77cdc60  Allison Hill  doctor  emergency        1
4     5  STF-b77cdc60  Allison Hill  doctor  emergency        1

## 2. Dataset Dimensions

Number of Rows    : 6552
Number of Columns : 6

## 3. Column Profile

           Data Type  Non-Null Count  Missing Count  Missing %  Unique Values
week           int64            6552              0        0.0             52
staff_id      object            6552              0        0.0            126
staff_name    object            6552              0        0.0            126
role          object            6552              0        0.0              3
service       object            6552              0        0.0              4
present        int64            6552              0        0.0              2

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
week,6552.0,NaN,NaN,NaN,26.5,15.009476,1.0,13.75,26.5,39.25,52.0
staff_id,6552,126,STF-b77cdc60,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
staff_name,6552,126,Allison Hill,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
role,6552,3,nurse,3796,NaN,NaN,NaN,NaN,NaN,NaN,NaN
service,6552,4,emergency,2028,NaN,NaN,NaN,NaN,NaN,NaN,NaN
present,6552.0,NaN,NaN,NaN,0.599817,0.489973,0.0,0.0,1.0,1.0,1.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.

## 3. Readmission — Hospital Data for Patient Readmission Prediction

In [7]:
READMISSION_RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw" / "Hospital Data for Patient Readmission Prediction"
print(READMISSION_RAW_DATA_DIR)   # fixed: previously printed Beds Management's path by mistake

readmission_file_names = ["Healthcare Data Analysis for readmission.csv"]
for file_name in readmission_file_names:
    file_path = READMISSION_RAW_DATA_DIR / file_name
    print(f"\u2713 {file_name} found" if file_path.exists() else f"\u2717 {file_name} NOT found")

C:\Users\sr189\OneDrive\Desktop\Hospital Management Data Analysis\MedTrack_DV\data\raw\Hospital Data for Patient Readmission Prediction
✓ Healthcare Data Analysis for readmission.csv found

In [8]:
for file_name in readmission_file_names:
    df = pd.read_csv(READMISSION_RAW_DATA_DIR / file_name)
    profile_table(df, file_name)

---

# 📊 Data Profile: `Healthcare Data Analysis for readmission.csv`

## 1. Dataset Preview

,hospital_name,Admission_date,hospital_id,hospital_beds_available,occupied_beds,hospital_ward,patient_id,patient_gender,patient_age,patient_race,...,doctor_id,doctor_name,doctor_specialty,patient_assigned_doctor,patient_checkin_date,patient_checkout_date,patient_disease,patient_length_of_stay,discharge_status,readmission
0,The Johns Hopkins Hospital,30-01-2024,3946,260,90,Maternity,1421,Female,48,Asian,...,1725,Justin Morris,Rheumatology,False,14-07-2024,19-07-2024,Anxiety Disorders,6,Deceased,1
1,The Johns Hopkins Hospital,20-03-2022,7147,250,90,ICU,4922,Male,40,Black,...,7510,Latoya Moss,Pulmonology or Allergy and Immunology,False,19-07-2024,07/07/2024,Urinary Tract Infection (UTI),2,Deceased,1
2,The Johns Hopkins Hospital,13-07-2021,4174,350,220,Pediatrics,9804,Female,74,Black,...,7137,Michael Allen,Neurology,False,20-07-2024,29-06-2024,Hypertension (High Blood Pressure),17,Recovered,0
3,The Johns Hopkins Hospital,26-01-2021,2466,190,350,Pediatrics,5622,Male,82,Hispanic,...,8801,Rebecca Mccullough,Cardiology,False,25-06-2024,16-07-2024,Arthritis,28,Recovered,0
4,The Johns Hopkins Hospital,06/02/2024,3014,220,390,Surgery,3314,Male,62,Hispanic,...,3588,John Giles,Rheumatology,False,21-07-2024,19-07-2024,Cancer,16,Transferred,1

## 2. Dataset Dimensions

Number of Rows    : 10000
Number of Columns : 26

## 3. Column Profile

,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
hospital_name,object,10000,0,0.0,1
Admission_date,object,10000,0,0.0,1460
hospital_id,int64,10000,0,0.0,6074
hospital_beds_available,int64,10000,0,0.0,41
occupied_beds,int64,10000,0,0.0,41
hospital_ward,object,10000,0,0.0,5
patient_id,int64,10000,0,0.0,6022
patient_gender,object,10000,0,0.0,2
patient_age,int64,10000,0,0.0,96
patient_race,object,10000,0,0.0,5
patient_sat_score,int64,10000,0,0.0,151
patient_first_initial,object,10000,0,0.0,52
patient_last_name,object,10000,0,0.0,985
patient_waittime,int64,10000,0,0.0,8
department_referral,object,10000,0,0.0,19
time_slot,object,10000,0,0.0,1439
doctor_id,int64,10000,0,0.0,6019
doctor_name,object,10000,0,0.0,9379
doctor_specialty,object,10000,0,0.0,19
patient_assigned_doctor,bool,10000,0,0.0,2
patient_checkin_date,object,10000,0,0.0,30
patient_checkout_date,object,10000,0,0.0,29
patient_disease,object,10000,0,0.0,28
patient_length_of_stay,int64,10000,0,0.0,30
discharge_status,object,10000,0,0.0,3
readmission,int64,10000,0,0.0,2

## 4. Statistical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
hospital_name,10000,1,The Johns Hopkins Hospital,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Admission_date,10000,1460,17-09-2020,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hospital_id,10000.0,NaN,NaN,NaN,5515.9666,2605.495574,1000.0,3255.75,5516.5,7790.25,9998.0
hospital_beds_available,10000.0,NaN,NaN,NaN,299.111,117.973859,100.0,200.0,300.0,400.0,500.0
occupied_beds,10000.0,NaN,NaN,NaN,199.085,118.299418,0.0,100.0,200.0,300.0,400.0
hospital_ward,10000,5,Pediatrics,2067,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_id,10000.0,NaN,NaN,NaN,5498.7387,2615.168591,1000.0,3232.5,5478.5,7779.5,9999.0
patient_gender,10000,2,Male,5012,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_age,10000.0,NaN,NaN,NaN,47.283,27.719692,0.0,23.0,47.0,71.0,95.0
patient_race,10000,5,Hispanic,2042,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_sat_score,10000.0,NaN,NaN,NaN,847.802,432.952877,100.0,480.0,840.0,1220.0,1600.0
patient_first_initial,10000,52,K,232,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_last_name,10000,985,Smith,202,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_waittime,10000.0,NaN,NaN,NaN,67.824,34.519765,15.0,30.0,75.0,105.0,120.0
department_referral,10000,19,Neurology,1790,NaN,NaN,NaN,NaN,NaN,NaN,NaN
time_slot,10000,1439,05:56:00 AM,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
doctor_id,10000.0,NaN,NaN,NaN,5476.229,2626.286129,1000.0,3178.75,5445.5,7783.0,9998.0
doctor_name,10000,9379,Christopher Smith,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
doctor_specialty,10000,19,Neurology,1792,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_assigned_doctor,10000,2,False,5039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_checkin_date,10000,30,15-07-2024,375,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_checkout_date,10000,29,29-06-2024,386,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_disease,10000,28,Parkinson’s Disease,388,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_length_of_stay,10000.0,NaN,NaN,NaN,15.5065,8.611955,1.0,8.0,16.0,23.0,30.0
discharge_status,10000,3,Recovered,3384,NaN,NaN,NaN,NaN,NaN,NaN,NaN
readmission,10000.0,NaN,NaN,NaN,0.4142,0.492608,0.0,0.0,0.0,1.0,1.0

## 5. Duplicate Record Check

Duplicate Rows: 0
✓ No duplicate rows found.