In [1]:
import pandas as pd
import os

In [2]:
print(os.getcwd())

D:\MedTrack_DV\notebooks

In [3]:
raw_path = "../data/raw"

print(os.listdir(raw_path))

['department_analytics_dataset.csv', 'hospital_overview_dataset.csv', 'patient_flow_dataset.csv', 'README.txt', 'resource_utilization_dataset.csv']

In [4]:
hospital_overview = pd.read_csv(
    "../data/raw/hospital_overview_dataset.csv"
)

patient_flow = pd.read_csv(
    "../data/raw/patient_flow_dataset.csv"
)

department_analytics = pd.read_csv(
    "../data/raw/department_analytics_dataset.csv"
)

resource_utilization = pd.read_csv(
    "../data/raw/resource_utilization_dataset.csv"
)

In [5]:
print("Hospital Overview:", hospital_overview.shape)
print("Patient Flow:", patient_flow.shape)
print("Department Analytics:", department_analytics.shape)
print("Resource Utilization:", resource_utilization.shape)

Hospital Overview: (500, 23)
Patient Flow: (500, 20)
Department Analytics: (500, 24)
Resource Utilization: (500, 24)

In [6]:
hospital_overview.head()

,admission_id,patient_id,hospital_id,hospital_name,department_id,department_name,admission_date,discharge_date,admission_type,admission_source,...,patient_gender,diagnosis,insurance_type,total_bill_amount,payment_status,discharge_status,patient_satisfaction_score,mortality_flag,readmission_flag,length_of_stay_days
0,A0001,P0001,H003,Sunrise Multi-Specialty Hospital,D01,Emergency Department,2026-03-12,2026-03-20,Emergency,Outpatient Clinic,...,Male,Respiratory Infection,Corporate Insurance,4362.99,Pending,Recovered,3.3,0,0,8
1,A0002,P0002,H001,CityCare General Hospital,D07,General Surgery,2026-01-01,2026-01-06,Urgent,Outpatient Clinic,...,Female,Fracture,Corporate Insurance,2260.96,Pending,Stable,3.6,0,0,5
2,A0003,P0003,H003,Sunrise Multi-Specialty Hospital,D04,Orthopedics,2026-05-21,2026-05-28,Emergency,Outpatient Clinic,...,Female,Routine Surgery,Self Pay,1828.77,Paid,Stable,3.9,0,0,7
3,A0004,P0004,H003,Sunrise Multi-Specialty Hospital,D04,Orthopedics,2026-06-28,2026-07-01,Urgent,Emergency Department,...,Female,Fracture,Corporate Insurance,1675.08,Paid,Recovered,4.4,0,1,3
4,A0005,P0005,H001,CityCare General Hospital,D05,ICU,2026-05-03,2026-05-11,Emergency,Referral,...,Female,Hypertension,Private Insurance,2703.11,Paid,Stable,4.4,0,0,8

In [7]:
patient_flow.head()

,movement_id,admission_id,patient_id,hospital_id,movement_sequence,movement_type,from_department_id,current_department_id,from_department_name,current_department_name,bed_id,movement_datetime,movement_date,duration_in_department_hours,year,month,day_of_week,hour_of_day,shift,is_peak_hour
0,M0001,A0001,P0001,H003,1,Discharge,D00,D99,Outside Hospital,Discharge,B3-001,2026-03-15 20:00:00,2026-03-15,15.5,2026,March,Sunday,20,Evening,1
1,M0002,A0002,P0002,H001,2,Transfer,D01,D07,Emergency Department,General Surgery,B1-002,2026-01-03 22:00:00,2026-01-03,8.2,2026,January,Saturday,22,Evening,0
2,M0003,A0003,P0003,H003,3,Department Transfer,D04,D04,Orthopedics,Orthopedics,B3-003,2026-05-26 13:00:00,2026-05-26,18.3,2026,May,Tuesday,13,Afternoon,0
3,M0004,A0004,P0004,H003,1,Admission,D00,D04,Outside Hospital,Orthopedics,B3-004,2026-06-29 15:00:00,2026-06-29,23.5,2026,June,Monday,15,Afternoon,0
4,M0005,A0005,P0005,H001,2,Transfer,D01,D05,Emergency Department,ICU,B1-005,2026-05-10 12:00:00,2026-05-10,16.7,2026,May,Sunday,12,Afternoon,0

In [8]:
department_analytics.head()

,date,hospital_id,hospital_name,department_id,department_name,department_type,total_beds,occupied_beds_count,bed_occupancy_rate_pct,patients_admitted_count,...,mortality_rate_pct,avg_length_of_stay_days,avg_treatment_time_hours,transfer_events_count,nurses_on_duty,doctors_on_duty,staff_to_patient_ratio,equipment_downtime_hours,avg_satisfaction_score,department_efficiency_score
0,2026-01-01,H001,CityCare General Hospital,D01,Emergency Department,Emergency,35,19,54.29,5,...,0.0,3.22,25.29,6,9,3,2.400,3.65,4.26,68.53
1,2026-01-08,H002,Green Valley Medical Center,D04,Orthopedics,Specialty,35,23,65.71,3,...,0.0,3.70,5.15,7,6,4,3.333,0.00,4.65,81.52
2,2026-01-15,H003,Sunrise Multi-Specialty Hospital,D07,General Surgery,Surgical,40,29,72.50,12,...,0.0,2.45,23.54,7,8,5,1.083,3.74,4.36,78.44
3,2026-01-22,H001,CityCare General Hospital,D03,Cardiology,Specialty,30,16,53.33,5,...,0.0,5.66,13.58,6,7,2,1.800,2.07,3.95,70.45
4,2026-01-29,H002,Green Valley Medical Center,D06,Pediatrics,Medical,30,18,60.00,5,...,0.0,7.70,13.60,4,4,4,1.600,2.66,4.29,64.27

In [9]:
resource_utilization.head()

,resource_utilization_id,date,hospital_id,hospital_name,department_id,department_name,resource_type,resource_category,total_units_available,units_in_use,...,utilized_hours,idle_hours,downtime_hours,nurses_on_duty_snapshot,doctors_on_duty_snapshot,overtime_hours,avg_response_time_minutes,resource_condition,maintenance_due_flag,last_maintenance_date
0,R0001,2026-01-01,H001,CityCare General Hospital,D01,Emergency Department,Bed,General Bed,28,21,...,18.00,6.00,0.77,11,2,2.39,22.77,Good,0,2025-10-01
1,R0002,2026-01-06,H002,Green Valley Medical Center,D06,Pediatrics,Equipment,Patient Monitor,5,2,...,9.60,14.40,4.86,10,2,0.84,21.07,Good,0,2025-09-14
2,R0003,2026-01-11,H003,Sunrise Multi-Specialty Hospital,D04,Orthopedics,Clinical Staff,Nursing Staff,7,3,...,5.14,6.86,0.10,8,5,0.93,21.49,Fair,0,2025-10-04
3,R0004,2026-01-16,H001,CityCare General Hospital,D02,General Medicine,Bed,ICU Bed,14,10,...,17.14,6.86,4.98,13,2,2.09,10.19,Good,0,2025-11-12
4,R0005,2026-01-21,H002,Green Valley Medical Center,D07,General Surgery,Equipment,Ventilator,18,10,...,13.33,10.67,3.87,3,3,4.28,15.70,Good,0,2025-10-24

In [10]:
print("HOSPITAL OVERVIEW")
print(hospital_overview.columns.tolist())

print("\nPATIENT FLOW")
print(patient_flow.columns.tolist())

print("\nDEPARTMENT ANALYTICS")
print(department_analytics.columns.tolist())

print("\nRESOURCE UTILIZATION")
print(resource_utilization.columns.tolist())

HOSPITAL OVERVIEW
['admission_id', 'patient_id', 'hospital_id', 'hospital_name', 'department_id', 'department_name', 'admission_date', 'discharge_date', 'admission_type', 'admission_source', 'bed_id', 'bed_type', 'patient_age', 'patient_gender', 'diagnosis', 'insurance_type', 'total_bill_amount', 'payment_status', 'discharge_status', 'patient_satisfaction_score', 'mortality_flag', 'readmission_flag', 'length_of_stay_days']

PATIENT FLOW
['movement_id', 'admission_id', 'patient_id', 'hospital_id', 'movement_sequence', 'movement_type', 'from_department_id', 'current_department_id', 'from_department_name', 'current_department_name', 'bed_id', 'movement_datetime', 'movement_date', 'duration_in_department_hours', 'year', 'month', 'day_of_week', 'hour_of_day', 'shift', 'is_peak_hour']

DEPARTMENT ANALYTICS
['date', 'hospital_id', 'hospital_name', 'department_id', 'department_name', 'department_type', 'total_beds', 'occupied_beds_count', 'bed_occupancy_rate_pct', 'patients_admitted_count', 'patients_discharged_count', 'readmission_count', 'readmission_rate_pct', 'mortality_count', 'mortality_rate_pct', 'avg_length_of_stay_days', 'avg_treatment_time_hours', 'transfer_events_count', 'nurses_on_duty', 'doctors_on_duty', 'staff_to_patient_ratio', 'equipment_downtime_hours', 'avg_satisfaction_score', 'department_efficiency_score']

RESOURCE UTILIZATION
['resource_utilization_id', 'date', 'hospital_id', 'hospital_name', 'department_id', 'department_name', 'resource_type', 'resource_category', 'total_units_available', 'units_in_use', 'units_under_maintenance', 'utilization_rate_pct', 'shortage_flag', 'capacity_hours', 'utilized_hours', 'idle_hours', 'downtime_hours', 'nurses_on_duty_snapshot', 'doctors_on_duty_snapshot', 'overtime_hours', 'avg_response_time_minutes', 'resource_condition', 'maintenance_due_flag', 'last_maintenance_date']

In [11]:
hospital_overview.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   admission_id                500 non-null    object
 1   patient_id                  500 non-null    object
 2   hospital_id                 500 non-null    object
 3   hospital_name               500 non-null    object
 4   department_id               500 non-null    object
 5   department_name             500 non-null    object
 6   admission_date              500 non-null    object
 7   discharge_date              500 non-null    object
 8   admission_type              500 non-null    object
 9   admission_source            500 non-null    object
 10  bed_id                      500 non-null    object
 11  bed_type                    500 non-null    object
 12  patient_age                 500 non-null    int64
 13  patient_gender              500 non-null    object
 14  diagnosis                   500 non-null    object
 15  insurance_type              500 non-null    object
 16  total_bill_amount           500 non-null    float64
 17  payment_status              500 non-null    object
 18  discharge_status            500 non-null    object
 19  patient_satisfaction_score  500 non-null    float64
 20  mortality_flag              500 non-null    int64
 21  readmission_flag            500 non-null    int64
 22  length_of_stay_days         500 non-null    int64
dtypes: float64(2), int64(4), object(17)
memory usage: 90.0+ KB

In [12]:
patient_flow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   movement_id                   500 non-null    object
 1   admission_id                  500 non-null    object
 2   patient_id                    500 non-null    object
 3   hospital_id                   500 non-null    object
 4   movement_sequence             500 non-null    int64
 5   movement_type                 500 non-null    object
 6   from_department_id            500 non-null    object
 7   current_department_id         500 non-null    object
 8   from_department_name          500 non-null    object
 9   current_department_name       500 non-null    object
 10  bed_id                        500 non-null    object
 11  movement_datetime             500 non-null    object
 12  movement_date                 500 non-null    object
 13  duration_in_department_hours  500 non-null    float64
 14  year                          500 non-null    int64
 15  month                         500 non-null    object
 16  day_of_week                   500 non-null    object
 17  hour_of_day                   500 non-null    int64
 18  shift                         500 non-null    object
 19  is_peak_hour                  500 non-null    int64
dtypes: float64(1), int64(4), object(15)
memory usage: 78.2+ KB

In [13]:
department_analytics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         500 non-null    object
 1   hospital_id                  500 non-null    object
 2   hospital_name                500 non-null    object
 3   department_id                500 non-null    object
 4   department_name              500 non-null    object
 5   department_type              500 non-null    object
 6   total_beds                   500 non-null    int64
 7   occupied_beds_count          500 non-null    int64
 8   bed_occupancy_rate_pct       500 non-null    float64
 9   patients_admitted_count      500 non-null    int64
 10  patients_discharged_count    500 non-null    int64
 11  readmission_count            500 non-null    int64
 12  readmission_rate_pct         500 non-null    float64
 13  mortality_count              500 non-null    int64
 14  mortality_rate_pct           500 non-null    float64
 15  avg_length_of_stay_days      500 non-null    float64
 16  avg_treatment_time_hours     500 non-null    float64
 17  transfer_events_count        500 non-null    int64
 18  nurses_on_duty               500 non-null    int64
 19  doctors_on_duty              500 non-null    int64
 20  staff_to_patient_ratio       500 non-null    float64
 21  equipment_downtime_hours     500 non-null    float64
 22  avg_satisfaction_score       500 non-null    float64
 23  department_efficiency_score  500 non-null    float64
dtypes: float64(9), int64(9), object(6)
memory usage: 93.9+ KB

In [14]:
resource_utilization.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   resource_utilization_id    500 non-null    object
 1   date                       500 non-null    object
 2   hospital_id                500 non-null    object
 3   hospital_name              500 non-null    object
 4   department_id              500 non-null    object
 5   department_name            500 non-null    object
 6   resource_type              500 non-null    object
 7   resource_category          500 non-null    object
 8   total_units_available      500 non-null    int64
 9   units_in_use               500 non-null    int64
 10  units_under_maintenance    500 non-null    int64
 11  utilization_rate_pct       500 non-null    float64
 12  shortage_flag              500 non-null    int64
 13  capacity_hours             500 non-null    int64
 14  utilized_hours             500 non-null    float64
 15  idle_hours                 500 non-null    float64
 16  downtime_hours             500 non-null    float64
 17  nurses_on_duty_snapshot    500 non-null    int64
 18  doctors_on_duty_snapshot   500 non-null    int64
 19  overtime_hours             500 non-null    float64
 20  avg_response_time_minutes  500 non-null    float64
 21  resource_condition         500 non-null    object
 22  maintenance_due_flag       500 non-null    int64
 23  last_maintenance_date      500 non-null    object
dtypes: float64(6), int64(8), object(10)
memory usage: 93.9+ KB

In [15]:
print("Hospital Overview")
print(hospital_overview.isnull().sum())

Hospital Overview
admission_id                  0
patient_id                    0
hospital_id                   0
hospital_name                 0
department_id                 0
department_name               0
admission_date                0
discharge_date                0
admission_type                0
admission_source              0
bed_id                        0
bed_type                      0
patient_age                   0
patient_gender                0
diagnosis                     0
insurance_type                0
total_bill_amount             0
payment_status                0
discharge_status              0
patient_satisfaction_score    0
mortality_flag                0
readmission_flag              0
length_of_stay_days           0
dtype: int64

In [16]:
print("Patient Flow")
print(patient_flow.isnull().sum())

Patient Flow
movement_id                     0
admission_id                    0
patient_id                      0
hospital_id                     0
movement_sequence               0
movement_type                   0
from_department_id              0
current_department_id           0
from_department_name            0
current_department_name         0
bed_id                          0
movement_datetime               0
movement_date                   0
duration_in_department_hours    0
year                            0
month                           0
day_of_week                     0
hour_of_day                     0
shift                           0
is_peak_hour                    0
dtype: int64

In [17]:
print("Department Analytics")
print(department_analytics.isnull().sum())

Department Analytics
date                           0
hospital_id                    0
hospital_name                  0
department_id                  0
department_name                0
department_type                0
total_beds                     0
occupied_beds_count            0
bed_occupancy_rate_pct         0
patients_admitted_count        0
patients_discharged_count      0
readmission_count              0
readmission_rate_pct           0
mortality_count                0
mortality_rate_pct             0
avg_length_of_stay_days        0
avg_treatment_time_hours       0
transfer_events_count          0
nurses_on_duty                 0
doctors_on_duty                0
staff_to_patient_ratio         0
equipment_downtime_hours       0
avg_satisfaction_score         0
department_efficiency_score    0
dtype: int64

In [18]:
print("Resource Utilization")
print(resource_utilization.isnull().sum())

Resource Utilization
resource_utilization_id      0
date                         0
hospital_id                  0
hospital_name                0
department_id                0
department_name              0
resource_type                0
resource_category            0
total_units_available        0
units_in_use                 0
units_under_maintenance      0
utilization_rate_pct         0
shortage_flag                0
capacity_hours               0
utilized_hours               0
idle_hours                   0
downtime_hours               0
nurses_on_duty_snapshot      0
doctors_on_duty_snapshot     0
overtime_hours               0
avg_response_time_minutes    0
resource_condition           0
maintenance_due_flag         0
last_maintenance_date        0
dtype: int64

In [19]:
print("Hospital Overview duplicates:",
      hospital_overview.duplicated().sum())

print("Patient Flow duplicates:",
      patient_flow.duplicated().sum())

print("Department Analytics duplicates:",
      department_analytics.duplicated().sum())

print("Resource Utilization duplicates:",
      resource_utilization.duplicated().sum())

Hospital Overview duplicates: 0
Patient Flow duplicates: 0
Department Analytics duplicates: 0
Resource Utilization duplicates: 0

In [20]:
print("Hospital Overview")
print("Admission IDs:", hospital_overview["admission_id"].nunique())
print("Patient IDs:", hospital_overview["patient_id"].nunique())
print("Hospital IDs:", hospital_overview["hospital_id"].nunique())
print("Department IDs:", hospital_overview["department_id"].nunique())

Hospital Overview
Admission IDs: 500
Patient IDs: 500
Hospital IDs: 3
Department IDs: 7

In [21]:
print("Patient Flow")
print("Movement IDs:", patient_flow["movement_id"].nunique())
print("Admission IDs:", patient_flow["admission_id"].nunique())
print("Patient IDs:", patient_flow["patient_id"].nunique())

Patient Flow
Movement IDs: 500
Admission IDs: 500
Patient IDs: 500

In [22]:
print("Department Analytics")
print("Hospital IDs:", department_analytics["hospital_id"].nunique())
print("Department IDs:", department_analytics["department_id"].nunique())
print("Dates:", department_analytics["date"].nunique())

Department Analytics
Hospital IDs: 3
Department IDs: 7
Dates: 180

In [23]:
print("Resource Utilization")
print("Resource IDs:",
      resource_utilization["resource_utilization_id"].nunique())

print("Hospital IDs:",
      resource_utilization["hospital_id"].nunique())

print("Department IDs:",
      resource_utilization["department_id"].nunique())

print("Dates:",
      resource_utilization["date"].nunique())

Resource Utilization
Resource IDs: 500
Hospital IDs: 3
Department IDs: 7
Dates: 36

In [24]:
datasets = {
    "Hospital Overview": hospital_overview,
    "Patient Flow": patient_flow,
    "Department Analytics": department_analytics,
    "Resource Utilization": resource_utilization
}

for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("Missing values:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())

============================================================
Hospital Overview
Rows: 500
Columns: 23
Missing values: 0
Duplicate rows: 0
============================================================
Patient Flow
Rows: 500
Columns: 20
Missing values: 0
Duplicate rows: 0
============================================================
Department Analytics
Rows: 500
Columns: 24
Missing values: 0
Duplicate rows: 0
============================================================
Resource Utilization
Rows: 500
Columns: 24
Missing values: 0
Duplicate rows: 0

In [25]:
profiling_summary = []

for name, df in datasets.items():
    profiling_summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

profiling_report = pd.DataFrame(profiling_summary)

profiling_report

                Dataset  Rows  Columns  Missing Values  Duplicate Rows
0     Hospital Overview   500       23               0               0
1          Patient Flow   500       20               0               0
2  Department Analytics   500       24               0               0
3  Resource Utilization   500       24               0               0

In [26]:
profiling_report.to_csv(
    "../data/processed/profiling_report.csv",
    index=False
)

print("Profiling report saved successfully.")

Profiling report saved successfully.