In [1]:
import pandas as pd

In [2]:
hospital = pd.read_csv(
    "../data/processed/hospital_overview_normalized.csv"
)

patient_flow = pd.read_csv(
    "../data/processed/patient_flow_normalized.csv"
)

department = pd.read_csv(
    "../data/processed/department_analytics_normalized.csv"
)

resource = pd.read_csv(
    "../data/processed/resource_utilization_normalized.csv"
)

print("All normalized datasets loaded successfully.")

All normalized datasets loaded successfully.

In [3]:
print("ROW COUNT VALIDATION")
print("=" * 50)

print("Hospital Overview:", len(hospital))
print("Patient Flow:", len(patient_flow))
print("Department Analytics:", len(department))
print("Resource Utilization:", len(resource))

ROW COUNT VALIDATION
==================================================
Hospital Overview: 500
Patient Flow: 500
Department Analytics: 500
Resource Utilization: 500

In [4]:
print("COLUMN COUNT VALIDATION")
print("=" * 50)

print("Hospital Overview:", len(hospital.columns))
print("Patient Flow:", len(patient_flow.columns))
print("Department Analytics:", len(department.columns))
print("Resource Utilization:", len(resource.columns))

COLUMN COUNT VALIDATION
==================================================
Hospital Overview: 24
Patient Flow: 21
Department Analytics: 24
Resource Utilization: 24

In [5]:
print("MISSING VALUE VALIDATION")
print("=" * 50)

print("Hospital Overview:", hospital.isnull().sum().sum())
print("Patient Flow:", patient_flow.isnull().sum().sum())
print("Department Analytics:", department.isnull().sum().sum())
print("Resource Utilization:", resource.isnull().sum().sum())

MISSING VALUE VALIDATION
==================================================
Hospital Overview: 0
Patient Flow: 0
Department Analytics: 0
Resource Utilization: 0

In [6]:
print("Hospital Overview missing values:")
print(hospital.isnull().sum()[hospital.isnull().sum() > 0])

print("\nPatient Flow missing values:")
print(patient_flow.isnull().sum()[patient_flow.isnull().sum() > 0])

print("\nDepartment Analytics missing values:")
print(department.isnull().sum()[department.isnull().sum() > 0])

print("\nResource Utilization missing values:")
print(resource.isnull().sum()[resource.isnull().sum() > 0])

Hospital Overview missing values:
Series([], dtype: int64)

Patient Flow missing values:
Series([], dtype: int64)

Department Analytics missing values:
Series([], dtype: int64)

Resource Utilization missing values:
Series([], dtype: int64)

In [7]:
print("DUPLICATE VALIDATION")
print("=" * 50)

print("Hospital Overview:", hospital.duplicated().sum())
print("Patient Flow:", patient_flow.duplicated().sum())
print("Department Analytics:", department.duplicated().sum())
print("Resource Utilization:", resource.duplicated().sum())

DUPLICATE VALIDATION
==================================================
Hospital Overview: 0
Patient Flow: 0
Department Analytics: 0
Resource Utilization: 0

In [8]:
print("Hospital Overview grain validation")

print("Total rows:", len(hospital))

print("Unique admission IDs:",
      hospital["admission_id"].nunique())

print("Duplicate admission IDs:",
      hospital["admission_id"].duplicated().sum())

Hospital Overview grain validation
Total rows: 500
Unique admission IDs: 500
Duplicate admission IDs: 0

In [9]:
print("Patient Flow grain validation")

print("Total rows:", len(patient_flow))

print("Unique movement IDs:",
      patient_flow["movement_id"].nunique())

print("Duplicate movement IDs:",
      patient_flow["movement_id"].duplicated().sum())

Patient Flow grain validation
Total rows: 500
Unique movement IDs: 500
Duplicate movement IDs: 0

In [10]:
department_key = [
    "hospital_id",
    "department_id",
    "date"
]

print("Department Analytics grain validation")

print("Total rows:", len(department))

print(
    "Unique hospital + department + date combinations:",
    department[department_key].drop_duplicates().shape[0]
)

Department Analytics grain validation
Total rows: 500
Unique hospital + department + date combinations: 500

In [11]:
resource_key = [
    "hospital_id",
    "department_id",
    "date",
    "resource_type"
]

print("Resource Utilization grain validation")

print("Total rows:", len(resource))

print(
    "Unique hospital + department + date + resource combinations:",
    resource[resource_key].drop_duplicates().shape[0]
)

Resource Utilization grain validation
Total rows: 500
Unique hospital + department + date + resource combinations: 252

In [12]:
resource_duplicates = resource[
    resource.duplicated(
        subset=[
            "hospital_id",
            "department_id",
            "date",
            "resource_type"
        ],
        keep=False
    )
]

print("Number of rows involved in repeated combinations:",
      len(resource_duplicates))

resource_duplicates.head(20)

Number of rows involved in repeated combinations: 496

,resource_utilization_id,date,hospital_id,hospital_name,department_id,department_name,resource_type,resource_category,total_units_available,units_in_use,...,utilized_hours,idle_hours,downtime_hours,nurses_on_duty_snapshot,doctors_on_duty_snapshot,overtime_hours,avg_response_time_minutes,resource_condition,maintenance_due_flag,last_maintenance_date
0,R0001,2026-01-01,H001,CityCare General Hospital,D01,emergency department,Bed,General Bed,28,21,...,18.00,6.00,0.77,11,2,2.39,22.77,Good,0,2025-10-01
1,R0002,2026-01-06,H002,Green Valley Medical Center,D06,pediatrics,Equipment,Patient Monitor,5,2,...,9.60,14.40,4.86,10,2,0.84,21.07,Good,0,2025-09-14
2,R0003,2026-01-11,H003,Sunrise Multi-Specialty Hospital,D04,orthopedics,Clinical Staff,Nursing Staff,7,3,...,5.14,6.86,0.10,8,5,0.93,21.49,Fair,0,2025-10-04
3,R0004,2026-01-16,H001,CityCare General Hospital,D02,general medicine,Bed,ICU Bed,14,10,...,17.14,6.86,4.98,13,2,2.09,10.19,Good,0,2025-11-12
4,R0005,2026-01-21,H002,Green Valley Medical Center,D07,general surgery,Equipment,Ventilator,18,10,...,13.33,10.67,3.87,3,3,4.28,15.70,Good,0,2025-10-24
5,R0006,2026-01-26,H003,Sunrise Multi-Specialty Hospital,D05,icu,Clinical Staff,Doctors,28,17,...,7.29,4.71,0.01,14,2,3.64,10.23,Good,0,2025-12-08
6,R0007,2026-01-31,H001,CityCare General Hospital,D03,cardiology,Bed,Private Bed,14,12,...,20.57,3.43,0.21,11,5,0.33,18.97,Good,0,2026-01-14
7,R0008,2026-02-05,H002,Green Valley Medical Center,D01,emergency department,Equipment,X-Ray Unit,18,11,...,14.67,9.33,2.62,3,5,4.34,9.83,Good,0,2026-01-05
8,R0009,2026-02-10,H003,Sunrise Multi-Specialty Hospital,D06,pediatrics,Clinical Staff,Nursing Staff,27,18,...,8.00,4.00,1.68,9,4,3.54,22.89,Good,0,2025-12-17
9,R0010,2026-02-15,H001,CityCare General Hospital,D04,orthopedics,Bed,Semi-Private Bed,38,31,...,19.58,4.42,4.92,6,2,4.99,9.60,Fair,1,2025-11-19
10,R0011,2026-02-20,H002,Green Valley Medical Center,D02,general medicine,Equipment,Infusion Pump,27,17,...,15.11,8.89,3.81,8,2,3.47,15.35,Good,1,2025-11-14
11,R0012,2026-02-25,H003,Sunrise Multi-Specialty Hospital,D07,general surgery,Clinical Staff,Doctors,29,17,...,7.03,4.97,1.02,10,2,3.56,11.33,Good,0,2025-11-13
12,R0013,2026-03-02,H001,CityCare General Hospital,D05,icu,Bed,General Bed,18,11,...,14.67,9.33,4.54,8,2,3.20,3.05,Needs Maintenance,1,2025-11-08
13,R0014,2026-03-07,H002,Green Valley Medical Center,D03,cardiology,Equipment,Patient Monitor,10,5,...,12.00,12.00,1.17,9,1,3.97,7.28,Needs Maintenance,1,2026-01-03
14,R0015,2026-03-12,H003,Sunrise Multi-Specialty Hospital,D01,emergency department,Clinical Staff,Nursing Staff,13,7,...,6.46,5.54,0.90,14,2,0.92,11.81,Good,0,2025-12-03
15,R0016,2026-03-17,H001,CityCare General Hospital,D06,pediatrics,Bed,ICU Bed,21,11,...,12.57,11.43,2.55,3,2,2.01,11.21,Needs Maintenance,1,2025-12-03
16,R0017,2026-03-22,H002,Green Valley Medical Center,D04,orthopedics,Equipment,Ventilator,15,10,...,16.00,8.00,2.84,7,3,1.59,15.80,Needs Maintenance,1,2025-11-26
17,R0018,2026-03-27,H003,Sunrise Multi-Specialty Hospital,D02,general medicine,Clinical Staff,Doctors,25,16,...,7.68,4.32,0.51,10,1,3.22,14.40,Good,0,2025-12-19
18,R0019,2026-04-01,H001,CityCare General Hospital,D07,general surgery,Bed,Private Bed,17,14,...,19.76,4.24,2.48,3,1,2.56,15.13,Good,0,2026-03-20
19,R0020,2026-04-06,H002,Green Valley Medical Center,D05,icu,Equipment,X-Ray Unit,26,21,...,19.38,4.62,1.48,10,2,1.74,14.90,Good,0,2026-02-04

In [13]:
print(
    resource_duplicates[
        [
            "hospital_id",
            "department_id",
            "date",
            "resource_type"
        ]
    ].value_counts().head(20)
)

hospital_id  department_id  date        resource_type
H001         D01            2026-01-01  Bed              2
                            2026-01-16  Bed              2
                            2026-01-31  Bed              2
                            2026-02-15  Bed              2
                            2026-03-02  Bed              2
                            2026-03-17  Bed              2
                            2026-04-01  Bed              2
                            2026-04-16  Bed              2
                            2026-05-01  Bed              2
                            2026-05-16  Bed              2
                            2026-05-31  Bed              2
                            2026-06-15  Bed              2
             D02            2026-01-01  Bed              2
                            2026-01-16  Bed              2
                            2026-01-31  Bed              2
                            2026-02-15  Bed              2
                            2026-03-02  Bed              2
                            2026-03-17  Bed              2
                            2026-04-01  Bed              2
                            2026-04-16  Bed              2
Name: count, dtype: int64

In [14]:
# Show all columns for one repeated combination

example = resource_duplicates[
    (resource_duplicates["hospital_id"] == "H001") &
    (resource_duplicates["department_id"] == "D01") &
    (resource_duplicates["date"] == "2026-01-01") &
    (resource_duplicates["resource_type"] == "Bed")
]

example

,resource_utilization_id,date,hospital_id,hospital_name,department_id,department_name,resource_type,resource_category,total_units_available,units_in_use,...,utilized_hours,idle_hours,downtime_hours,nurses_on_duty_snapshot,doctors_on_duty_snapshot,overtime_hours,avg_response_time_minutes,resource_condition,maintenance_due_flag,last_maintenance_date
0,R0001,2026-01-01,H001,CityCare General Hospital,D01,emergency department,Bed,General Bed,28,21,...,18.00,6.00,0.77,11,2,2.39,22.77,Good,0,2025-10-01
252,R0253,2026-01-01,H001,CityCare General Hospital,D01,emergency department,Bed,General Bed,33,16,...,11.64,12.36,2.41,13,5,0.61,12.09,Good,1,2025-09-07

In [15]:
print(
    example.T
)

                                                 0    \
resource_utilization_id                        R0001
date                                      2026-01-01
hospital_id                                     H001
hospital_name              CityCare General Hospital
department_id                                    D01
department_name                 emergency department
resource_type                                    Bed
resource_category                        General Bed
total_units_available                             28
units_in_use                                      21
units_under_maintenance                            2
utilization_rate_pct                            75.0
shortage_flag                                      0
capacity_hours                                    24
utilized_hours                                  18.0
idle_hours                                       6.0
downtime_hours                                  0.77
nurses_on_duty_snapshot                           11
doctors_on_duty_snapshot                           2
overtime_hours                                  2.39
avg_response_time_minutes                      22.77
resource_condition                              Good
maintenance_due_flag                               0
last_maintenance_date                     2025-10-01

                                                 252
resource_utilization_id                        R0253
date                                      2026-01-01
hospital_id                                     H001
hospital_name              CityCare General Hospital
department_id                                    D01
department_name                 emergency department
resource_type                                    Bed
resource_category                        General Bed
total_units_available                             33
units_in_use                                      16
units_under_maintenance                            3
utilization_rate_pct                           48.48
shortage_flag                                      0
capacity_hours                                    24
utilized_hours                                 11.64
idle_hours                                     12.36
downtime_hours                                  2.41
nurses_on_duty_snapshot                           13
doctors_on_duty_snapshot                           5
overtime_hours                                  0.61
avg_response_time_minutes                      12.09
resource_condition                              Good
maintenance_due_flag                               1
last_maintenance_date                     2025-09-07

In [16]:
# Check how many records exist for each resource type
print(resource["resource_type"].value_counts())

resource_type
Bed               167
Equipment         167
Clinical Staff    166
Name: count, dtype: int64

In [17]:
# Check how many records exist for each resource category
print(resource["resource_category"].value_counts())

resource_category
Doctors             83
Nursing Staff       83
Patient Monitor     42
General Bed         42
ICU Bed             42
Ventilator          42
Private Bed         42
X-Ray Unit          42
Semi-Private Bed    41
Infusion Pump       41
Name: count, dtype: int64

In [18]:
# Check whether each resource type/category combination is repeated
print(
    resource[
        [
            "resource_type",
            "resource_category"
        ]
    ].value_counts()
)

resource_type   resource_category
Clinical Staff  Doctors              83
                Nursing Staff        83
Bed             ICU Bed              42
                General Bed          42
                Private Bed          42
Equipment       Patient Monitor      42
                X-Ray Unit           42
                Ventilator           42
Bed             Semi-Private Bed     41
Equipment       Infusion Pump        41
Name: count, dtype: int64

In [19]:
resource_key_with_category = [
    "hospital_id",
    "department_id",
    "date",
    "resource_type",
    "resource_category"
]

print("Resource Utilization grain validation with category")

print("Total rows:", len(resource))

print(
    "Unique hospital + department + date + resource type + category combinations:",
    resource[resource_key_with_category].drop_duplicates().shape[0]
)

Resource Utilization grain validation with category
Total rows: 500
Unique hospital + department + date + resource type + category combinations: 252

In [20]:
resource_duplicates_category = resource[
    resource.duplicated(
        subset=resource_key_with_category,
        keep=False
    )
]

print(
    "Rows involved in repeated combinations:",
    len(resource_duplicates_category)
)

Rows involved in repeated combinations: 496

In [21]:
# Count how many times each resource_utilization_id appears

print(
    resource["resource_utilization_id"].duplicated().sum()
)

0

In [22]:
# Check whether the resource IDs themselves are unique

print(
    resource["resource_utilization_id"].nunique()
)

print(
    len(resource)
)

500
500

In [23]:
# Check the number of records for each hospital, department and date

resource.groupby(
    ["hospital_id", "department_id", "date"]
).size().value_counts().sort_index()

1      4
2    248
Name: count, dtype: int64

In [24]:
# Show one hospital + department + date combination
# that contains multiple resource records

example_group = resource[
    (resource["hospital_id"] == "H001") &
    (resource["department_id"] == "D01") &
    (resource["date"] == "2026-01-01")
]

example_group[
    [
        "resource_utilization_id",
        "resource_type",
        "resource_category",
        "total_units_available",
        "units_in_use"
    ]
]

,resource_utilization_id,resource_type,resource_category,total_units_available,units_in_use
0,R0001,Bed,General Bed,28,21
252,R0253,Bed,General Bed,33,16

In [25]:
resource[
    (resource["hospital_id"] == "H001") &
    (resource["department_id"] == "D01") &
    (resource["date"] == "2026-01-01")
][
    [
        "resource_utilization_id",
        "resource_type",
        "resource_category",
        "total_units_available",
        "units_in_use",
        "units_under_maintenance",
        "utilization_rate_pct",
        "capacity_hours",
        "utilized_hours",
        "idle_hours",
        "downtime_hours"
    ]
]

,resource_utilization_id,resource_type,resource_category,total_units_available,units_in_use,units_under_maintenance,utilization_rate_pct,capacity_hours,utilized_hours,idle_hours,downtime_hours
0,R0001,Bed,General Bed,28,21,2,75.00,24,18.00,6.00,0.77
252,R0253,Bed,General Bed,33,16,3,48.48,24,11.64,12.36,2.41

In [26]:
# Check the two observations for each resource combination
# and see whether their IDs follow a systematic pattern.

resource_sorted = resource.sort_values(
    [
        "hospital_id",
        "department_id",
        "date",
        "resource_type",
        "resource_category"
    ]
)

resource_sorted[
    resource_sorted.duplicated(
        subset=[
            "hospital_id",
            "department_id",
            "date",
            "resource_type",
            "resource_category"
        ],
        keep=False
    )
][
    [
        "resource_utilization_id",
        "date",
        "hospital_id",
        "department_id",
        "resource_type",
        "resource_category"
    ]
].head(30)

,resource_utilization_id,date,hospital_id,department_id,resource_type,resource_category
0,R0001,2026-01-01,H001,D01,Bed,General Bed
252,R0253,2026-01-01,H001,D01,Bed,General Bed
147,R0148,2026-01-16,H001,D01,Bed,ICU Bed
399,R0400,2026-01-16,H001,D01,Bed,ICU Bed
42,R0043,2026-01-31,H001,D01,Bed,Private Bed
294,R0295,2026-01-31,H001,D01,Bed,Private Bed
189,R0190,2026-02-15,H001,D01,Bed,Semi-Private Bed
441,R0442,2026-02-15,H001,D01,Bed,Semi-Private Bed
84,R0085,2026-03-02,H001,D01,Bed,General Bed
336,R0337,2026-03-02,H001,D01,Bed,General Bed
231,R0232,2026-03-17,H001,D01,Bed,ICU Bed
483,R0484,2026-03-17,H001,D01,Bed,ICU Bed
126,R0127,2026-04-01,H001,D01,Bed,Private Bed
378,R0379,2026-04-01,H001,D01,Bed,Private Bed
21,R0022,2026-04-16,H001,D01,Bed,Semi-Private Bed
273,R0274,2026-04-16,H001,D01,Bed,Semi-Private Bed
168,R0169,2026-05-01,H001,D01,Bed,General Bed
420,R0421,2026-05-01,H001,D01,Bed,General Bed
63,R0064,2026-05-16,H001,D01,Bed,ICU Bed
315,R0316,2026-05-16,H001,D01,Bed,ICU Bed
210,R0211,2026-05-31,H001,D01,Bed,Private Bed
462,R0463,2026-05-31,H001,D01,Bed,Private Bed
105,R0106,2026-06-15,H001,D01,Bed,Semi-Private Bed
357,R0358,2026-06-15,H001,D01,Bed,Semi-Private Bed
108,R0109,2026-01-01,H001,D02,Bed,General Bed
360,R0361,2026-01-01,H001,D02,Bed,General Bed
3,R0004,2026-01-16,H001,D02,Bed,ICU Bed
255,R0256,2026-01-16,H001,D02,Bed,ICU Bed
150,R0151,2026-01-31,H001,D02,Bed,Private Bed
402,R0403,2026-01-31,H001,D02,Bed,Private Bed

In [27]:
# Compare the two repeated records completely

pair = resource[
    (resource["hospital_id"] == "H001") &
    (resource["department_id"] == "D01") &
    (resource["date"] == "2026-01-01") &
    (resource["resource_type"] == "Bed") &
    (resource["resource_category"] == "General Bed")
]

print(pair.T)

                                                 0    \
resource_utilization_id                        R0001
date                                      2026-01-01
hospital_id                                     H001
hospital_name              CityCare General Hospital
department_id                                    D01
department_name                 emergency department
resource_type                                    Bed
resource_category                        General Bed
total_units_available                             28
units_in_use                                      21
units_under_maintenance                            2
utilization_rate_pct                            75.0
shortage_flag                                      0
capacity_hours                                    24
utilized_hours                                  18.0
idle_hours                                       6.0
downtime_hours                                  0.77
nurses_on_duty_snapshot                           11
doctors_on_duty_snapshot                           2
overtime_hours                                  2.39
avg_response_time_minutes                      22.77
resource_condition                              Good
maintenance_due_flag                               0
last_maintenance_date                     2025-10-01

                                                 252
resource_utilization_id                        R0253
date                                      2026-01-01
hospital_id                                     H001
hospital_name              CityCare General Hospital
department_id                                    D01
department_name                 emergency department
resource_type                                    Bed
resource_category                        General Bed
total_units_available                             33
units_in_use                                      16
units_under_maintenance                            3
utilization_rate_pct                           48.48
shortage_flag                                      0
capacity_hours                                    24
utilized_hours                                 11.64
idle_hours                                     12.36
downtime_hours                                  2.41
nurses_on_duty_snapshot                           13
doctors_on_duty_snapshot                           5
overtime_hours                                  0.61
avg_response_time_minutes                      12.09
resource_condition                              Good
maintenance_due_flag                               1
last_maintenance_date                     2025-09-07

In [28]:
resource[
    resource["resource_utilization_id"].isin(["R0001", "R0253"])
][[
    "resource_utilization_id",
    "date",
    "hospital_id",
    "department_id",
    "resource_type",
    "resource_category"
]]

,resource_utilization_id,date,hospital_id,department_id,resource_type,resource_category
0,R0001,2026-01-01,H001,D01,Bed,General Bed
252,R0253,2026-01-01,H001,D01,Bed,General Bed

In [29]:
print("Patient IDs in Hospital Overview:", hospital["patient_id"].nunique())
print("Patient IDs in Patient Flow:", patient_flow["patient_id"].nunique())

print(
    "Patient IDs in Patient Flow that are not in Hospital Overview:",
    patient_flow.loc[
        ~patient_flow["patient_id"].isin(hospital["patient_id"]),
        "patient_id"
    ].nunique()
)

Patient IDs in Hospital Overview: 500
Patient IDs in Patient Flow: 500
Patient IDs in Patient Flow that are not in Hospital Overview: 0

In [30]:
print("Admission IDs in Hospital Overview:", hospital["admission_id"].nunique())
print("Admission IDs in Patient Flow:", patient_flow["admission_id"].nunique())

print(
    "Admission IDs in Patient Flow that are not in Hospital Overview:",
    patient_flow.loc[
        ~patient_flow["admission_id"].isin(hospital["admission_id"]),
        "admission_id"
    ].nunique()
)

Admission IDs in Hospital Overview: 500
Admission IDs in Patient Flow: 500
Admission IDs in Patient Flow that are not in Hospital Overview: 0

In [31]:
print("Department IDs in Hospital Overview:",
      hospital["department_id"].nunique())

print("Department IDs in Patient Flow:",
      patient_flow["department_id"].nunique())

print("Department IDs in Department Analytics:",
      department["department_id"].nunique())

print(
    "Department IDs in Patient Flow not in Hospital Overview:",
    patient_flow.loc[
        ~patient_flow["department_id"].isin(hospital["department_id"]),
        "department_id"
    ].nunique()
)

print(
    "Department IDs in Department Analytics not in Hospital Overview:",
    department.loc[
        ~department["department_id"].isin(hospital["department_id"]),
        "department_id"
    ].nunique()
)

Department IDs in Hospital Overview: 7

KeyError: 'department_id'

In [32]:
print("Patient Flow columns:")
print(patient_flow.columns.tolist())

Patient Flow columns:
['movement_id', 'admission_id', 'patient_id', 'hospital_id', 'movement_sequence', 'movement_type', 'from_department_id', 'current_department_id', 'from_department_name', 'current_department_name', 'bed_id', 'movement_datetime', 'movement_date', 'duration_in_department_hours', 'year', 'month', 'day_of_week', 'hour_of_day', 'shift', 'is_peak_hour', 'date']

In [33]:
print("Department IDs in Hospital Overview:",
      hospital["department_id"].nunique())

print("From Department IDs in Patient Flow:",
      patient_flow["from_department_id"].nunique())

print("Current Department IDs in Patient Flow:",
      patient_flow["current_department_id"].nunique())

print("Department IDs in Department Analytics:",
      department["department_id"].nunique())

Department IDs in Hospital Overview: 7
From Department IDs in Patient Flow: 8
Current Department IDs in Patient Flow: 8
Department IDs in Department Analytics: 7

In [34]:
print(
    "From Department IDs in Patient Flow not in Hospital Overview:"
)

print(
    patient_flow.loc[
        ~patient_flow["from_department_id"].isin(
            hospital["department_id"]
        ),
        "from_department_id"
    ].dropna().unique()
)

print(
    "Current Department IDs in Patient Flow not in Hospital Overview:"
)

print(
    patient_flow.loc[
        ~patient_flow["current_department_id"].isin(
            hospital["department_id"]
        ),
        "current_department_id"
    ].dropna().unique()
)

From Department IDs in Patient Flow not in Hospital Overview:
['D00']
Current Department IDs in Patient Flow not in Hospital Overview:
['D99']

In [35]:
print(
    patient_flow[
        patient_flow["from_department_id"] == "D00"
    ][
        [
            "movement_id",
            "movement_type",
            "from_department_id",
            "current_department_id",
            "from_department_name",
            "current_department_name"
        ]
    ].head(20)
)

   movement_id movement_type from_department_id current_department_id  \
0        M0001     Discharge                D00                   D99
3        M0004     Admission                D00                   D04
6        M0007     Admission                D00                   D07
9        M0010     Admission                D00                   D05
12       M0013     Admission                D00                   D04
15       M0016     Admission                D00                   D06
18       M0019     Admission                D00                   D05
21       M0022     Admission                D00                   D02
24       M0025     Admission                D00                   D04
27       M0028     Admission                D00                   D03
30       M0031     Admission                D00                   D02
33       M0034     Discharge                D00                   D99
36       M0037     Admission                D00                   D03
39       M0040     Admission                D00                   D03
42       M0043     Admission                D00                   D06
45       M0046     Admission                D00                   D04
48       M0049     Admission                D00                   D02
51       M0052     Admission                D00                   D02
54       M0055     Admission                D00                   D03
57       M0058     Admission                D00                   D01

   from_department_name current_department_name
0      outside hospital               discharge
3      outside hospital             orthopedics
6      outside hospital         general surgery
9      outside hospital                     icu
12     outside hospital             orthopedics
15     outside hospital              pediatrics
18     outside hospital                     icu
21     outside hospital        general medicine
24     outside hospital             orthopedics
27     outside hospital              cardiology
30     outside hospital        general medicine
33     outside hospital               discharge
36     outside hospital              cardiology
39     outside hospital              cardiology
42     outside hospital              pediatrics
45     outside hospital             orthopedics
48     outside hospital        general medicine
51     outside hospital        general medicine
54     outside hospital              cardiology
57     outside hospital    emergency department

In [36]:
print(
    patient_flow[
        patient_flow["current_department_id"] == "D99"
    ][
        [
            "movement_id",
            "movement_type",
            "from_department_id",
            "current_department_id",
            "from_department_name",
            "current_department_name"
        ]
    ].head(20)
)

    movement_id movement_type from_department_id current_department_id  \
0         M0001     Discharge                D00                   D99
11        M0012     Discharge                D05                   D99
22        M0023     Discharge                D01                   D99
33        M0034     Discharge                D00                   D99
44        M0045     Discharge                D02                   D99
55        M0056     Discharge                D01                   D99
66        M0067     Discharge                D00                   D99
77        M0078     Discharge                D01                   D99
88        M0089     Discharge                D01                   D99
99        M0100     Discharge                D00                   D99
110       M0111     Discharge                D06                   D99
121       M0122     Discharge                D01                   D99
132       M0133     Discharge                D00                   D99
143       M0144     Discharge                D02                   D99
154       M0155     Discharge                D01                   D99
165       M0166     Discharge                D00                   D99
176       M0177     Discharge                D01                   D99
187       M0188     Discharge                D01                   D99
198       M0199     Discharge                D00                   D99
209       M0210     Discharge                D03                   D99

     from_department_name current_department_name
0        outside hospital               discharge
11                    icu               discharge
22   emergency department               discharge
33       outside hospital               discharge
44       general medicine               discharge
55   emergency department               discharge
66       outside hospital               discharge
77   emergency department               discharge
88   emergency department               discharge
99       outside hospital               discharge
110            pediatrics               discharge
121  emergency department               discharge
132      outside hospital               discharge
143      general medicine               discharge
154  emergency department               discharge
165      outside hospital               discharge
176  emergency department               discharge
187  emergency department               discharge
198      outside hospital               discharge
209            cardiology               discharge

In [37]:
print("Hospital IDs in Hospital Overview:",
      hospital["hospital_id"].nunique())

print("Hospital IDs in Patient Flow:",
      patient_flow["hospital_id"].nunique())

print("Hospital IDs in Department Analytics:",
      department["hospital_id"].nunique())

print("Hospital IDs in Resource Utilization:",
      resource["hospital_id"].nunique())

Hospital IDs in Hospital Overview: 3
Hospital IDs in Patient Flow: 3
Hospital IDs in Department Analytics: 3
Hospital IDs in Resource Utilization: 3

In [38]:
print("Patient Flow hospitals not in Hospital Overview:")

print(
    patient_flow.loc[
        ~patient_flow["hospital_id"].isin(hospital["hospital_id"]),
        "hospital_id"
    ].unique()
)

print("Department Analytics hospitals not in Hospital Overview:")

print(
    department.loc[
        ~department["hospital_id"].isin(hospital["hospital_id"]),
        "hospital_id"
    ].unique()
)

print("Resource Utilization hospitals not in Hospital Overview:")

print(
    resource.loc[
        ~resource["hospital_id"].isin(hospital["hospital_id"]),
        "hospital_id"
    ].unique()
)

Patient Flow hospitals not in Hospital Overview:
[]
Department Analytics hospitals not in Hospital Overview:
[]
Resource Utilization hospitals not in Hospital Overview:
[]

In [39]:
print("Hospital Overview ID data types:")
print(hospital[["hospital_id", "department_id", "patient_id", "admission_id"]].dtypes)

print("\nPatient Flow ID data types:")
print(patient_flow[["hospital_id", "patient_id", "admission_id"]].dtypes)

print("\nDepartment Analytics ID data types:")
print(department[["hospital_id", "department_id"]].dtypes)

print("\nResource Utilization ID data types:")
print(resource[["hospital_id", "department_id"]].dtypes)

Hospital Overview ID data types:
hospital_id      object
department_id    object
patient_id       object
admission_id     object
dtype: object

Patient Flow ID data types:
hospital_id     object
patient_id      object
admission_id    object
dtype: object

Department Analytics ID data types:
hospital_id      object
department_id    object
dtype: object

Resource Utilization ID data types:
hospital_id      object
department_id    object
dtype: object

In [40]:
print("Hospital Overview date range:")
print(hospital["admission_date"].min(), "to", hospital["admission_date"].max())

print("\nPatient Flow date range:")
print(patient_flow["date"].min(), "to", patient_flow["date"].max())

print("\nDepartment Analytics date range:")
print(department["date"].min(), "to", department["date"].max())

print("\nResource Utilization date range:")
print(resource["date"].min(), "to", resource["date"].max())

Hospital Overview date range:
2026-01-01 to 2026-06-30

Patient Flow date range:
2026-01-03 to 2026-07-05

Department Analytics date range:
2026-01-01 to 2026-06-29

Resource Utilization date range:
2026-01-01 to 2026-06-25

In [41]:
print("Common date range across all four datasets:")

start_dates = [
    hospital["admission_date"].min(),
    patient_flow["date"].min(),
    department["date"].min(),
    resource["date"].min()
]

end_dates = [
    hospital["admission_date"].max(),
    patient_flow["date"].max(),
    department["date"].max(),
    resource["date"].max()
]

common_start = max(start_dates)
common_end = min(end_dates)

print("Common start date:", common_start)
print("Common end date:", common_end)

Common date range across all four datasets:
Common start date: 2026-01-03
Common end date: 2026-06-25

In [42]:
print("Hospital Overview:")
print(hospital[["department_id", "department_name"]].drop_duplicates().sort_values("department_id"))

print("\nDepartment Analytics:")
print(department[["department_id", "department_name"]].drop_duplicates().sort_values("department_id"))

print("\nPatient Flow:")
print(
    patient_flow[
        ["current_department_id", "current_department_name"]
    ].drop_duplicates().sort_values("current_department_id")
)

Hospital Overview:
   department_id       department_name
0            D01  emergency department
19           D02      general medicine
27           D03            cardiology
2            D04           orthopedics
4            D05                   icu
10           D06            pediatrics
1            D07       general surgery

Department Analytics:
  department_id       department_name
0           D01  emergency department
5           D02      general medicine
3           D03            cardiology
1           D04           orthopedics
6           D05                   icu
4           D06            pediatrics
2           D07       general surgery

Patient Flow:
   current_department_id current_department_name
13                   D01    emergency department
19                   D02        general medicine
27                   D03              cardiology
2                    D04             orthopedics
4                    D05                     icu
10                   D06              pediatrics
1                    D07         general surgery
0                    D99               discharge

In [43]:
print("Hospital Overview combinations:")
print(
    hospital[["hospital_id", "department_id"]]
    .drop_duplicates()
    .shape[0]
)

print("Department Analytics combinations:")
print(
    department[["hospital_id", "department_id"]]
    .drop_duplicates()
    .shape[0]
)

print("Resource Utilization combinations:")
print(
    resource[["hospital_id", "department_id"]]
    .drop_duplicates()
    .shape[0]
)

print("\nDepartment combinations in Department Analytics not found in Hospital Overview:")
print(
    department[
        ~department.set_index(["hospital_id", "department_id"]).index.isin(
            hospital.set_index(["hospital_id", "department_id"]).index
        )
    ][["hospital_id", "department_id"]]
    .drop_duplicates()
)

print("\nDepartment combinations in Resource Utilization not found in Hospital Overview:")
print(
    resource[
        ~resource.set_index(["hospital_id", "department_id"]).index.isin(
            hospital.set_index(["hospital_id", "department_id"]).index
        )
    ][["hospital_id", "department_id"]]
    .drop_duplicates()
)

Hospital Overview combinations:
21
Department Analytics combinations:
21
Resource Utilization combinations:
21

Department combinations in Department Analytics not found in Hospital Overview:
Empty DataFrame
Columns: [hospital_id, department_id]
Index: []

Department combinations in Resource Utilization not found in Hospital Overview:
Empty DataFrame
Columns: [hospital_id, department_id]
Index: []

In [44]:
print("Hospital Overview:")
print(hospital[["admission_date", "discharge_date"]].dtypes)

print("\nPatient Flow:")
print(patient_flow[["movement_datetime", "movement_date", "date"]].dtypes)

print("\nDepartment Analytics:")
print(department[["date"]].dtypes)

print("\nResource Utilization:")
print(resource[["date", "last_maintenance_date"]].dtypes)

Hospital Overview:
admission_date    object
discharge_date    object
dtype: object

Patient Flow:
movement_datetime    object
movement_date        object
date                 object
dtype: object

Department Analytics:
date    object
dtype: object

Resource Utilization:
date                     object
last_maintenance_date    object
dtype: object

In [45]:
# Convert date columns to datetime

hospital["admission_date"] = pd.to_datetime(
    hospital["admission_date"], errors="coerce"
)

hospital["discharge_date"] = pd.to_datetime(
    hospital["discharge_date"], errors="coerce"
)

patient_flow["movement_datetime"] = pd.to_datetime(
    patient_flow["movement_datetime"], errors="coerce"
)

patient_flow["movement_date"] = pd.to_datetime(
    patient_flow["movement_date"], errors="coerce"
)

patient_flow["date"] = pd.to_datetime(
    patient_flow["date"], errors="coerce"
)

department["date"] = pd.to_datetime(
    department["date"], errors="coerce"
)

resource["date"] = pd.to_datetime(
    resource["date"], errors="coerce"
)

resource["last_maintenance_date"] = pd.to_datetime(
    resource["last_maintenance_date"], errors="coerce"
)

print("Date columns converted successfully.")

Date columns converted successfully.

In [46]:
print("Hospital Overview:")
print(hospital[["admission_date", "discharge_date"]].dtypes)

print("\nPatient Flow:")
print(patient_flow[["movement_datetime", "movement_date", "date"]].dtypes)

print("\nDepartment Analytics:")
print(department[["date"]].dtypes)

print("\nResource Utilization:")
print(resource[["date", "last_maintenance_date"]].dtypes)

Hospital Overview:
admission_date    datetime64[ns]
discharge_date    datetime64[ns]
dtype: object

Patient Flow:
movement_datetime    datetime64[ns]
movement_date        datetime64[ns]
date                 datetime64[ns]
dtype: object

Department Analytics:
date    datetime64[ns]
dtype: object

Resource Utilization:
date                     datetime64[ns]
last_maintenance_date    datetime64[ns]
dtype: object

In [47]:
print("Missing dates after conversion:")

print("\nHospital Overview:")
print(hospital[["admission_date", "discharge_date"]].isna().sum())

print("\nPatient Flow:")
print(patient_flow[["movement_datetime", "movement_date", "date"]].isna().sum())

print("\nDepartment Analytics:")
print(department[["date"]].isna().sum())

print("\nResource Utilization:")
print(resource[["date", "last_maintenance_date"]].isna().sum())

Missing dates after conversion:

Hospital Overview:
admission_date    0
discharge_date    0
dtype: int64

Patient Flow:
movement_datetime    0
movement_date        0
date                 0
dtype: int64

Department Analytics:
date    0
dtype: int64

Resource Utilization:
date                     0
last_maintenance_date    0
dtype: int64

In [48]:
print("Admission ID relationship validation:")

flow_admissions = patient_flow["admission_id"].nunique()
hospital_admissions = hospital["admission_id"].nunique()

print("Unique admissions in Hospital Overview:", hospital_admissions)
print("Unique admissions in Patient Flow:", flow_admissions)

print(
    "Patient Flow admissions not found in Hospital Overview:",
    patient_flow.loc[
        ~patient_flow["admission_id"].isin(hospital["admission_id"]),
        "admission_id"
    ].nunique()
)

Admission ID relationship validation:
Unique admissions in Hospital Overview: 500
Unique admissions in Patient Flow: 500
Patient Flow admissions not found in Hospital Overview: 0

In [49]:
print("Movement sequence validation:")

print("Minimum movement sequence:",
      patient_flow["movement_sequence"].min())

print("Maximum movement sequence:",
      patient_flow["movement_sequence"].max())

print("Missing movement sequences:",
      patient_flow["movement_sequence"].isna().sum())

print("Unique movement sequence values:",
      sorted(patient_flow["movement_sequence"].unique()))

Movement sequence validation:
Minimum movement sequence: 1
Maximum movement sequence: 3
Missing movement sequences: 0
Unique movement sequence values: [np.int64(1), np.int64(2), np.int64(3)]

In [50]:
print("=" * 60)
print("FINAL DATA VALIDATION REPORT")
print("=" * 60)

print("\n1. ROW COUNTS")
print("Hospital Overview:", len(hospital))
print("Patient Flow:", len(patient_flow))
print("Department Analytics:", len(department))
print("Resource Utilization:", len(resource))

print("\n2. MISSING VALUES")
print("Hospital Overview:", hospital.isnull().sum().sum())
print("Patient Flow:", patient_flow.isnull().sum().sum())
print("Department Analytics:", department.isnull().sum().sum())
print("Resource Utilization:", resource.isnull().sum().sum())

print("\n3. EXACT DUPLICATES")
print("Hospital Overview:", hospital.duplicated().sum())
print("Patient Flow:", patient_flow.duplicated().sum())
print("Department Analytics:", department.duplicated().sum())
print("Resource Utilization:", resource.duplicated().sum())

print("\n4. PRIMARY KEY VALIDATION")
print("Hospital Overview duplicate admission IDs:",
      hospital["admission_id"].duplicated().sum())

print("Patient Flow duplicate movement IDs:",
      patient_flow["movement_id"].duplicated().sum())

print("Resource Utilization duplicate resource IDs:",
      resource["resource_utilization_id"].duplicated().sum())

print("\n5. RELATIONSHIP VALIDATION")

unmatched_patients = patient_flow.loc[
    ~patient_flow["patient_id"].isin(hospital["patient_id"]),
    "patient_id"
].nunique()

unmatched_admissions = patient_flow.loc[
    ~patient_flow["admission_id"].isin(hospital["admission_id"]),
    "admission_id"
].nunique()

print("Unmatched patient IDs:", unmatched_patients)
print("Unmatched admission IDs:", unmatched_admissions)

print("\n6. HOSPITAL VALIDATION")

unmatched_flow_hospitals = patient_flow.loc[
    ~patient_flow["hospital_id"].isin(hospital["hospital_id"]),
    "hospital_id"
].nunique()

unmatched_department_hospitals = department.loc[
    ~department["hospital_id"].isin(hospital["hospital_id"]),
    "hospital_id"
].nunique()

unmatched_resource_hospitals = resource.loc[
    ~resource["hospital_id"].isin(hospital["hospital_id"]),
    "hospital_id"
].nunique()

print("Unmatched hospitals in Patient Flow:",
      unmatched_flow_hospitals)

print("Unmatched hospitals in Department Analytics:",
      unmatched_department_hospitals)

print("Unmatched hospitals in Resource Utilization:",
      unmatched_resource_hospitals)

print("\n7. DEPARTMENT VALIDATION")

print("Hospital Overview department IDs:",
      hospital["department_id"].nunique())

print("Department Analytics department IDs:",
      department["department_id"].nunique())

print("Patient Flow current department IDs:",
      patient_flow["current_department_id"].nunique())

print("\n8. DATE VALIDATION")

print("Hospital Overview date range:",
      hospital["admission_date"].min(),
      "to",
      hospital["admission_date"].max())

print("Patient Flow date range:",
      patient_flow["date"].min(),
      "to",
      patient_flow["date"].max())

print("Department Analytics date range:",
      department["date"].min(),
      "to",
      department["date"].max())

print("Resource Utilization date range:",
      resource["date"].min(),
      "to",
      resource["date"].max())

print("\nMissing dates after conversion:")
print("Hospital Overview:",
      hospital[["admission_date", "discharge_date"]].isna().sum().sum())

print("Patient Flow:",
      patient_flow[["movement_datetime", "movement_date", "date"]].isna().sum().sum())

print("Department Analytics:",
      department["date"].isna().sum())

print("Resource Utilization:",
      resource[["date", "last_maintenance_date"]].isna().sum().sum())

print("\n9. MOVEMENT SEQUENCE VALIDATION")

print("Minimum movement sequence:",
      patient_flow["movement_sequence"].min())

print("Maximum movement sequence:",
      patient_flow["movement_sequence"].max())

print("Missing movement sequences:",
      patient_flow["movement_sequence"].isna().sum())

print("\n10. HOSPITAL-DEPARTMENT COMBINATION VALIDATION")

print("Hospital Overview combinations:",
      hospital[["hospital_id", "department_id"]].drop_duplicates().shape[0])

print("Department Analytics combinations:",
      department[["hospital_id", "department_id"]].drop_duplicates().shape[0])

print("Resource Utilization combinations:",
      resource[["hospital_id", "department_id"]].drop_duplicates().shape[0])

print("\n11. OVERALL STATUS")
print("Data validation completed successfully.")
print("Resource Utilization grain observation has been documented.")

============================================================
FINAL DATA VALIDATION REPORT
============================================================

1. ROW COUNTS
Hospital Overview: 500
Patient Flow: 500
Department Analytics: 500
Resource Utilization: 500

2. MISSING VALUES
Hospital Overview: 0
Patient Flow: 0
Department Analytics: 0
Resource Utilization: 0

3. EXACT DUPLICATES
Hospital Overview: 0
Patient Flow: 0
Department Analytics: 0
Resource Utilization: 0

4. PRIMARY KEY VALIDATION
Hospital Overview duplicate admission IDs: 0
Patient Flow duplicate movement IDs: 0
Resource Utilization duplicate resource IDs: 0

5. RELATIONSHIP VALIDATION
Unmatched patient IDs: 0
Unmatched admission IDs: 0

6. HOSPITAL VALIDATION
Unmatched hospitals in Patient Flow: 0
Unmatched hospitals in Department Analytics: 0
Unmatched hospitals in Resource Utilization: 0

7. DEPARTMENT VALIDATION
Hospital Overview department IDs: 7
Department Analytics department IDs: 7
Patient Flow current department IDs: 8

8. DATE VALIDATION
Hospital Overview date range: 2026-01-01 00:00:00 to 2026-06-30 00:00:00
Patient Flow date range: 2026-01-03 00:00:00 to 2026-07-05 00:00:00
Department Analytics date range: 2026-01-01 00:00:00 to 2026-06-29 00:00:00
Resource Utilization date range: 2026-01-01 00:00:00 to 2026-06-25 00:00:00

Missing dates after conversion:
Hospital Overview: 0
Patient Flow: 0
Department Analytics: 0
Resource Utilization: 0

9. MOVEMENT SEQUENCE VALIDATION
Minimum movement sequence: 1
Maximum movement sequence: 3
Missing movement sequences: 0

10. HOSPITAL-DEPARTMENT COMBINATION VALIDATION
Hospital Overview combinations: 21
Department Analytics combinations: 21
Resource Utilization combinations: 21

11. OVERALL STATUS
Data validation completed successfully.
Resource Utilization grain observation has been documented.

In [51]:
validation_report = f"""
MEDTRACK_DV DATA VALIDATION REPORT
==================================

1. ROW COUNTS
Hospital Overview: {len(hospital)}
Patient Flow: {len(patient_flow)}
Department Analytics: {len(department)}
Resource Utilization: {len(resource)}

2. MISSING VALUES
Hospital Overview: {hospital.isnull().sum().sum()}
Patient Flow: {patient_flow.isnull().sum().sum()}
Department Analytics: {department.isnull().sum().sum()}
Resource Utilization: {resource.isnull().sum().sum()}

3. EXACT DUPLICATES
Hospital Overview: {hospital.duplicated().sum()}
Patient Flow: {patient_flow.duplicated().sum()}
Department Analytics: {department.duplicated().sum()}
Resource Utilization: {resource.duplicated().sum()}

4. PRIMARY KEY VALIDATION
Duplicate admission IDs: {hospital["admission_id"].duplicated().sum()}
Duplicate movement IDs: {patient_flow["movement_id"].duplicated().sum()}
Duplicate resource utilization IDs: {resource["resource_utilization_id"].duplicated().sum()}

5. RELATIONSHIP VALIDATION
Unmatched patient IDs: {unmatched_patients}
Unmatched admission IDs: {unmatched_admissions}

6. HOSPITAL VALIDATION
Unmatched hospitals in Patient Flow: {unmatched_flow_hospitals}
Unmatched hospitals in Department Analytics: {unmatched_department_hospitals}
Unmatched hospitals in Resource Utilization: {unmatched_resource_hospitals}

7. DEPARTMENT VALIDATION
Hospital Overview department IDs: {hospital["department_id"].nunique()}
Department Analytics department IDs: {department["department_id"].nunique()}
Patient Flow current department IDs: {patient_flow["current_department_id"].nunique()}

8. DATE VALIDATION
Hospital Overview:
{hospital["admission_date"].min()} to {hospital["admission_date"].max()}

Patient Flow:
{patient_flow["date"].min()} to {patient_flow["date"].max()}

Department Analytics:
{department["date"].min()} to {department["date"].max()}

Resource Utilization:
{resource["date"].min()} to {resource["date"].max()}

9. MOVEMENT SEQUENCE VALIDATION
Minimum movement sequence: {patient_flow["movement_sequence"].min()}
Maximum movement sequence: {patient_flow["movement_sequence"].max()}
Missing movement sequences: {patient_flow["movement_sequence"].isna().sum()}

10. HOSPITAL-DEPARTMENT COMBINATIONS
Hospital Overview:
{hospital[["hospital_id", "department_id"]].drop_duplicates().shape[0]}

Department Analytics:
{department[["hospital_id", "department_id"]].drop_duplicates().shape[0]}

Resource Utilization:
{resource[["hospital_id", "department_id"]].drop_duplicates().shape[0]}

OVERALL STATUS
============
Data validation completed successfully.

Resource Utilization grain observation:
Multiple records share the same hospital, department, date,
resource type, and resource category combination. These records
were retained because they contain different operational
measurements and are not exact duplicates.

The four datasets are ready for use as separate analytical
datasets in Tableau.
"""

with open("../docs/validation_report.txt", "w", encoding="utf-8") as file:
    file.write(validation_report)

print("Validation report saved successfully.")
print("Location: ../docs/validation_report.txt")

Validation report saved successfully.
Location: ../docs/validation_report.txt